### ISSUE TITLE
Unhelpful dashboard error message when user doesn't have permission

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#1006]
Seen in beta.18

Steps taken.
Created user x with read permission on dashboard y (dash queries an index and a statistic)
In another browser session navigate to the direct url for dashboard y.
Log in as user x
Re-enter the direct dash url
You get the following unhelpful error that is hiding server side errors (see further down) that tell you what is happening.

```
java.lang.RuntimeException

java.lang.RuntimeException: Error sending request DocRef{type='Index', uuid='3e72379d-403f-4757-88d5-bfae4d724b55', name='Stroom Family App Events Index'} to /dataSource
	at stroom.datasource.RemoteDataSourceProvider.post(RemoteDataSourceProvider.java:109)
	at stroom.datasource.RemoteDataSourceProvider.getDataSource(RemoteDataSourceProvider.java:61)
	at stroom.dashboard.server.FetchExpressionFieldsHandler.lambda$exec$0(FetchExpressionFieldsHandler.java:49)
	at java.util.Optional.map(Optional.java:215)
	at stroom.dashboard.server.FetchExpressionFieldsHandler.exec(FetchExpressionFieldsHandler.java:48)
	at stroom.dashboard.server.FetchExpressionFieldsHandler.exec(FetchExpressionFieldsHandler.java:31)
	at stroom.task.server.AbstractTaskHandler.exec(AbstractTaskHandler.java:31)
	at sun.reflect.GeneratedMethodAccessor156.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at stroom.security.server.UserSecurityMethodInterceptor.doSecured(UserSecurityMethodInterceptor.java:123)
	at stroom.security.server.UserSecurityMethodInterceptor.secureMethod(UserSecurityMethodInterceptor.java:98)
	at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy178.exec(Unknown Source)
	at stroom.task.server.TaskManagerImpl.doExec(TaskManagerImpl.java:404)
	at stroom.task.server.TaskManagerImpl.exec(TaskManagerImpl.java:222)
	at stroom.dispatch.server.DispatchServiceImpl.exec(DispatchServiceImpl.java:103)
	at sun.reflect.GeneratedMethodAccessor338.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at stroom.dispatch.server.DispatchServiceImpl.service(DispatchServiceImpl.java:145)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
	at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:34)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45)
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at stroom.security.server.SecurityFilter.continueAsUser(SecurityFilter.java:183)
	at stroom.security.server.SecurityFilter.filter(SecurityFilter.java:144)
	at stroom.security.server.SecurityFilter.doFilter(SecurityFilter.java:101)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at stroom.servlet.CacheControlFilter.doFilter(CacheControlFilter.java:70)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at stroom.servlet.RejectPostFilter.doFilter(RejectPostFilter.java:55)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at stroom.servlet.HttpServletRequestFilter.doFilter(HttpServletRequestFilter.java:56)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:308)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:262)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:241)
	at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:455)
	at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:68)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:561)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:334)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:104)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Error 500 sending request DocRef{type='Index', uuid='3e72379d-403f-4757-88d5-bfae4d724b55', name='Stroom Family App Events Index'} to http://127.0.0.1:8080/api/stroom-index/v2/dataSource: Internal Server Error
	at stroom.datasource.RemoteDataSourceProvider.post(RemoteDataSourceProvider.java:103)
	... 92 more
```

```
Caused by: stroom.entity.shared.PermissionException: User 'x' does not have permission to read (DocRef{type='StatisticStore', uuid='378e1c9b-755f-48a5-a883-d0a7dbe3d167', name='Stroom Family App Events SQL Statistic'})
```

```
stroom.entity.shared.PermissionException: User 'x' does not have permission to read (DocRef{type='Index', uuid='3e72379d-403f-4757-88d5-bfae4d724b55', name='Stroom Family App Events Index'})
```

**Comment by GCHQ-11** [comment]
StatisticsDataSourceCacheImpl also causes permissions to be bypassed if the data source has been read by someone else who had permission.

**Comment by GCHQ-11** [comment]
The stats data source cache now uses internal processing user to retrieve the data sources, but that protects the data itself with the security context
