### ISSUE TITLE
Javascript error when running a viz with datetime data

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#1037]
When running a viz that had datatime data passed to it, I saw this in the browser dev tools console.
```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2016-03-T12:00:00.000Z, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (https://192.168.1.16/stroom/stroom/moment-with-locales.min.js:1:3248)
    at gb (https://192.168.1.16/stroom/stroom/moment-with-locales.min.js:1:19736)
    at rb (https://192.168.1.16/stroom/stroom/moment-with-locales.min.js:1:22824)
    at qb (https://192.168.1.16/stroom/stroom/moment-with-locales.min.js:1:22691)
    at pb (https://192.168.1.16/stroom/stroom/moment-with-locales.min.js:1:22410)
    at sb (https://192.168.1.16/stroom/stroom/moment-with-locales.min.js:1:23150)
    at tb (https://192.168.1.16/stroom/stroom/moment-with-locales.min.js:1:23184)
    at a (https://192.168.1.16/stroom/stroom/moment-with-locales.min.js:1:202)
    at Agg (stroom-0.js:9395:25)
    at zgg (stroom-0.js:10229:69)
    at Wgg (stroom-0.js:10457:108)
    at Ygg (stroom-0.js:9072:36)
    at _gg.dhg [as Ud] (stroom-0.js:11488:5655)
    at Gs.Hs [as Md] (stroom-0.js:11472:25687)
    at Xu (stroom-0.js:11094:214)
    at Pu (stroom-0.js:10432:59)
    at Jf (stroom-0.js:4535:26)
    at ebc.Uf [as Rc] (stroom-0.js:11472:7593)
    at bs (stroom-0.js:10298:147)
    at Lf (stroom-0.js:9595:112)
    at ebc._ac [as Vc] (stroom-0.js:11474:23051)
    at Zgg.WKb [as Vc] (stroom-0.js:11473:12345)
    at fSb (stroom-0.js:9013:85)
    at HTMLInputElement.NTb (stroom-0.js:8513:46)
    at Ij (stroom-0.js:5900:29)
    at Lj (stroom-0.js:10366:57)
    at HTMLInputElement.eval (stroom-0.js:8229:46)
w @ moment-with-locales.min.js:1
(anonymous) @ moment-with-locales.min.js:1
gb @ moment-with-locales.min.js:1
rb @ moment-with-locales.min.js:1
qb @ moment-with-locales.min.js:1
pb @ moment-with-locales.min.js:1
sb @ moment-with-locales.min.js:1
tb @ moment-with-locales.min.js:1
a @ moment-with-locales.min.js:1
Agg @ stroom-0.js:9395
zgg @ stroom-0.js:10229
Wgg @ stroom-0.js:10457
Ygg @ stroom-0.js:9072
dhg @ stroom-0.js:11488
Hs @ stroom-0.js:11472
Xu @ stroom-0.js:11094
Pu @ stroom-0.js:10432
Jf @ stroom-0.js:4535
Uf @ stroom-0.js:11472
bs @ stroom-0.js:10298
Lf @ stroom-0.js:9595
_ac @ stroom-0.js:11474
WKb @ stroom-0.js:11473
fSb @ stroom-0.js:9013
NTb @ stroom-0.js:8513
Ij @ stroom-0.js:5900
Lj @ stroom-0.js:10366
(anonymous) @ stroom-0.js:8229
```

**Comment by stroomdev66** [comment]
I've updated the library that is used to parse dates and times (`moment.js`). However this error is due to a badly formed date being entered into a date/time selection box and is therefore somewhat expected behaviour. Basically the lib is expecting to parse a well formed ISO8601 date/time but is being given something else by the user. This is possible as the control is just a text box with an additional date picker attached.
