### ISSUE TITLE
Proxy failing to start with guice error

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#1059]
```
INFO   [2019-01-03T07:44:19.709Z] [main] stroom.startup.App -  Starting Stroom Proxy 
com.google.inject.ConfigurationException: Guice configuration errors:

1) No implementation for stroom.node.server.StroomPropertyService was bound.
  while locating stroom.node.server.StroomPropertyService
    for the 1st parameter of stroom.connectors.ExternalLibService.<init>(ExternalLibService.java:44)
  while locating stroom.connectors.ExternalLibService
    for the 2nd parameter of stroom.connectors.kafka.StroomKafkaProducerFactoryService.<init>(StroomKafkaProducerFactoryService.java:40)
  while locating stroom.connectors.kafka.StroomKafkaProducerFactoryService

2) No implementation for stroom.node.server.StroomPropertyService was bound.
  while locating stroom.node.server.StroomPropertyService
    for the 1st parameter of stroom.connectors.kafka.StroomKafkaProducerFactoryService.<init>(StroomKafkaProducerFactoryService.java:40)
  while locating stroom.connectors.kafka.StroomKafkaProducerFactoryService

2 errors
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1045)
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1004)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1054)
        at stroom.startup.GuiceUtil.addHealthCheck(GuiceUtil.java:29)
        at stroom.startup.App.startProxy(App.java:167)
        at stroom.startup.App.run(App.java:150)
        at stroom.startup.App.run(App.java:108)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
        at io.dropwizard.cli.Cli.run(Cli.java:75)
        at io.dropwizard.Application.run(Application.java:93)
        at stroom.startup.App.main(App.java:120)
```

**Comment by at055612** [comment]
Looks like the kafka/elastic health checks have also been accidentally added to the proxy app which they will not work on.
