### ISSUE TITLE
HeapHistogram stat failing in the docker stack

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#1084]
When the heap histo job runs (when stroom is running in docker) you see the following in the logs 
```
stroom                 | Caused by: java.lang.RuntimeException: Error executing command [jmap, -histo:live, 6]
stroom                 |        at stroom.node.server.HeapHistogramService.generateHeapHistogram(HeapHistogramService.java:91)
stroom                 |        at stroom.node.server.HeapHistogramStatisticsExecutor.exec(HeapHistogramStatisticsExecutor.java:71)
stroom                 |        ... 36 common frames omitted
stroom                 | Caused by: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
stroom                 |        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
stroom                 |        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
stroom                 |        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
stroom                 |        at stroom.node.server.HeapHistogramService.generateHeapHistogram(HeapHistogramService.java:82)
stroom                 |        ... 37 common frames omitted

```

Couple of issues here.  
* The exception at line 91 of HHS needs to output std(err|out)
* The logging at line 123 of HHS is using the wrong format syntax (%s vs {})

When a debugger is attached the content of stderr is 
```
6: Unable to open socket file: target process not responding or HotSpot VM not loaded
```

The java process is running as user `stroom` and so is jmap, as seen from this shell log in the container.
```
/stroom # jps
273 Jps
6 jar
/stroom # 
/stroom # 
/stroom # 
/stroom # ps -ef
PID   USER     TIME  COMMAND
    1 root      0:00 /sbin/tini -- /stroom/docker-entrypoint.sh sh -c echo "JAVA_OPTS: [${JAVA_OPTS}]"; java ${JAVA_OPTS} -jar stroom-app-all.jar server config/config.yml
    6 stroom    1:21 java -Xms50m -Xmx1024m -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=10765,suspend=n -jar stroom-app-all.jar server config/config.yml
  268 root      0:00 sh
  288 stroom    0:00 jmap -histo:live 6
  306 root      0:00 ps -ef
/stroom # 
```

**Comment by at055612** [comment]
It looks like the heap histo can be obtained internally using the following
```
        DiagnosticCommandMBean dcmd = ManagementFactoryHelper.getDiagnosticCommandMBean();
        String[] emptyStringArgs = {};
        Object[] dcmdArgs = { emptyStringArgs };
        String[] signature = { String[].class.getName() };
        System.out.println(dcmd.invoke("gcClassHistogram", dcmdArgs, signature));
```
This would also save us having to run the full jdk in the container
