### ISSUE TITLE
stroom.util.StreamDumpTool errors with  Missing table: ACTIVITY on stroom-app-5.5.10

### ISSUE THREAD

**Issue by burnalting** [gchq/stroom#1187]
Using the following log4j.xml configuration in /opt/stroom/stroom-app/stroom-extraction.log4j.xml

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">

<log4j:configuration xmlns:log4j='http://jakarta.apache.org/log4j/'>
  <appender name="STROOM" class="org.apache.log4j.RollingFileAppender">
    <param name="File" value="instance/logs/stroom-extraction.log"/>
    <param name="MaxBackupIndex" value="10"/>
    <param name="MaxFileSize" value="100MB"/>
    <param name="Append" value="true"/>
    <layout class="org.apache.log4j.EnhancedPatternLayout">
        <param name="ConversionPattern" value="%d{yyyy-MM-dd'T'HH:mm:ss.SSS'Z'}{GMT+0} %-5p [%t] %C{2} (%F:%L) - %m%n" />
    </layout>
  </appender>

  <logger name="org.hibernate">
    <level value="fatal"/>
  </logger>

  <logger name="stroom" additivity="false">
    <level value="debug"/>
    <appender-ref ref="STROOM"/>
  </logger>

  <root>
    <level value="ERROR" />
    <appender-ref ref="STROOM" />
  </root>
</log4j:configuration>
```

Running 
```bash
cd /opt/stroom/stroom-app
java -cp "apache-tomcat-7.0.53/lib/*:lib/*:instance/webapps/stroom/WEB-INF/lib/*" -Dlog4j.configuration=file:`pwd`/stroom-extraction.log4j.xml stroom.util.StreamDumpTool outputDir=/stroomdata/stroom-extraction streamType="Raw Events" format="\${streamType}/\${feed}/\${pathId}/\${id}"
Creating directory '/stroomdata/stroom-extraction'
```
result in the following

> Creating directory '/stroomdata/stroom-extraction'
> Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in stroom.spring.PersistenceConfiguration: Invocation of init method failed; nested exception is org.hibernate.HibernateException: Missing table: ACTIVITY
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
> 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
> 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
> 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1054)
> 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:829)
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
> 	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
> 	at stroom.util.StreamDumpTool.buildAppContext(StreamDumpTool.java:252)
> 	at stroom.util.StreamDumpTool.getAppContext(StreamDumpTool.java:245)
> 	at stroom.util.StreamDumpTool.run(StreamDumpTool.java:121)
> 	at stroom.util.AbstractCommandLineTool.doMain(AbstractCommandLineTool.java:95)
> 	at stroom.util.StreamDumpTool.main(StreamDumpTool.java:64)
> Caused by: org.hibernate.HibernateException: Missing table: ACTIVITY
> 	at org.hibernate.cfg.Configuration.validateSchema(Configuration.java:1335)
> 	at org.hibernate.tool.hbm2ddl.SchemaValidator.validate(SchemaValidator.java:175)
> 	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:525)
> 	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1859)
> 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:852)
> 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:845)
> 	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.withTccl(ClassLoaderServiceImpl.java:398)
> 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:844)
> 	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60)
> 	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:343)
> 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:318)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
> 	... 15 more

**Comment by burnalting** [comment]
My next run after creating a correctly configured /opt/stroom/.stroom/stroom.conf solves the problem :-)
