### ISSUE TITLE
ERROR stroom.streamstore.server.StreamAttributeMapUtil

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#1202]
Proper stack to follow

stroom.streamstore.streamattributeMapRetentionRuleDecorator.addMatchingRetentionRuleInfo (:53)
stroom.streamstore.StreamAttributeMapUtil.createAttibuteMap (:56)
ArrayList.foreach
stroom.streamstore.StreamAttributeMapUtil.lambda$createAttibuteMap$0 (:70)

 then java long stuff, against  feed name

**Comment by stroomdev10** [comment]
```
java.lang.NumberFormatException: For input string: &#34;FEED-NAME&#34;
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.valueOf(Long.java:803)
	at stroom.streamstore.server.StreamAttributeMapUtil.lambda$createAttributeMap$0(StreamAttributeMapUtil.java:70)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at stroom.streamstore.server.StreamAttributeMapUtil.createAttributeMap(StreamAttributeMapUtil.java:56)
	at stroom.streamstore.server.StreamAttributeMapRetentionRuleDecorator.addMatchingRetentionRuleInfo(StreamAttributeMapRetentionRuleDecorator.java:53)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1628)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```
