### ISSUE TITLE
SQL Stats queries are failing

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#1447]
```
1 error
	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1053)
	at stroom.statistics.impl.sql.search.StatisticsSearchServiceImpl.lambda$getFlowableQueryResults$17(StatisticsSearchServiceImpl.java:370)
	at io.reactivex.internal.operators.flowable.FlowableGenerate.subscribeActual(FlowableGenerate.java:45)
	at io.reactivex.Flowable.subscribe(Flowable.java:13610)
	at io.reactivex.Flowable.subscribe(Flowable.java:13556)
	at io.reactivex.internal.operators.flowable.FlowableUsing.subscribeActual(FlowableUsing.java:74)
	at io.reactivex.Flowable.subscribe(Flowable.java:13610)
	at io.reactivex.Flowable.subscribe(Flowable.java:13556)
	at io.reactivex.internal.operators.flowable.FlowableConcatMap$ConcatMapImmediate.drain(FlowableConcatMap.java:344)
	at io.reactivex.internal.operators.flowable.FlowableConcatMap$BaseConcatMapSubscriber.onNext(FlowableConcatMap.java:159)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onNext(FlowableSubscribeOn.java:97)
	at io.reactivex.internal.subscriptions.ScalarSubscription.request(ScalarSubscription.java:55)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.requestUpstream(FlowableSubscribeOn.java:133)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onSubscribe(FlowableSubscribeOn.java:90)
	at io.reactivex.internal.operators.flowable.FlowableJust.subscribeActual(FlowableJust.java:34)
	at io.reactivex.Flowable.subscribe(Flowable.java:13610)
	at io.reactivex.Flowable.subscribe(Flowable.java:13556)
	at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:261)
	at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:226)
	at stroom.task.impl.ExecutorProviderImpl.lambda$get$0(ExecutorProviderImpl.java:59)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.NullPointerException: Null user identity
	at stroom.task.impl.TaskManagerImpl.getUserIdentity(TaskManagerImpl.java:276)
	at stroom.task.impl.TaskContextProvider.get(TaskContextProvider.java:22)
	at stroom.task.impl.TaskContextProvider.get(TaskContextProvider.java:10)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:85)
	at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:77)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:59)
	at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
	... 23 common frames omitted
```

**Comment by at055612** [comment]
This appears to have been fixed.  sql stat queries working ok.
