### ISSUE TITLE
v7.0-beta-23 won't run against MySQL 8 due to SQL errors

### ISSUE THREAD

**Issue by robin54747** [gchq/stroom#1462]
When pointed to a fresh MySQL 8.0 setup, STROOM v7.0-beta-23 stops with the following:
```
1) Error in custom provider, java.lang.RuntimeException: Expression #1 of ORDER BY clause is not in SELECT list, references column 'stroom.doc.id' which is not in SELECT list; this is incompatible with DISTINCT
  at stroom.data.retention.impl.DataRetentionModule.getRules(Unknown Source) (via modules: stroom.app.guice.AppModule -> stroom.app.guice.CoreModule -> stroom.data.retention.impl.DataRetentionModule)
  while locating stroom.data.retention.shared.DataRetentionRules
  at stroom.meta.impl.StreamAttributeMapRetentionRuleDecorator.<init>(Unknown Source)
  while locating stroom.meta.impl.StreamAttributeMapRetentionRuleDecorator
    for the 3rd parameter of stroom.meta.impl.MetaResourceImpl.<init>(Unknown Source)
  while locating stroom.meta.impl.MetaResourceImpl
  while locating stroom.util.shared.RestResource annotated with @com.google.inject.internal.Element(setName=,uniqueId=165, type=MULTIBINDER, keyType=)
  while locating java.util.Set<stroom.util.shared.RestResource>
    for the 2nd parameter of stroom.dropwizard.common.RestResources.<init>(Unknown Source)
  while locating stroom.dropwizard.common.RestResources
    for field at stroom.app.App.restResources(Unknown Source)
  while locating stroom.app.App

1 error
        at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:73)
        at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:1014)
        at stroom.app.App.run(App.java:157)
        at stroom.app.App.run(App.java:65)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at stroom.app.App.main(App.java:95)
Caused by: java.lang.RuntimeException: Expression #1 of ORDER BY clause is not in SELECT list, references column 'stroom.doc.id' which is not in SELECT list; this is incompatible with DISTINCT
        at stroom.docstore.impl.db.DBPersistence.list(DBPersistence.java:156)
        at stroom.docstore.impl.StoreImpl.createDocRefList(StoreImpl.java:521)
        at stroom.docstore.impl.StoreImpl.list(StoreImpl.java:494)
        at stroom.docstore.impl.StoreImpl.listDocuments(StoreImpl.java:226)
        at stroom.data.retention.impl.DataRetentionRulesServiceImpl.listDocuments(DataRetentionRulesServiceImpl.java:119)
        at stroom.data.retention.impl.DataRetentionModule.getRules(DataRetentionModule.java:40)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at com.google.inject.internal.ProviderMethod$ReflectionProviderMethod.doProvision(ProviderMethod.java:286)
        at com.google.inject.internal.ProviderMethod.doProvision(ProviderMethod.java:173)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.provision(InternalProviderInstanceBindingImpl.java:185)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$CyclicFactory.get(InternalProviderInstanceBindingImpl.java:162)
        at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
        at stroom.meta.impl.StreamAttributeMapRetentionRuleDecorator.<init>(StreamAttributeMapRetentionRuleDecorator.java:51)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
        at com.google.inject.internal.DefaultConstructionProxyFactory$ReflectiveProxy.newInstance(DefaultConstructionProxyFactory.java:126)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:198)
        at com.google.inject.internal.RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:151)
        at com.google.inject.internal.InternalProviderInstanceBindingImpl$Factory.get(InternalProviderInstanceBindingImpl.java:113)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:52)
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:147)
        at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:101)
        at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:71)
        ... 8 more
Caused by: java.sql.SQLException: Expression #1 of ORDER BY clause is not in SELECT list, references column 'stroom.doc.id' which is not in SELECT list; this is incompatible with DISTINCT
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:970)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1020)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
        at stroom.docstore.impl.db.DBPersistence.list(DBPersistence.java:146)
        ... 51 more
```

**Comment by gcdev373** [comment]
Change rolled back to investigate test issues

**Comment by gcdev373** [comment]
Change rolled back due to failing tests.
