### ISSUE TITLE
Missing fields in imported stat entities

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#1538]
Having run setupSampleData, all of the internal stat entities have no fields in them.  Some should have fields, e.g. Node.  When you query one you then get:

```
ERROR 2020-05-06T14:09:07.824Z dw-27 - POST /api/sqlstatistics/v2/search s.s.i.s.s.SqlStatisticsSearchResponseCreatorManager Unexpected fieldName Node 
java.lang.RuntimeException: Unexpected fieldName Node
	at stroom.statistics.impl.sql.search.StatisticsSearchServiceImpl.lambda$buildResultSetMapper$7(StatisticsSearchServiceImpl.java:225)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Collections.java:1576)
	at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1743)
	at java.base/java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.forEachRemaining(Collections.java:1601)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
```

**Comment by stroomdev66** [comment]
Fixed alongside #1396
