### ISSUE TITLE
Errors in stat and possibly lucene queries are not being propagated back to the UI properly

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#1542]
For example run a stats query with no date term.  It should error as it needs one.  In the UI you get
```
java.lang.RuntimeException: Error sending request SearchRequest{key=9a1a9732-df96-415f-8f5a-67973c60d73d|CountStatisticsSQL|query-NZU2J|SRRB_1588798885179, query=Query{dataSource=DocRef{type='StatisticStore', uuid='e2528c85-722e-46e0-91b6-742149691047', name='CountStatisticSQL'}, expression=AND {user = user1}, params=[Param{key='currentUser()', value='admin'}]}, resultRequests=[ResultRequest{componentId='table-Q0DWW', mappings=[TableSettings{queryId='query-NZU2J', fields=[Field{id='table-Q0DWW|BES8C', name='Date Time', expression='${Date Time}', sort=Sort{order=0, direction=ASCENDING}, filter=null, format=Format{type=DATE_TIME, numberFormat=null, dateTimeFormat=null}, group=null}, Field{id='table-Q0DWW|7F591', name='state', expression='${state}', sort=null, filter=null, format=Format{type=GENERAL, numberFormat=null, dateTimeFormat=null}, group=null}, Field{id='table-Q0DWW|KI7KE', name='colour', expression='${colour}', sort=null, filter=null, format=Format{type=GENERAL, numberFormat=null, dateTimeFormat=null}, group=null}, Field{id='table-Q0DWW|WYWXL', name='user', expression='${user}', sort=null, filter=null, format=Format{type=GENERAL, numberFormat=null, dateTimeFormat=null}, group=null}, Field{id='table-Q0DWW|I91WR', name='Precision ms', expression='${Precision ms}', sort=null, filter=null, format=Format{type=NUMBER, numberFormat=null, dateTimeFormat=null}, group=null}, Field{id='table-Q0DWW|ID60B', name='Statistic Count', expression='${Statistic Count}', sort=null, filter=null, format=Format{type=NUMBER, numberFormat=null, dateTimeFormat=null}, group=null}], extractValues=true, extractionPipeline=null, maxResults=[1000000], showDetail=null}], requestedRange=OffsetRange{offset=0, length=100}, openGroups=null, resultStyle=TABLE, fetch=CHANGES}], dateTimeLocale='Europe/London', incremental=true, timeout=null} to http://localhost:8080/api/sqlstatistics/v2/search
```

On the server you get 
```
ERROR 2020-05-06T21:01:25.256Z dw-146 - POST /api/sqlstatistics/v2/search s.s.i.s.s.SqlStatisticsSearchResponseCreatorManager Search queries on the statistic store must contain one term using the 'Date Time' field with one of the following condtitions [[BETWEEN]].  Please amend the query 
java.lang.UnsupportedOperationException: Search queries on the statistic store must contain one term using the 'Date Time' field with one of the following condtitions [[BETWEEN]].  Please amend the query
	at stroom.statistics.impl.sql.search.StatStoreCriteriaBuilder.buildCriteria(StatStoreCriteriaBuilder.java:92)
	at stroom.statistics.impl.sql.search.SqlStatisticsStore.<init>(SqlStatisticsStore.java:78)
	at stroom.statistics.impl.sql.search.SqlStatisticStoreFactory.buildStore(SqlStatisticStoreFactory.java:81)
	at stroom.statistics.impl.sql.search.SqlStatisticStoreFactory.create(SqlStatisticStoreFactory.java:67)
	at stroom.statistics.impl.sql.search.SqlStatisticsSearchResponseCreatorManager.create(SqlStatisticsSearchResponseCreatorManager.java:54)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$2(LocalLoadingCache.java:140)
	at com.github.benmanes.caffeine.cache.LocalCache.lambda$statsAware$0(LocalCache.java:139)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2379)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1908)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2377)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2360)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:54)
	at stroom.cache.impl.CacheManagerImpl$1.get(CacheManagerImpl.java:92)
	at stroom.statistics.impl.sql.search.SqlStatisticsSearchResponseCreatorManager.get(SqlStatisticsSearchResponseCreatorManager.java:68)
	at stroom.statistics.impl.sql.search.StatisticsQueryServiceImpl.buildResponse(StatisticsQueryServiceImpl.java:106)
	at stroom.statistics.impl.sql.search.StatisticsQueryServiceImpl.lambda$search$1(StatisticsQueryServiceImpl.java:84)
	at stroom.security.impl.SecurityContextImpl.useAsReadResult(SecurityContextImpl.java:300)
	at stroom.statistics.impl.sql.search.StatisticsQueryServiceImpl.search(StatisticsQueryServiceImpl.java:66)
	at stroom.statistics.impl.sql.search.SqlStatisticsQueryResource.search(SqlStatisticsQueryResource.java:83)
```

Search queries are made more complicated as there are two rest calls going on (ui -> server, server -> server)

**Comment by at055612** [comment]
Will be fixed by #1782
