### ISSUE TITLE
Cannot use RuleSet with STROOM Proxy in v7.0-beta.35

### ISSUE THREAD

**Issue by outside-free** [gchq/stroom#1621]
Using stack stroom_core_test-v7.0-beta.35:

After creating a RuileSet and a API key for admin user (being lazy there!), I edited `volumes/stroom-proxy-local/config/config.yml`:
* uncomment `proxyRequestConfig:` 
* set the UUID value for `proxyRequestConfig/receiptPolicyUuid` for the RuleSet
* uncommented `contentSyncConfig:`
* set the API Key for `contentSyncConfig/apiKey`

After restarting STROOM, if I post anything, regardless of whether it uses a client cert or not, then it responds with a `500`:
```<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 null - </title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /stroom/noauth/datafeed/. Reason:
<pre>    null - </pre></p>
</body>
</html>
```

And in the proxy logs (using `docker logs -f stroom-proxy-local`) this NPE appears for every POST:
```
ERROR  [2020-06-02T08:40:13.173Z] [dw-26 - POST /stroom/noauth/datafeed/] stroom.receive.common.StroomStreamException -  sendErrorResponse() - 500 null -
ERROR  [2020-06-02T08:40:13.175Z] [dw-26 - POST /stroom/noauth/datafeed/] stroom.proxy.app.handler.ProxyRequestHandler -  "handleException()","Accept=*/*","Connection=close","Content-Length=8262","Content-Type=application/x-www-form-urlencoded","Environment=TEST","Feed=TEST","Host=localhost","RemoteCertExpiry=2022-04-06T15:29:10.000Z","RemoteDN=CN=A Stroom Client,O=GCHQ,L=Cheltenham,C=UK","System=TEST","User-Agent=curl/7.29.0","X-Forwarded-For=172.18.0.1","X-SSL-CLIENT-S-DN=CN=A Stroom Client,O=GCHQ,L=Cheltenham,C=UK","X-SSL-Client-V-End=Apr  6 15:29:10 2022 GMT","X-SSL-Client-V-Start=Jan  2 15:29:10 2020 GMT","X-SSL-Client-Verify=SUCCESS","X-SSL-Protocol=TLSv1.2"
java.lang.NullPointerException: null
        at stroom.docstore.impl.JsonSerialiser2.read(JsonSerialiser2.java:30)
        at stroom.docstore.impl.StoreImpl.read(StoreImpl.java:530)
        at stroom.docstore.impl.StoreImpl.readDocument(StoreImpl.java:280)
        at stroom.docstore.impl.StoreImpl.readDocument(StoreImpl.java:62)
        at stroom.receive.rules.impl.ReceiveDataRuleSetServiceImpl.readDocument(ReceiveDataRuleSetServiceImpl.java:141)
        at stroom.receive.rules.impl.ReceiveDataRuleSetServiceImpl.readDocument(ReceiveDataRuleSetServiceImpl.java:43)
        at stroom.receive.rules.impl.ReceiveDataPolicyChecker.refresh(ReceiveDataPolicyChecker.java:83)
        at stroom.receive.rules.impl.ReceiveDataPolicyChecker.getChecker(ReceiveDataPolicyChecker.java:70)
        at stroom.receive.rules.impl.ReceiveDataPolicyChecker.check(ReceiveDataPolicyChecker.java:65)
        at stroom.receive.rules.impl.DataReceiptPolicyAttributeMapFilter.filter(DataReceiptPolicyAttributeMapFilter.java:39)
        at stroom.proxy.app.handler.ProxyRequestHandler.stream(ProxyRequestHandler.java:76)
        at stroom.proxy.app.handler.ProxyRequestHandler.handle(ProxyRequestHandler.java:56)
        at stroom.receive.common.ReceiveDataServlet.handleRequest(ReceiveDataServlet.java:86)
        at stroom.receive.common.ReceiveDataServlet.doPost(ReceiveDataServlet.java:60)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
        at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45)
        at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at stroom.proxy.app.servlet.ProxySecurityFilter.filter(ProxySecurityFilter.java:142)
        at stroom.proxy.app.servlet.ProxySecurityFilter.doFilter(ProxySecurityFilter.java:101)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:311)
        at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:265)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:239)
        at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:703)
        at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:67)
        at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:505)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by at055612** [comment]
There appear to be a number of issues here.  The doc type has changed to ReceivedDataRuleSet so the proxy config needs to change.  Also proxy is still using the default creds when an API key has been set in config.  Also the old v1 dictionary and rule set resources need to be merged with the new v2 ones.
