### ISSUE TITLE
NPE at net.sf.saxon.tree.tiny.TinyBuilder.endDocument line 168

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#179]
This has occurred a few times. Possibly an issue with template reuse concurrency. Not able to reproduce readily.

**Comment by stroomdev10** [comment]
FATAL java.lang.NullPointerException at net.sf.saxon.tree.tiny.TinyBuilder(TinyBuilder.java:168)
at net.sf.saxon.event.ProxyReceiver.endDocument(ProxyReceiver.java:120)
at net.sf.saxon.event.ReceivingContentHandler.endDocument(ReceivingContentHandler.java:236)
at net.sf.saxon.jaxp.TransformerHandlerImpl.endDocument(TransformerHandlerImpl.java:165)
at stroom.pipeline.server.filter.XSLTFilter.endDocument(XSLTFilter.java:354)
at stroom.pipeline.server.filter.AbstractXSLTFilter.endDocument(AbstractXSLTFilter.java:168)
at stroom.pipeline.server.filter.XSLTFilter.endDocument(XSLTFilter.java:372)
at stroom.pipeline.server.filter.AbstractXSLTFilter.endDocument(AbstractXSLTFilter.java:168)
at stroom.pipeline.server.filter.SplitFilter.endElement(SplitFilter.java:320)
at stroom.pipeline.server.filter.AbstractXSLTFilter.endElement(AbstractXSLTFilter.java:353)
at stroom.pipeline.server.filter.RecordCountFilter.endElement(RecordCountFilter.java:204)
at com.sun.org.apache.xerces.internal.parsers.Abstr...
