### ISSUE TITLE
Warning Message on Searches with large number of results

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#1991]
7-beta.76
When running a search that could match over 1M events, the search will stop and show the following warning:
`unable to create native thread: possibly out of memory or process/resource limits reached`

Sometimes the search has returned 1M rows when this happens but sometimes it's several 10s of k rows less, the exactly number varies.  Upping the Maximum Results value for the query has no effect - it still limits to 1M rows and stops with the warning.  Reducing the Maximum Results value appears to limit the results as expected but the warning still appears some time after it's reached the limit.

Possibly connected but three of the four nodes generate errors at the same time or several seconds after the warning appears:
`WARN   [2021-01-08T08:09:30.684Z] [ForkJoinPool.commonPool-worker-3] com.github.benmanes.caffeine.cache.BoundedLocalCache -  Exception thrown by removal listener 
stroom.security.impl.exception.AuthenticationException: No user is currently logged in
	at stroom.security.impl.SecurityContextImpl.hasAppPermission(SecurityContextImpl.java:121)
	at stroom.security.impl.SecurityContextImpl.isAdmin(SecurityContextImpl.java:74)
	at stroom.security.impl.SecurityContextImpl.checkAdmin(SecurityContextImpl.java:512)
	at stroom.security.impl.SecurityContextImpl.secure(SecurityContextImpl.java:339)
	at stroom.task.impl.TaskManagerImpl.terminate(TaskManagerImpl.java:404)
	at stroom.search.impl.RemoteSearchResultFactory.destroy(RemoteSearchResultFactory.java:70)
	at stroom.search.impl.RemoteSearchResults.lambda$new$0(RemoteSearchResults.java:33)
	at stroom.cache.impl.CacheManagerImpl.lambda$create$2(CacheManagerImpl.java:79)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$notifyRemoval$1(BoundedLocalCache.java:333)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1429)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
`

**Comment by stroomdev66** [comment]
This is likely fixed with the new implementation.
