### ISSUE TITLE
SQLException during SQL Stats Aggregation when running v6.1.32 against MySQL 8.0.21 InnoDB Cluster

### ISSUE THREAD

**Issue by robin54747** [gchq/stroom#2045]
The error is:
```
java.sql.SQLException: The table does not comply with the requirements of an external plugin.
```

This is after restoring a dump of a fresh STROOM 6.1.32 from a MySQL 5.5.62 database into the MySQL 8.0.21 InnoDB Cluster. STROOM is running from a 6.1.32 stack (except db of course.)

Not sure if that has any relationship to ...

**Comment by robin54747** [comment]
A stack trace:
```
INFO   [2021-02-15T09:45:05.718Z] [Stroom P2 #1 - LifecycleTask] stroom.statistics.server.sql.SQLStatisticAggregationManager -  SQL Statistic Aggregation - start 
ERROR  [2021-02-15T09:45:05.762Z] [Stroom P2 #1 - LifecycleTask] stroom.entity.server.util.ConnectionUtil -  executeUpdate() - [UPDATE SQL_STAT_VAL_SRC SET PROCESSING = 1 LIMIT ? , [1000000]] {} 
java.sql.SQLException: The table does not comply with the requirements by an external plugin.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:970)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1109)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1057)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1377)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1042)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:384)
	at stroom.entity.server.util.ConnectionUtil.executeUpdate(ConnectionUtil.java:118)
	at stroom.statistics.server.sql.SQLStatisticAggregationTransactionHelper.doAggregateSQL_Update(SQLStatisticAggregationTransactionHelper.java:186)
	at stroom.statistics.server.sql.SQLStatisticAggregationTransactionHelper.aggregateConfigStage1(SQLStatisticAggregationTransactionHelper.java:272)
	at stroom.statistics.server.sql.SQLStatisticAggregationManager.aggregate(SQLStatisticAggregationManager.java:132)
	at stroom.statistics.server.sql.SQLStatisticAggregationManager.aggregate(SQLStatisticAggregationManager.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at stroom.util.spring.StroomBeanStore.invoke(StroomBeanStore.java:150)
	at stroom.util.spring.StroomBeanMethodExecutable.exec(StroomBeanMethodExecutable.java:63)
	at stroom.jobsystem.server.ScheduledTaskExecutorImpl$JobNodeTrackedExecutable.exec(ScheduledTaskExecutorImpl.java:213)
	at stroom.lifecycle.LifecycleTaskHandler.exec(LifecycleTaskHandler.java:38)
	at stroom.lifecycle.LifecycleTaskHandler.exec(LifecycleTaskHandler.java:28)
	at stroom.task.server.AbstractTaskHandler.exec(AbstractTaskHandler.java:31)
	at sun.reflect.GeneratedMethodAccessor182.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at stroom.security.server.UserSecurityMethodInterceptor.secureMethod(UserSecurityMethodInterceptor.java:91)
	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy196.exec(Unknown Source)
	at stroom.task.server.TaskFactory.lambda$createRunnable$1(TaskFactory.java:89)
	at stroom.task.server.TaskFactory.lambda$wrapSupplier$10(TaskFactory.java:147)
	at stroom.task.server.TaskFactory.lambda$createRunnable$2(TaskFactory.java:96)
	at stroom.task.server.TaskManagerImpl.lambda$null$0(TaskManagerImpl.java:88)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
WARN   [2021-02-15T09:45:05.769Z] [Stroom P2 #1 - LifecycleTask] stroom.entity.server.util.EntityServiceExceptionUtil -  unwrap() - wrapping exception The table does not comply with the requirements by an external plugin. The table does not comply with the requirements by an external plugin. (increase log level to debug to see stack trace) 
ERROR  [2021-02-15T09:45:05.778Z] [Stroom P2 #1 - LifecycleTask] stroom.statistics.server.sql.SQLStatisticAggregationManager -  Unable to save record state: The table does not comply with the requirements by an external plugin. 
stroom.entity.shared.EntityServiceException: Unable to save record state: The table does not comply with the requirements by an external plugin.
	at stroom.entity.server.util.EntityServiceExceptionUtil.unwrap(EntityServiceExceptionUtil.java:176)
	at stroom.entity.server.util.EntityServiceExceptionUtil.unwrap(EntityServiceExceptionUtil.java:133)
	at stroom.entity.server.util.EntityServiceExceptionUtil.create(EntityServiceExceptionUtil.java:49)
	at stroom.statistics.server.sql.SQLStatisticAggregationManager.aggregate(SQLStatisticAggregationManager.java:142)
	at stroom.statistics.server.sql.SQLStatisticAggregationManager.aggregate(SQLStatisticAggregationManager.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at stroom.util.spring.StroomBeanStore.invoke(StroomBeanStore.java:150)
	at stroom.util.spring.StroomBeanMethodExecutable.exec(StroomBeanMethodExecutable.java:63)
	at stroom.jobsystem.server.ScheduledTaskExecutorImpl$JobNodeTrackedExecutable.exec(ScheduledTaskExecutorImpl.java:213)
	at stroom.lifecycle.LifecycleTaskHandler.exec(LifecycleTaskHandler.java:38)
	at stroom.lifecycle.LifecycleTaskHandler.exec(LifecycleTaskHandler.java:28)
	at stroom.task.server.AbstractTaskHandler.exec(AbstractTaskHandler.java:31)
	at sun.reflect.GeneratedMethodAccessor182.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at stroom.security.server.UserSecurityMethodInterceptor.secureMethod(UserSecurityMethodInterceptor.java:91)
	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy196.exec(Unknown Source)
	at stroom.task.server.TaskFactory.lambda$createRunnable$1(TaskFactory.java:89)
	at stroom.task.server.TaskFactory.lambda$wrapSupplier$10(TaskFactory.java:147)
	at stroom.task.server.TaskFactory.lambda$createRunnable$2(TaskFactory.java:96)
	at stroom.task.server.TaskManagerImpl.lambda$null$0(TaskManagerImpl.java:88)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

**Comment by robin54747** [comment]
Just to confirm, this is the case whether upgrading, or starting with an empty database.
