### ISSUE TITLE
Proxy aggregation is not thread-safe

### ISSUE THREAD

**Issue by p-kimberley** [gchq/stroom#2181]
# Summary
Attempting to use multiple forwarding threads results in an unhandled exception when trying to rename the file `/stroom-proxy/repo/<time-based filename>.lock/<date>/<feed name>/<sequence no>.zip.lock`.

# Setup
Three remote proxies, set to store and forward to a Stroom v6.1 instance

# Proxy configuration
`
proxyRepositoryConfig.readCron: "* * *"
proxyRepositoryReaderConfig.readCron: "* * *"
proxyRepositoryReaderConfig.forwardThreadCount: 4
proxyRepositoryReaderConfig.maxStreamSize: "1G"
`

An exception is not thrown if `forwardThreadCount` is set to `1`.

# Exception

> ERROR  [2021-04-20T07:37:00.828Z] [dw-19 - POST /stroom/datafeed] stroom.proxy.handler.ProxyRequestHandler -  "handleException()","Accept=*/*","Accept-Encoding=gzip, deflate","Compression=Gzip","Content-Length=7716290","Content-Type=text/csv","Feed=TWITTER","FileName=twitter-20.csv","GUID=94643680-0a43-4a1b-b77a-09d91a287900","Host=proxy.stroom.internal","ReceivedTime=2021-04-20T07:36:59.784Z","RemoteAddress=10.0.10.51","RemoteHost=10.0.10.51","User-Agent=python-requests/2.25.1","X-Forwarded-For=10.0.10.51","X-Forwarded-Host=proxy.stroom.internal","X-Forwarded-Port=443","X-Forwarded-Proto=https","X-Real-IP=10.0.10.51","X-Request-ID=3dd2dc6a745490fea183a623614145b1","X-Scheme=https"
java.io.IOException: Failed to rename file /stroom-proxy/repo/2021-04-20T07#36#40,468Z.lock/1a00467c-a032-4daa-85fa-2d8228d35813/2021-04-20/TWITTER/003.zip.lock to /stroom-proxy/repo/2021-04-20T07#36#40,468Z.lock/1a00467c-a032-4daa-85fa-2d8228d35813/2021-04-20/TWITTER/003.zip
	at stroom.proxy.repo.StroomZipOutputStreamImpl.close(StroomZipOutputStreamImpl.java:149)
	at stroom.proxy.repo.StroomZipRepository$2.close(StroomZipRepository.java:373)
	at stroom.proxy.repo.ProxyRepositoryStreamHandler.handleFooter(ProxyRepositoryStreamHandler.java:56)
	at stroom.proxy.handler.ProxyRequestHandler.stream(ProxyRequestHandler.java:93)
	at stroom.proxy.handler.ProxyRequestHandler.handle(ProxyRequestHandler.java:51)
	at stroom.datafeed.server.DataFeedServlet.handleRequest(DataFeedServlet.java:83)
	at stroom.datafeed.server.DataFeedServlet.doPost(DataFeedServlet.java:57)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45)
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at stroom.proxy.security.ProxySecurityFilter.filter(ProxySecurityFilter.java:134)
	at stroom.proxy.security.ProxySecurityFilter.doFilter(ProxySecurityFilter.java:93)

**Comment by p-kimberley** [comment]
An update on this - the issue presents itself only when enabling stream _rolling_. If support for rolling streams is dropped, this issue can be closed.

**Comment by stroomdev66** [comment]
Rolling streams has been dropped
