### ISSUE TITLE
create_account fails silently if you specify a blank password

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2361]
`create_account -u 10_is_great -p ""` fails silently

**Comment by at055612** [comment]
When I tried this via an IJ run config with `--password ""` I got
```
INFO  2021-08-17T14:51:37.363Z main s.a.c.CreateAccountCommand     Creating account for user 'jbloggs2' 
ERROR 2021-08-17T14:51:37.364Z main s.a.c.CreateAccountCommand     Password does not meet the minimum length requirement of 1 characters 
WARN  2021-08-17T14:51:37.384Z main s.e.l.i.StroomEventLoggingServiceImpl Problem getting current user 
java.lang.NullPointerException: Cannot invoke "stroom.security.api.UserIdentity.getId()" because the return value of "stroom.security.api.SecurityContext.getUserIdentity()" is null
	at stroom.event.logging.impl.StroomEventLoggingServiceImpl.getUser(StroomEventLoggingServiceImpl.java:304)
	at stroom.event.logging.impl.StroomEventLoggingServiceImpl.createEvent(StroomEventLoggingServiceImpl.java:171)
	at event.logging.EventLoggingService.log(EventLoggingService.java:110)
	at stroom.app.commands.CreateAccountCommand.logEvent(CreateAccountCommand.java:174)
	at stroom.app.commands.CreateAccountCommand.runCommand(CreateAccountCommand.java:140)
	at stroom.app.commands.AbstractStroomAccountConfiguredCommand.run(AbstractStroomAccountConfiguredCommand.java:65)
	at stroom.app.commands.AbstractStroomAccountConfiguredCommand.run(AbstractStroomAccountConfiguredCommand.java:26)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at stroom.app.App.main(App.java:135)
WARN  2021-08-17T14:51:37.385Z main s.e.l.i.StroomEventLoggingServiceImpl Problem getting current user 
stroom.security.impl.exception.AuthenticationException: No user is currently logged in
	at stroom.security.impl.SecurityContextImpl.isProcessingUser(SecurityContextImpl.java:85)
	at stroom.event.logging.impl.StroomEventLoggingServiceImpl.getRunAsUser(StroomEventLoggingServiceImpl.java:282)
	at stroom.event.logging.impl.StroomEventLoggingServiceImpl.createEvent(StroomEventLoggingServiceImpl.java:172)
	at event.logging.EventLoggingService.log(EventLoggingService.java:110)
	at stroom.app.commands.CreateAccountCommand.logEvent(CreateAccountCommand.java:174)
	at stroom.app.commands.CreateAccountCommand.runCommand(CreateAccountCommand.java:140)
	at stroom.app.commands.AbstractStroomAccountConfiguredCommand.run(AbstractStroomAccountConfiguredCommand.java:65)
	at stroom.app.commands.AbstractStroomAccountConfiguredCommand.run(AbstractStroomAccountConfiguredCommand.java:26)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at stroom.app.App.main(App.java:135)
ERROR 2021-08-17T14:51:37.387Z main s.a.c.AbstractStroomAccountConfiguredCommand Error running DB migrations 
stroom.security.impl.exception.AuthenticationException: No user is currently logged in
	at stroom.security.impl.SecurityContextImpl.hasAppPermission(SecurityContextImpl.java:122)
	at stroom.security.impl.SecurityContextImpl.isAdmin(SecurityContextImpl.java:75)
	at stroom.security.impl.SecurityContextImpl.checkAdmin(SecurityContextImpl.java:516)
	at stroom.security.impl.SecurityContextImpl.secureResult(SecurityContextImpl.java:444)
	at stroom.activity.impl.CurrentActivityImpl.getActivity(CurrentActivityImpl.java:47)
	at stroom.event.logging.impl.StroomEventLoggingServiceImpl.createEvent(StroomEventLoggingServiceImpl.java:177)
	at event.logging.EventLoggingService.log(EventLoggingService.java:110)
	at stroom.app.commands.CreateAccountCommand.logEvent(CreateAccountCommand.java:174)
	at stroom.app.commands.CreateAccountCommand.runCommand(CreateAccountCommand.java:140)
	at stroom.app.commands.AbstractStroomAccountConfiguredCommand.run(AbstractStroomAccountConfiguredCommand.java:65)
	at stroom.app.commands.AbstractStroomAccountConfiguredCommand.run(AbstractStroomAccountConfiguredCommand.java:26)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at stroom.app.App.main(App.java:135)

Process finished with exit code 1
```
I think password has been made optional in master, so need to back port some master changes.  Also need the logging to cope with no logged in user.

**Comment by at055612** [comment]
Also need to fix the error handling in AbstractStroomAccountConfiguredCommand so runCommand is in its own try/catch block with a sensible error msg, or let the sub classes handle it.

**Comment by at055612** [comment]
Fixed in > beta.166
