### ISSUE TITLE
FileSystemClean is throwing exceptions 

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2430]
I appreciate that FSC is deprecated, but I need to complete one more run to bridge the gap between v6 FSC last run and Data Delete new run.

The volume being reported *is* the Data Volume for this stack.

```
ERROR  [2021-09-15T06:26:24.681Z] [File System Clean# #1 - Cleaning: /stroom/volumes/xxxxxxxxx - File system clean - File system clean - File system clean - File system clean] stroom.db.util.JooqUtil -  Cursor returned more than one result 
org.jooq.exception.TooManyRowsException: Cursor returned more than one result
	at org.jooq_3.12.3.MYSQL.debug(Unknown Source)
	at org.jooq.impl.Tools.fetchOne(Tools.java:2087)
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:653)
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:589)
	at org.jooq.impl.AbstractResultQuery.fetchOptional(AbstractResultQuery.java:779)
	at org.jooq.impl.SelectImpl.fetchOptional(SelectImpl.java:3008)
	at stroom.data.store.impl.fs.db.FsTypePathDaoImpl.lambda$getName$5(FsTypePathDaoImpl.java:99)
	at stroom.db.util.JooqUtil.contextResult(JooqUtil.java:112)
	at stroom.data.store.impl.fs.db.FsTypePathDaoImpl.getName(FsTypePathDaoImpl.java:95)
	at stroom.data.store.impl.fs.db.FsTypePathDaoImpl.loadName(FsTypePathDaoImpl.java:68)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$2(LocalLoadingCache.java:140)
	at com.github.benmanes.caffeine.cache.LocalCache.lambda$statsAware$0(LocalCache.java:139)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2379)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2377)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2360)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:54)
	at stroom.cache.impl.CacheManagerImpl$1.get(CacheManagerImpl.java:99)
	at stroom.data.store.impl.fs.db.FsTypePathDaoImpl.getType(FsTypePathDaoImpl.java:53)
	at stroom.data.store.impl.fs.FsDataStoreMaintenanceService.pathToStreamExpression(FsDataStoreMaintenanceService.java:251)
	at stroom.data.store.impl.fs.FsDataStoreMaintenanceService.findMatchingStreams(FsDataStoreMaintenanceService.java:221)
	at stroom.data.store.impl.fs.FsDataStoreMaintenanceService.buildStreamsKeyedByBaseName(FsDataStoreMaintenanceService.java:181)
	at stroom.data.store.impl.fs.FsDataStoreMaintenanceService.lambda$scanVolumePath$1(FsDataStoreMaintenanceService.java:161)
	at stroom.security.impl.SecurityContextImpl.secureResult(SecurityContextImpl.java:374)
	at stroom.data.store.impl.fs.FsDataStoreMaintenanceService.scanVolumePath(FsDataStoreMaintenanceService.java:112)
	at stroom.data.store.impl.fs.FsCleanSubTaskHandler.lambda$exec$3(FsCleanSubTaskHandler.java:83)
	at stroom.security.impl.SecurityContextImpl.secure(SecurityContextImpl.java:340)
	at stroom.data.store.impl.fs.FsCleanSubTaskHandler.exec(FsCleanSubTaskHandler.java:69)
	at stroom.data.store.impl.fs.FsCleanSubTaskHandler.lambda$exec$1(FsCleanSubTaskHandler.java:125)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$createFromConsumer$0(TaskContextFactoryImpl.java:95)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$3(TaskContextFactoryImpl.java:158)
	at stroom.util.logging.LocationAwareLambdaLogger.logDurationIfDebugEnabled(LocationAwareLambdaLogger.java:156)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$5(TaskContextFactoryImpl.java:158)
	at stroom.util.pipeline.scope.PipelineScopeRunnable.scopeResult(PipelineScopeRunnable.java:38)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$6(TaskContextFactoryImpl.java:155)
	at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:232)
	at jdk.internal.reflect.GeneratedMethodAccessor119.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
	at com.sun.proxy.$Proxy98.asUserResult(Unknown Source)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$11(TaskContextFactoryImpl.java:155)
	at stroom.data.store.impl.fs.FsCleanSubTaskHandler.lambda$exec$3(FsCleanSubTaskHandler.java:128)
	at stroom.security.impl.SecurityContextImpl.secure(SecurityContextImpl.java:340)
	at stroom.data.store.impl.fs.FsCleanSubTaskHandler.exec(FsCleanSubTaskHandler.java:69)
	at stroom.data.store.impl.fs.FsCleanSubTaskHandler.lambda$exec$1(FsCleanSubTaskHandler.java:125)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$createFromConsumer$0(TaskContextFactoryImpl.java:95)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$3(TaskContextFactoryImpl.java:158)
	at stroom.util.logging.LocationAwareLambdaLogger.logDurationIfDebugEnabled(LocationAwareLambdaLogger.java:156)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$5(TaskContextFactoryImpl.java:158)
	at stroom.util.pipeline.scope.PipelineScopeRunnable.scopeResult(PipelineScopeRunnable.java:38)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$6(TaskContextFactoryImpl.java:155)
	at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:232)
	at jdk.internal.reflect.GeneratedMethodAccessor119.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
	at com.sun.proxy.$Proxy98.asUserResult(Unknown Source)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$11(TaskContextFactoryImpl.java:155)
	at stroom.data.store.impl.fs.FsCleanSubTaskHandler.lambda$exec$3(FsCleanSubTaskHandler.java:128)
	at stroom.security.impl.SecurityContextImpl.secure(SecurityContextImpl.java:340)
	at stroom.data.store.impl.fs.FsCleanSubTaskHandler.exec(FsCleanSubTaskHandler.java:69)
	at stroom.data.store.impl.fs.FsCleanSubTaskHandler.lambda$exec$1(FsCleanSubTaskHandler.java:125)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$createFromConsumer$0(TaskContextFactoryImpl.java:95)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$3(TaskContextFactoryImpl.java:158)
	at stroom.util.logging.LocationAwareLambdaLogger.logDurationIfDebugEnabled(LocationAwareLambdaLogger.java:156)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$5(TaskContextFactoryImpl.java:158)
	at stroom.util.pipeline.scope.PipelineScopeRunnable.scopeResult(PipelineScopeRunnable.java:38)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$6(TaskContextFactoryImpl.java:155)
	at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:232)
	at jdk.internal.reflect.GeneratedMethodAccessor119.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
	at com.sun.proxy.$Proxy98.asUserResult(Unknown Source)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$11(TaskContextFactoryImpl.java:155)
	at stroom.data.store.impl.fs.FsCleanSubTaskHandler.lambda$exec$3(FsCleanSubTaskHandler.java:128)
	at stroom.security.impl.SecurityContextImpl.secure(SecurityContextImpl.java:340)
	at stroom.data.store.impl.fs.FsCleanSubTaskHandler.exec(FsCleanSubTaskHandler.java:69)
	at stroom.data.store.impl.fs.FsCleanSubTaskHandler.lambda$exec$1(FsCleanSubTaskHandler.java:125)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$createFromConsumer$0(TaskContextFactoryImpl.java:95)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$3(TaskContextFactoryImpl.java:158)
	at stroom.util.logging.LocationAwareLambdaLogger.logDurationIfDebugEnabled(LocationAwareLambdaLogger.java:156)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$5(TaskContextFactoryImpl.java:158)
	at stroom.util.pipeline.scope.PipelineScopeRunnable.scopeResult(PipelineScopeRunnable.java:38)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$6(TaskContextFactoryImpl.java:155)
	at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:232)
	at jdk.internal.reflect.GeneratedMethodAccessor119.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
	at com.sun.proxy.$Proxy98.asUserResult(Unknown Source)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$11(TaskContextFactoryImpl.java:155)
	at stroom.data.store.impl.fs.FsCleanSubTaskHandler.lambda$exec$3(FsCleanSubTaskHandler.java:128)
	at stroom.security.impl.SecurityContextImpl.secure(SecurityContextImpl.java:347)
	at stroom.data.store.impl.fs.FsCleanSubTaskHandler.exec(FsCleanSubTaskHandler.java:69)
	at stroom.data.store.impl.fs.FsCleanExecutor.cleanVolume(FsCleanExecutor.java:149)
	at stroom.data.store.impl.fs.FsCleanExecutor.lambda$clean$1(FsCleanExecutor.java:111)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$createFromConsumer$0(TaskContextFactoryImpl.java:95)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$3(TaskContextFactoryImpl.java:158)
	at stroom.util.logging.LocationAwareLambdaLogger.logDurationIfDebugEnabled(LocationAwareLambdaLogger.java:156)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$5(TaskContextFactoryImpl.java:158)
	at stroom.util.pipeline.scope.PipelineScopeRunnable.scopeResult(PipelineScopeRunnable.java:38)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$6(TaskContextFactoryImpl.java:155)
	at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:232)
	at jdk.internal.reflect.GeneratedMethodAccessor119.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
	at com.sun.proxy.$Proxy98.asUserResult(Unknown Source)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$11(TaskContextFactoryImpl.java:155)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
	at stroom.task.impl.ExecutorProviderImpl.lambda$get$0(ExecutorProviderImpl.java:61)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
WARN   [2021-09-15T06:26:24.681Z] [File System Clean# #1 - Cleaning: /stroom/volumes/xxxxxxxx - File system clean - File system clean - File system clean - File system clean] stroom.data.store.impl.fs.FsDataStoreMaintenanceService -  Not a valid repository path 
```

**Comment by stroomdev10** [comment]
It is likely that FSC deleted a bunch of files associated with Streams that exist in the DB
