### ISSUE TITLE
Exception logged during Search

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2439]
possibly when I disconnected my browser session...

```
ERROR  [2021-09-15T15:20:22.008Z] [Stroom P2 #13 - DB Search] stroom.bytebuffer.ByteBufferPoolImpl4 -  Thread interrupted waiting for a buffer from the pool 
java.lang.InterruptedException: null
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1627)
	at java.base/java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:420)
	at stroom.bytebuffer.ByteBufferPoolImpl4.getBuffer(ByteBufferPoolImpl4.java:194)
	at stroom.bytebuffer.ByteBufferPoolImpl4.lambda$getPooledByteBuffer$1(ByteBufferPoolImpl4.java:169)
	at stroom.bytebuffer.PooledByteBuffer.getByteBuffer(PooledByteBuffer.java:64)
	at stroom.lmdb.AbstractLmdbDb.get(AbstractLmdbDb.java:220)
	at stroom.pipeline.refdata.store.offheapstore.MapDefinitionUIDStore.get(MapDefinitionUIDStore.java:109)
	at stroom.pipeline.refdata.store.offheapstore.RefDataOffHeapStore.lambda$buildRefStoreEntry$53(RefDataOffHeapStore.java:1235)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
	at stroom.pipeline.refdata.store.offheapstore.RefDataOffHeapStore.buildRefStoreEntry(RefDataOffHeapStore.java:1232)
	at stroom.pipeline.refdata.store.offheapstore.RefDataOffHeapStore.lambda$buildKeyValueStoreEntryStream$41(RefDataOffHeapStore.java:1142)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.base/java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:720)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at stroom.pipeline.refdata.ReferenceDataServiceImpl.lambda$doSearch$38(ReferenceDataServiceImpl.java:502)
	at stroom.pipeline.refdata.store.offheapstore.RefDataOffHeapStore.lambda$consumeEntryStream$37(RefDataOffHeapStore.java:1097)
	at stroom.util.logging.LocationAwareLambdaLogger.logDurationIfDebugEnabled(LocationAwareLambdaLogger.java:156)
	at stroom.pipeline.refdata.store.offheapstore.RefDataOffHeapStore.lambda$consumeEntryStream$39(RefDataOffHeapStore.java:1095)
	at stroom.lmdb.LmdbEnv.getWithReadTxnUnderMaxReaderSemaphore(LmdbEnv.java:195)
	at stroom.lmdb.LmdbEnv.lambda$new$0(LmdbEnv.java:75)
	at stroom.lmdb.LmdbEnv.getWithReadTxn(LmdbEnv.java:173)
	at stroom.pipeline.refdata.store.offheapstore.RefDataOffHeapStore.consumeEntryStream(RefDataOffHeapStore.java:1067)
	at stroom.pipeline.refdata.ReferenceDataServiceImpl.doSearch(ReferenceDataServiceImpl.java:497)
	at stroom.pipeline.refdata.ReferenceDataServiceImpl.lambda$search$31(ReferenceDataServiceImpl.java:459)
	at stroom.util.logging.LocationAwareLambdaLogger.logDurationIfInfoEnabled(LocationAwareLambdaLogger.java:249)
	at stroom.util.logging.LambdaLogger.logDurationIfInfoEnabled(LambdaLogger.java:208)
	at stroom.pipeline.refdata.ReferenceDataServiceImpl.lambda$search$32(ReferenceDataServiceImpl.java:458)
	at stroom.pipeline.refdata.ReferenceDataServiceImpl.withPermissionCheck(ReferenceDataServiceImpl.java:436)
	at stroom.pipeline.refdata.ReferenceDataServiceImpl.search(ReferenceDataServiceImpl.java:458)
	at stroom.searchable.impl.SearchableStore.searchAsync(SearchableStore.java:88)
	at stroom.searchable.impl.SearchableStore.lambda$new$2(SearchableStore.java:69)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$createFromConsumer$0(TaskContextFactoryImpl.java:188)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$3(TaskContextFactoryImpl.java:259)
	at stroom.util.logging.LocationAwareLambdaLogger.logDurationIfDebugEnabled(LocationAwareLambdaLogger.java:156)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$5(TaskContextFactoryImpl.java:259)
	at stroom.util.pipeline.scope.PipelineScopeRunnable.scopeResult(PipelineScopeRunnable.java:38)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$6(TaskContextFactoryImpl.java:256)
	at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:232)
	at jdk.internal.reflect.GeneratedMethodAccessor98.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
	at com.sun.proxy.$Proxy98.asUserResult(Unknown Source)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$11(TaskContextFactoryImpl.java:256)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
	at stroom.task.impl.ExecutorProviderImpl.lambda$get$0(ExecutorProviderImpl.java:61)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by at055612** [comment]
Need to change the error() to debug() so we don't fill the logs with stack.

**Comment by at055612** [comment]
Fixed in >beta.145
