### ISSUE TITLE
Startup DB error in b.146

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2462]
Started 3 nodes concurrently, one node ERRORs with the following error, other nodes are OK.  

```
ERROR  [2021-09-23T09:55:46.677Z] [Data Processor# #23 - Data Processor] stroom.db.util.JooqUtil -  HikariPool-1 - Connection is not available, request timed out after 30000ms.
java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:676)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:190)
        at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:155)
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
        at stroom.db.util.DataSourceProxy.getConnection(DataSourceProxy.java:20)
        at stroom.db.util.JooqUtil.contextResult(JooqUtil.java:110)
        at stroom.processor.impl.db.ProcessorFeedCache.get(ProcessorFeedCache.java:74)
        at stroom.processor.impl.db.ProcessorFeedCache.load(ProcessorFeedCache.java:51)
        at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$2(LocalLoadingCache.java:140)
        at com.github.benmanes.caffeine.cache.LocalCache.lambda$statsAware$0(LocalCache.java:139)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2379)
        at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2377)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2360)
        at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
        at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:54)
        at stroom.cache.impl.CacheManagerImpl$1.get(CacheManagerImpl.java:99)
        at stroom.processor.impl.db.ProcessorFeedCache.getOrCreate(ProcessorFeedCache.java:70)
        at stroom.processor.impl.db.ProcessorTaskDaoImpl.lambda$new$0(ProcessorTaskDaoImpl.java:170)
        at stroom.db.util.GenericDao.update(GenericDao.java:103)
        at stroom.processor.impl.db.ProcessorTaskDaoImpl.update(ProcessorTaskDaoImpl.java:879)
        at stroom.processor.impl.db.ProcessorTaskDaoImpl.lambda$changeTaskStatus$28(ProcessorTaskDaoImpl.java:1085)
        at stroom.db.util.JooqUtil.lambda$transactionResult$2(JooqUtil.java:148)
        at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$0(DefaultDSLContext.java:536)
        at org.jooq.impl.Tools$12$1.block(Tools.java:4843)
        at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3137)
        at org.jooq.impl.Tools$12.get(Tools.java:4840)
        at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:588)
        at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:505)
        at stroom.db.util.JooqUtil.lambda$transactionResult$3(JooqUtil.java:148)
        at stroom.db.util.JooqUtil.contextResult(JooqUtil.java:112)
        at stroom.db.util.JooqUtil.transactionResult(JooqUtil.java:147)
        at stroom.processor.impl.db.ProcessorTaskDaoImpl.changeTaskStatus(ProcessorTaskDaoImpl.java:1074)
        at stroom.processor.impl.DataProcessorTaskHandler.exec(DataProcessorTaskHandler.java:133)
        at stroom.processor.impl.DataProcessorTaskHandler.lambda$exec$0(DataProcessorTaskHandler.java:85)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$3(TaskContextFactoryImpl.java:259)
        at stroom.util.logging.LocationAwareLambdaLogger.logDurationIfDebugEnabled(LocationAwareLambdaLogger.java:156)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$5(TaskContextFactoryImpl.java:259)
        at stroom.util.pipeline.scope.PipelineScopeRunnable.scopeResult(PipelineScopeRunnable.java:38)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$6(TaskContextFactoryImpl.java:256)
        at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:232)
        at jdk.internal.reflect.GeneratedMethodAccessor121.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
        at com.sun.proxy.$Proxy98.asUserResult(Unknown Source)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$11(TaskContextFactoryImpl.java:256)
        at stroom.processor.impl.DataProcessorTaskHandler.lambda$exec$1(DataProcessorTaskHandler.java:85)
        at stroom.security.impl.SecurityContextImpl.asProcessingUserResult(SecurityContextImpl.java:268)
        at stroom.processor.impl.DataProcessorTaskHandler.exec(DataProcessorTaskHandler.java:80)
        at stroom.processor.impl.DataProcessorTaskFactory.lambda$fetch$0(DataProcessorTaskFactory.java:83)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
        at stroom.task.impl.ExecutorProviderImpl.lambda$get$0(ExecutorProviderImpl.java:61)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)

```

**Comment by stroomdev10** [comment]
Thread Dump extract for 66

```
"Data Processor# #28 - Data Processor" #207 prio=1 os_prio=0 cpu=14.97ms elapsed=1281.28s tid=0x00007f7210292910 nid=0x1816 waiting for monitor entry  [0x00007f632e3e0000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at java.util.concurrent.ConcurrentHashMap.compute(java.base@15.0.2/ConcurrentHashMap.java:1932)
        - waiting to lock <0x00000000911cb1a0> (a java.util.concurrent.ConcurrentHashMap$ReservationNode)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2377)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2360)
        at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
        at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:54)
        at stroom.cache.impl.CacheManagerImpl$1.get(CacheManagerImpl.java:99)
        at stroom.processor.impl.db.ProcessorFeedCache.getOrCreate(ProcessorFeedCache.java:70)
        at stroom.processor.impl.db.ProcessorTaskDaoImpl.lambda$new$0(ProcessorTaskDaoImpl.java:170)
        at stroom.processor.impl.db.ProcessorTaskDaoImpl$$Lambda$955/0x000000080147c6e8.apply(Unknown Source)
        at stroom.db.util.GenericDao.update(GenericDao.java:103)
        at stroom.processor.impl.db.ProcessorTaskDaoImpl.update(ProcessorTaskDaoImpl.java:879)
        at stroom.processor.impl.db.ProcessorTaskDaoImpl.lambda$changeTaskStatus$28(ProcessorTaskDaoImpl.java:1085)
        at stroom.processor.impl.db.ProcessorTaskDaoImpl$$Lambda$1422/0x000000080160afb0.apply(Unknown Source)
        at stroom.db.util.JooqUtil.lambda$transactionResult$2(JooqUtil.java:148)
        at stroom.db.util.JooqUtil$$Lambda$870/0x00000008013b4870.run(Unknown Source)
        at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$0(DefaultDSLContext.java:536)
        at org.jooq.impl.DefaultDSLContext$$Lambda$871/0x00000008013b4cb0.get(Unknown Source)
        at org.jooq.impl.Tools$12$1.block(Tools.java:4843)
        at java.util.concurrent.ForkJoinPool.managedBlock(java.base@15.0.2/ForkJoinPool.java:3137)
        at org.jooq.impl.Tools$12.get(Tools.java:4840)
        at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:588)
        at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:505)
        at stroom.db.util.JooqUtil.lambda$transactionResult$3(JooqUtil.java:148)
        at stroom.db.util.JooqUtil$$Lambda$869/0x00000008013b3fb0.apply(Unknown Source)
        at stroom.db.util.JooqUtil.contextResult(JooqUtil.java:112)
        at stroom.db.util.JooqUtil.transactionResult(JooqUtil.java:147)
        at stroom.processor.impl.db.ProcessorTaskDaoImpl.changeTaskStatus(ProcessorTaskDaoImpl.java:1074)
        at stroom.processor.impl.DataProcessorTaskHandler.exec(DataProcessorTaskHandler.java:133)
        at stroom.processor.impl.DataProcessorTaskHandler.lambda$exec$0(DataProcessorTaskHandler.java:85)
        at stroom.processor.impl.DataProcessorTaskHandler$$Lambda$1283/0x00000008015d3108.apply(Unknown Source)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$3(TaskContextFactoryImpl.java:259)
        at stroom.task.impl.TaskContextFactoryImpl$$Lambda$1006/0x0000000801492bb0.get(Unknown Source)
        at stroom.util.logging.LocationAwareLambdaLogger.logDurationIfDebugEnabled(LocationAwareLambdaLogger.java:156)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$5(TaskContextFactoryImpl.java:259)
        at stroom.task.impl.TaskContextFactoryImpl$$Lambda$1002/0x0000000801491c58.get(Unknown Source)
        at stroom.util.pipeline.scope.PipelineScopeRunnable.scopeResult(PipelineScopeRunnable.java:38)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$6(TaskContextFactoryImpl.java:256)
        at stroom.task.impl.TaskContextFactoryImpl$$Lambda$1001/0x0000000801491a30.get(Unknown Source)
        at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:232)
        at jdk.internal.reflect.GeneratedMethodAccessor97.invoke(Unknown Source)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@15.0.2/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@15.0.2/Method.java:564)
        at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
        at com.sun.proxy.$Proxy98.asUserResult(Unknown Source)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$11(TaskContextFactoryImpl.java:256)
        at stroom.task.impl.TaskContextFactoryImpl$$Lambda$992/0x0000000801485860.get(Unknown Source)
        at stroom.processor.impl.DataProcessorTaskHandler.lambda$exec$1(DataProcessorTaskHandler.java:85)
        at stroom.processor.impl.DataProcessorTaskHandler$$Lambda$1275/0x00000008015d1fc8.get(Unknown Source)
        at stroom.security.impl.SecurityContextImpl.asProcessingUserResult(SecurityContextImpl.java:268)
        at stroom.processor.impl.DataProcessorTaskHandler.exec(DataProcessorTaskHandler.java:80)
        at stroom.processor.impl.DataProcessorTaskFactory.lambda$fetch$0(DataProcessorTaskFactory.java:83)
        at stroom.processor.impl.DataProcessorTaskFactory$$Lambda$1269/0x00000008015ce0e8.run(Unknown Source)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(java.base@15.0.2/CompletableFuture.java:1800)
        at stroom.task.impl.ExecutorProviderImpl.lambda$get$0(ExecutorProviderImpl.java:61)
        at stroom.task.impl.ExecutorProviderImpl$$Lambda$994/0x0000000801486540.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@15.0.2/ThreadPoolExecutor.java:1130)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@15.0.2/ThreadPoolExecutor.java:630)
        at java.lang.Thread.run(java.base@15.0.2/Thread.java:832)

```
