### ISSUE TITLE
Error decoding binary data

### ISSUE THREAD

**Issue by stroomdev00** [gchq/stroom#2467]
When trying to view a non-ASCII input stream (for example if gzipped data has been sent in error), both `Data Preview` and `View Source` show `## null ##`.

Stack trace to follow.

**Comment by stroomdev10** [comment]
```
DEBUG  [2021-09-23T13:10:55.451Z] [dw-719 - POST /api/data/v1/fetch - Data Fetcher] stroom.data.store.impl.DataFetcher -  null
java.lang.IllegalArgumentException: newLimit > capacity: (11 > 10)
        at java.base/java.nio.Buffer.createLimitException(Buffer.java:391)
        at java.base/java.nio.Buffer.limit(Buffer.java:365)
        at java.base/java.nio.ByteBuffer.limit(ByteBuffer.java:1394)
        at stroom.pipeline.reader.ByteStreamDecoder.decodeNextChar(ByteStreamDecoder.java:124)
        at stroom.data.store.impl.CharReader.read(CharReader.java:136)
        at stroom.data.store.impl.DataFetcher.extractDataRange(DataFetcher.java:650)
        at stroom.data.store.impl.DataFetcher.getNonSegmentedData(DataFetcher.java:583)
        at stroom.data.store.impl.DataFetcher.createDataResult(DataFetcher.java:438)
        at stroom.data.store.impl.DataFetcher.lambda$getData$3(DataFetcher.java:287)
        at stroom.security.impl.SecurityContextImpl.useAsReadResult(SecurityContextImpl.java:304)
        at stroom.data.store.impl.DataFetcher.lambda$getData$4(DataFetcher.java:207)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$3(TaskContextFactoryImpl.java:259)
        at stroom.util.logging.LocationAwareLambdaLogger.logDurationIfDebugEnabled(LocationAwareLambdaLogger.java:156)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$5(TaskContextFactoryImpl.java:259)
        at stroom.util.pipeline.scope.PipelineScopeRunnable.scopeResult(PipelineScopeRunnable.java:38)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$6(TaskContextFactoryImpl.java:256)
        at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:232)
        at jdk.internal.reflect.GeneratedMethodAccessor151.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
        at com.sun.proxy.$Proxy98.asUserResult(Unknown Source)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$11(TaskContextFactoryImpl.java:256)
        at stroom.data.store.impl.DataFetcher.getData(DataFetcher.java:324)
        at stroom.data.store.impl.DataServiceImpl.lambda$fetch$4(DataServiceImpl.java:270)
        at stroom.security.impl.SecurityContextImpl.secureResult(SecurityContextImpl.java:381)
        at stroom.data.store.impl.DataServiceImpl.fetch(DataServiceImpl.java:269)
        at stroom.data.store.impl.DataResourceImpl.lambda$fetch$2(DataResourceImpl.java:145)
        at event.logging.impl.DefaultEventLoggingService.loggedResult(DefaultEventLoggingService.java:120)
        at event.logging.EventLoggingService.loggedResult(EventLoggingService.java:406)
        at stroom.data.store.impl.DataResourceImpl.fetch(DataResourceImpl.java:135)
        at jdk.internal.reflect.GeneratedMethodAccessor512.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
        at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
        at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45)
        at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)

```

**Comment by at055612** [comment]
Relates to #1953
