### ISSUE TITLE
LMDB Reference Data - Purge Error

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2483]
```
ERROR  [2021-10-02T11:02:32.324Z] [Stroom P2 #241 - Ref Data Off-heap Store Purge] stroom.pipeline.refdata.store.offheapstore.RefDataOffHeapStore -    Failed purge of refStreamDefinition with stream 523051 (0 maps deleted, 0 values deleted, 0 values de-referenced): Error deleting key Cap: 10, pos: 0, lim: 10, rem: 10, val [>7A CF 87 11 BF C2 82 38 00 00< ], asStr [zχ^Q�<82>8^@^@]
java.lang.RuntimeException: Error deleting key Cap: 10, pos: 0, lim: 10, rem: 10, val [>7A CF 87 11 BF C2 82 38 00 00< ], asStr [zχ^Q�<82>8^@^@]
        at stroom.lmdb.AbstractLmdbDb.delete(AbstractLmdbDb.java:695)
        at stroom.pipeline.refdata.store.offheapstore.ValueStore.lambda$deReferenceOrDeleteValue$2(ValueStore.java:138)
        at stroom.pipeline.refdata.store.offheapstore.databases.ValueStoreMetaDb.deReferenceOrDeleteValue(ValueStoreMetaDb.java:189)
        at stroom.pipeline.refdata.store.offheapstore.ValueStore.deReferenceOrDeleteValue(ValueStore.java:134)
        at stroom.pipeline.refdata.store.offheapstore.RefDataOffHeapStore.deReferenceOrDeleteValue(RefDataOffHeapStore.java:999)
        at stroom.pipeline.refdata.store.offheapstore.RefDataOffHeapStore.lambda$purgeMapData$31(RefDataOffHeapStore.java:974)
        at stroom.pipeline.refdata.store.offheapstore.databases.KeyValueStoreDb.deleteMapEntries(KeyValueStoreDb.java:113)
        at stroom.pipeline.refdata.store.offheapstore.RefDataOffHeapStore.purgeMapData(RefDataOffHeapStore.java:971)
        at stroom.pipeline.refdata.store.offheapstore.RefDataOffHeapStore.purgeRefStreamData(RefDataOffHeapStore.java:941)
        at stroom.pipeline.refdata.store.offheapstore.RefDataOffHeapStore.purgeRefStreamDef(RefDataOffHeapStore.java:845)
        at stroom.pipeline.refdata.store.offheapstore.RefDataOffHeapStore.lambda$purgeRefStreamIfEligible$24(RefDataOffHeapStore.java:773)
        at stroom.lmdb.LmdbEnv.lambda$doWithWriteTxn$2(LmdbEnv.java:115)
        at stroom.lmdb.LmdbEnv.getWithWriteTxn(LmdbEnv.java:140)
        at stroom.lmdb.LmdbEnv.doWithWriteTxn(LmdbEnv.java:114)
        at stroom.pipeline.refdata.store.offheapstore.RefDataOffHeapStore.lambda$purgeRefStreamIfEligible$26(RefDataOffHeapStore.java:759)
        at stroom.pipeline.refdata.store.AbstractRefDataStore.doWithRefStreamDefinitionLock(AbstractRefDataStore.java:133)
        at stroom.pipeline.refdata.store.offheapstore.RefDataOffHeapStore.purgeRefStreamIfEligible(RefDataOffHeapStore.java:751)
        at stroom.pipeline.refdata.store.offheapstore.RefDataOffHeapStore.purgeOldData(RefDataOffHeapStore.java:636)
        at stroom.pipeline.refdata.store.offheapstore.RefDataOffHeapStore.purgeOldData(RefDataOffHeapStore.java:458)
        at stroom.pipeline.refdata.store.RefDataStoreFactory.purgeOldData(RefDataStoreFactory.java:51)
        at stroom.pipeline.refdata.store.RefDataStoreModule$RefDataPurge.lambda$new$0(RefDataStoreModule.java:104)
        at stroom.util.RunnableWrapper.run(RunnableWrapper.java:19)
        at stroom.job.impl.ScheduledJobFunction.run(ScheduledJobFunction.java:27)
        at stroom.job.impl.ScheduledTaskExecutor$JobNodeTrackedFunction.run(ScheduledTaskExecutor.java:270)
        at stroom.job.impl.ScheduledTaskExecutor.lambda$execute$2(ScheduledTaskExecutor.java:149)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$createFromConsumer$0(TaskContextFactoryImpl.java:188)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$3(TaskContextFactoryImpl.java:259)
        at stroom.util.logging.LocationAwareLambdaLogger.logDurationIfDebugEnabled(LocationAwareLambdaLogger.java:156)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$5(TaskContextFactoryImpl.java:259)
        at stroom.util.pipeline.scope.PipelineScopeRunnable.scopeResult(PipelineScopeRunnable.java:38)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$6(TaskContextFactoryImpl.java:256)
        at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:232)
        at jdk.internal.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
        at com.sun.proxy.$Proxy98.asUserResult(Unknown Source)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$11(TaskContextFactoryImpl.java:256)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
        at stroom.task.impl.ExecutorProviderImpl.lambda$get$0(ExecutorProviderImpl.java:61)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: org.lmdbjava.Txn$TxFullException: Transaction has too many dirty pages (-30788)
        at org.lmdbjava.ResultCodeMapper.checkRc(ResultCodeMapper.java:102)
        at org.lmdbjava.Dbi.delete(Dbi.java:173)
        at org.lmdbjava.Dbi.delete(Dbi.java:136)
        at stroom.lmdb.AbstractLmdbDb.delete(AbstractLmdbDb.java:689)
        ... 42 common frames omitted
```

**Comment by stroomdev10** [comment]
```[
    {
        "createTime": "2021-10-04T06:11:34.130Z",
        "effectiveTime": "2021-09-30T00:00:00.000Z",
        "lastAccessedTime": "2021-10-04T06:00:00.000Z",
        "maps": {
            "REFDATASRC2": {
                "keyValueCount": 0,
                "rangeValueCount": 1000000
            }
        },
        "processingState": "COMPLETE",
        "refStreamDefinition": {
            "partIndex": 0,
            "pipelineDocRef": {
                "type": "Pipeline",
                "uuid": "da1c7351-086f-493b-866a-b42dbe990700"
            },
            "pipelineVersion": "8a0af81c-1eb1-419f-b395-e28b3672d0de",
            "streamId": 523038
        }
    },
    {
        "createTime": "2021-10-04T06:11:34.097Z",
        "effectiveTime": "2021-10-02T00:00:00.000Z",
        "lastAccessedTime": "2021-10-04T06:00:00.000Z",
        "maps": {
            "REFDATASRC1": {
                "keyValueCount": 2,
                "rangeValueCount": 0
            },
            "REFDATASRC1_XML": {
                "keyValueCount": 2,
                "rangeValueCount": 0
            }
        },
        "processingState": "COMPLETE",
        "refStreamDefinition": {
            "partIndex": 0,
            "pipelineDocRef": {
                "type": "Pipeline",
                "uuid": "da1c7351-086f-493b-866a-b42dbe990700"
            },
            "pipelineVersion": "8a0af81c-1eb1-419f-b395-e28b3672d0de",
            "streamId": 526245
        }
    },
    {
        "createTime": "2021-10-04T06:12:09.911Z",
        "effectiveTime": "2021-10-02T00:00:00.000Z",
        "lastAccessedTime": "2021-10-04T06:00:00.000Z",
        "maps": {
            "REFDATASRC1": {
                "keyValueCount": 2,
                "rangeValueCount": 0
            },
            "REFDATASRC1_XML": {
                "keyValueCount": 2,
                "rangeValueCount": 0
            }
        },
        "processingState": "COMPLETE",
        "refStreamDefinition": {
            "partIndex": 0,
            "pipelineDocRef": {
                "type": "Pipeline",
                "uuid": "da1c7351-086f-493b-866a-b42dbe990700"
            },
            "pipelineVersion": "8a0af81c-1eb1-419f-b395-e28b3672d0de",
            "streamId": 526246
        }
    },
    {
        "createTime": "2021-10-01T09:00:52.987Z",
        "effectiveTime": "2021-09-27T00:00:00.000Z",
        "lastAccessedTime": "2021-10-04T06:00:00.000Z",
        "maps": {
            "REFDATASRC3_1": {
                "keyValueCount": 1000000,
                "rangeValueCount": 0
            },
            "REFDATASRC3_2": {
                "keyValueCount": 1000000,
                "rangeValueCount": 0
            },
            "REFDATASRC3_3": {
                "keyValueCount": 1000000,
                "rangeValueCount": 0
            }
        },
        "processingState": "PURGE_FAILED",
        "refStreamDefinition": {
            "partIndex": 0,
            "pipelineDocRef": {
                "type": "Pipeline",
                "uuid": "da1c7351-086f-493b-866a-b42dbe990700"
            },
            "pipelineVersion": "8a0af81c-1eb1-419f-b395-e28b3672d0de",
            "streamId": 523051
        }
    }
]
```
