### ISSUE TITLE
UI node died during Search b.152

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2541]
OOM?  b.152 seems to reliably fail when querying dashboards which worked fine under previous versions

[hs_err_pid12022.log](https://github.com/gchq/stroom/files/7458888/hs_err_pid12022.log)

**Comment by stroomdev10** [comment]
Possibly related?  this is happening after the crash


ERROR  [2021-11-02T08:43:47.156Z] [dw-35 - POST /api/sqlstatistics/v2/search] stroom.query.common.v2.FlatResultCreator -  Error creating result for resultRequest vis-QL85W
java.lang.RuntimeException: Error performing work in read transaction: Environment has already been closed
        at stroom.lmdb.LmdbEnv.getWithReadTxnUnderMaxReaderSemaphore(LmdbEnv.java:247)
        at stroom.lmdb.LmdbEnv.getWithReadTxnUnderReadWriteLock(LmdbEnv.java:270)
        at stroom.lmdb.LmdbEnv.lambda$new$0(LmdbEnv.java:80)
        at stroom.lmdb.LmdbEnv.doWithReadTxn(LmdbEnv.java:222)
        at stroom.query.common.v2.LmdbDataStore.getChildren(LmdbDataStore.java:612)
        at stroom.query.common.v2.LmdbDataStore.lambda$get$7(LmdbDataStore.java:557)
        at stroom.query.common.v2.Metrics.measure(Metrics.java:24)
        at stroom.query.common.v2.LmdbDataStore.get(LmdbDataStore.java:553)
        at stroom.query.common.v2.LmdbDataStore.get(LmdbDataStore.java:542)
        at stroom.query.common.v2.FlatResultCreator$Mapper.map(FlatResultCreator.java:371)
        at stroom.query.common.v2.FlatResultCreator.create(FlatResultCreator.java:148)
        at stroom.query.common.v2.SearchResponseCreator.getResult(SearchResponseCreator.java:318)
        at stroom.query.common.v2.SearchResponseCreator.getResults(SearchResponseCreator.java:255)
        at stroom.query.common.v2.SearchResponseCreator.lambda$create$4(SearchResponseCreator.java:164)
        at stroom.query.util.BasicLambdaLogger.logDurationIfTraceEnabled(BasicLambdaLogger.java:143)
        at stroom.query.util.LambdaLogger.logDurationIfTraceEnabled(LambdaLogger.java:54)
        at stroom.query.common.v2.SearchResponseCreator.create(SearchResponseCreator.java:163)
        at stroom.statistics.impl.sql.search.StatisticsQueryServiceImpl.buildResponse(StatisticsQueryServiceImpl.java:111)
        at stroom.statistics.impl.sql.search.StatisticsQueryServiceImpl.lambda$search$1(StatisticsQueryServiceImpl.java:85)
        at stroom.security.impl.SecurityContextImpl.useAsReadResult(SecurityContextImpl.java:304)
        at stroom.statistics.impl.sql.search.StatisticsQueryServiceImpl.search(StatisticsQueryServiceImpl.java:65)
        at stroom.statistics.impl.sql.search.SqlStatisticsQueryResourceImpl.search(SqlStatisticsQueryResourceImpl.java:70)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
        at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
      at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
        at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45)
        at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at stroom.security.impl.SecurityFilter.continueAsUser(SecurityFilter.java:272)
        at stroom.security.impl.SecurityFilter.filter(SecurityFilter.java:156)
        at stroom.security.impl.SecurityFilter.doFilter(SecurityFilter.java:109)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at stroom.security.impl.ContentSecurityFilter.doFilter(ContentSecurityFilter.java:74)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at stroom.core.servlet.RejectPostFilter.doFilter(RejectPostFilter.java:56)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at stroom.core.servlet.HttpServletRequestFilter.doFilter(HttpServletRequestFilter.java:56)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at stroom.core.servlet.CacheControlFilter.doFilter(CacheControlFilter.java:100)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:319)
        at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:273)
        at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
        at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:313)
        at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:716)
        at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:67)
        at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: org.lmdbjava.Env$AlreadyClosedException: Environment has already been closed
        at org.lmdbjava.Env.txn(Env.java:370)
        at org.lmdbjava.Env.txnRead(Env.java:381)
        at stroom.lmdb.LmdbEnv.getWithReadTxnUnderMaxReaderSemaphore(LmdbEnv.java:243)
        ... 112 common frames omitted

**Comment by at055612** [comment]
Fixed in beta.154
