### ISSUE TITLE
NPE when data volume is full to limit

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2644]
Initial ERROR looks correct, but followed by lots of NPEs, likely one per file part?

[20211213_DISK_FULL.txt](https://github.com/gchq/stroom/files/7702454/20211213_DISK_FULL.txt)

**Comment by at055612** [comment]
```
INFO   [2021-12-12T23:13:58.974Z] [File Set Processor #107 - File Set Processor] stroom.core.receive.DataStoreFileSetProcessor -  Processing set - xxxxxxxx-EVENTS(164)
WARN   [2021-12-12T23:13:58.982Z] [File Set Processor #107 - File Set Processor] stroom.data.store.impl.fs.FsVolumeService -  No ACTIVE volume found, all vols: 1, non-full vols: 0, non-full ACTIVE vols: 0
ERROR  [2021-12-12T23:13:58.982Z] [File Set Processor #107 - File Set Processor] stroom.core.receive.DataStoreFileSetProcessor -  Failed to get lock as no writable volumes. This may be because there are no active volumes configured or the active volumes (or the filesystem(s) they sit on) are full or near full.
stroom.data.store.api.DataException: Failed to get lock as no writable volumes. This may be because there are no active volumes configured or the active volumes (or the filesystem(s) they sit on) are full or near full.
        at stroom.data.store.impl.fs.FsStore.openTarget(FsStore.java:78)
        at stroom.receive.common.StreamTargetStroomStreamHandler.lambda$getTarget$6(StreamTargetStroomStreamHandler.java:351)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
        at stroom.receive.common.StreamTargetStroomStreamHandler.getTarget(StreamTargetStroomStreamHandler.java:339)
        at stroom.receive.common.StreamTargetStroomStreamHandler.checkLayer(StreamTargetStroomStreamHandler.java:196)
        at stroom.receive.common.StreamTargetStroomStreamHandler.handleEntryEnd(StreamTargetStroomStreamHandler.java:269)
        at stroom.proxy.repo.ProxyFileHandler.sendEntry(ProxyFileHandler.java:157)
        at stroom.proxy.repo.ProxyFileHandler.sendEntry(ProxyFileHandler.java:131)
        at stroom.proxy.repo.ProxyFileHandler.processFeedFile(ProxyFileHandler.java:68)
        at stroom.core.receive.DataStoreFileSetProcessor.process(DataStoreFileSetProcessor.java:139)
        at stroom.proxy.repo.RepositoryProcessor$ZipInfoConsumer.lambda$processFileSet$0(RepositoryProcessor.java:410)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$createFromConsumer$0(TaskContextFactoryImpl.java:188)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$3(TaskContextFactoryImpl.java:259)
        at stroom.util.logging.LocationAwareLambdaLogger.logDurationIfDebugEnabled(LocationAwareLambdaLogger.java:156)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$5(TaskContextFactoryImpl.java:259)
        at stroom.util.pipeline.scope.PipelineScopeRunnable.scopeResult(PipelineScopeRunnable.java:38)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$6(TaskContextFactoryImpl.java:256)
        at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:232)
        at jdk.internal.reflect.GeneratedMethodAccessor148.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
        at com.sun.proxy.$Proxy98.asUserResult(Unknown Source)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$11(TaskContextFactoryImpl.java:256)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
        at stroom.task.impl.ExecutorProviderImpl.lambda$get$0(ExecutorProviderImpl.java:61)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
ERROR  [2021-12-12T23:13:58.982Z] [File Set Processor #107 - File Set Processor] stroom.core.receive.DataStoreFileSetProcessor -  null
java.lang.NullPointerException: null
ERROR  [2021-12-12T23:13:58.982Z] [File Set Processor #107 - File Set Processor] stroom.core.receive.DataStoreFileSetProcessor -  null
java.lang.NullPointerException: null
ERROR  [2021-12-12T23:13:58.983Z] [File Set Processor #107 - File Set Processor] stroom.core.receive.DataStoreFileSetProcessor -  null
java.lang.NullPointerException: null
ERROR  [2021-12-12T23:13:58.983Z] [File Set Processor #107 - File Set Processor] stroom.core.receive.DataStoreFileSetProcessor -  null
java.lang.NullPointerException: null
ERROR  [2021-12-12T23:13:58.983Z] [File Set Processor #107 - File Set Processor] stroom.core.receive.DataStoreFileSetProcessor -  null
java.lang.NullPointerException: null
ERROR  [2021-12-12T23:13:58.983Z] [File Set Processor #107 - File Set Processor] stroom.core.receive.DataStoreFileSetProcessor -  null
java.lang.NullPointerException: null
ERROR  [2021-12-12T23:13:58.983Z] [File Set Processor #107 - File Set Processor] stroom.core.receive.DataStoreFileSetProcessor -  null
java.lang.NullPointerException: null
ERROR  [2021-12-12T23:13:58.983Z] [File Set Processor #107 - File Set Processor] stroom.core.receive.DataStoreFileSetProcessor -  null
java.lang.NullPointerException: null
ERROR  [2021-12-12T23:13:58.983Z] [File Set Processor #107 - File Set Processor] stroom.core.receive.DataStoreFileSetProcessor -  null
java.lang.NullPointerException: null
```

**Comment by at055612** [comment]
Changing the logic so it now breaks our of the fileset loop when an exception occurs such that you will now get a single error (with no stack) per feed processed.
```
ERROR 2021-12-21T16:09:07.186Z File Set Processor #57 s.c.r.DataStoreFileSetProcessor Error processing file 1 (/home/dev/.stroom/v7/node1a/proxy_repo/2021-12-21T15#23#14,568Z/001__parts/001__part001.zip) in fileset TEST_FEED (2 files), no further files in this set will be processed. - Failed to get lock as no writable volumes. This may be because there are no active volumes configured or the active volumes (or the filesystem(s) they sit on) are full or near full. (Enable DEBUG for stack trace) 
```

**Comment by at055612** [comment]
Fixed in >b.169
