### ISSUE TITLE
Multiple nodes trying to create the same user record on multi-node boot

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#2785]
Booting up a fresh 3 node cluster and see this error on one node.

The code that checks for the presence of the user before trying to create it ought to get a cluster lock, re-check then create to avoid these errors.  

```
ERROR 2022-02-21T15:05:31.541Z main stroom.db.util.JooqUtil        SQL [insert into `account` (`id`, `version`, `create_time_ms`, `create_user`, `update_time_ms`, `update_user`, `user_id`, `email`, `password_hash`, `first_name`, `last_name`, `comments`, `login_count`, `login_failures`, `last_login_ms`, `reactivated_ms`, `force_password_change`, `never_expires`, `enabled`, `inactive`, `locked`, `processing_account`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; Duplicate entry 'INTERNAL_PROCESSING_USER' for key 'account.user_id' 
org.jooq.exception.DataAccessException: SQL [insert into `account` (`id`, `version`, `create_time_ms`, `create_user`, `update_time_ms`, `update_user`, `user_id`, `email`, `password_hash`, `first_name`, `last_name`, `comments`, `login_count`, `login_failures`, `last_login_ms`, `reactivated_ms`, `force_password_change`, `never_expires`, `enabled`, `inactive`, `locked`, `processing_account`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]; Duplicate entry 'INTERNAL_PROCESSING_USER' for key 'account.user_id'
	at org.jooq_3.12.3.MYSQL.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2717)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:755)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:382)
	at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:206)
	at org.jooq.impl.TableRecordImpl$1.operate(TableRecordImpl.java:177)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:130)
	at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:173)
	at org.jooq.impl.UpdatableRecordImpl.store0(UpdatableRecordImpl.java:196)
	at org.jooq.impl.UpdatableRecordImpl.access$000(UpdatableRecordImpl.java:85)
	at org.jooq.impl.UpdatableRecordImpl$1.operate(UpdatableRecordImpl.java:136)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:130)
	at org.jooq.impl.UpdatableRecordImpl.store(UpdatableRecordImpl.java:132)
	at org.jooq.impl.UpdatableRecordImpl.store(UpdatableRecordImpl.java:124)
	at stroom.db.util.JooqUtil.create(JooqUtil.java:185)
	at stroom.security.identity.db.AccountDaoImpl.create(AccountDaoImpl.java:310)
	at stroom.security.identity.account.ProcessingUserIdentityProviderImpl.getAccount(ProcessingUserIdentityProviderImpl.java:99)
	at stroom.security.identity.account.ProcessingUserIdentityProviderImpl.get(ProcessingUserIdentityProviderImpl.java:58)
	at stroom.security.impl.SecurityContextImpl.asProcessingUser(SecurityContextImpl.java:284)
	at stroom.node.impl.NodeServiceImpl.<init>(NodeServiceImpl.java:90)
	at stroom.node.impl.NodeServiceImpl$$FastClassByGuice$$294296177.GUICE$TRAMPOLINE(<generated>)
	at stroom.node.impl.NodeServiceImpl$$FastClassByGuice$$294296177.apply(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at com.google.inject.internal.RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:206)
	at com.google.inject.internal.RealMultibinder$RealMultibinderProvider.doProvision(RealMultibinder.java:159)
	at com.google.inject.internal.InternalProviderInstanceBindingImpl$Factory.get(InternalProviderInstanceBindingImpl.java:113)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:40)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:60)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:50)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:146)
	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:101)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:72)
	at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:1061)
	at stroom.app.App.run(App.java:240)
	at stroom.app.App.run(App.java:86)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at stroom.app.App.main(App.java:139)
Caused by: java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'INTERNAL_PROCESSING_USER' for key 'account.user_id'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:117)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.executeUpdate(DefaultPreparedStatement.java:99)
	at org.jooq.impl.AbstractDMLQuery.executeReturningGeneratedKeysFetchAdditionalRows(AbstractDMLQuery.java:1096)
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:960)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:368)
	... 62 common frames omitted
```

**Comment by at055612** [comment]
Using a cluster lock is not possible due to circular dependencies.  The code already handles this error condition, it just needs to be changed to not log the error when it is expected.

**Comment by at055612** [comment]
Fixed in b.184
