### ISSUE TITLE
Seeing errors in the logs when booting up a brand new cluster

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#2789]
The errors are being logged due to all nodes trying to create the proc user and admin account and stroom_user records at the same time.  The exceptions are being swallowed so the app is fine but we should not see these as errors in the logs.

Also seeing errors relating to flyway migrations conflicting with other nodes, e.g. 
```
org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to lock table `stroom`.`statistics_schema_history`
---------------------------------------------------------
SQL State  : 40001
Error Code : 1213
Message    : Deadlock found when trying to get lock; try restarting transaction

	at org.flywaydb.core.internal.database.base.Table.lock(Table.java:107)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.doAddAppliedMigration(JdbcTableSchemaHistory.java:167)
	at org.flywaydb.core.internal.schemahistory.SchemaHistory.addAppliedMigration(SchemaHistory.java:170)
	at org.flywaydb.core.internal.schemahistory.SchemaHistory.addBaselineMarker(SchemaHistory.java:87)
	at org.flywaydb.core.internal.command.DbBaseline$1.call(DbBaseline.java:121)
	at org.flywaydb.core.internal.command.DbBaseline$1.call(DbBaseline.java:97)
	at org.flywaydb.core.internal.jdbc.TransactionTemplate.execute(TransactionTemplate.java:74)
	at org.flywaydb.core.internal.command.DbBaseline.baseline(DbBaseline.java:97)
	at org.flywaydb.core.Flyway.doBaseline(Flyway.java:1403)
	at org.flywaydb.core.Flyway.access$200(Flyway.java:85)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1381)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1356)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1711)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
	at stroom.db.util.AbstractFlyWayDbModule.performMigration(AbstractFlyWayDbModule.java:67)
	at stroom.db.util.AbstractDataSourceProviderModule.getConnectionProvider(AbstractDataSourceProviderModule.java:69)
	at stroom.db.util.AbstractDataSourceProviderModule$$FastClassByGuice$$13554542.GUICE$TRAMPOLINE(<generated>)
	at stroom.db.util.AbstractDataSourceProviderModule$$FastClassByGuice$$13554542.apply(<generated>)
```

It would be preferable if could enforce some sort of cluster wide lock before initialising all the db guice modules and thus ensure that only one node will be performing any migrations at a time.

**Comment by at055612** [comment]
Fixed in b.184
