### ISSUE TITLE
Processor Tasks Data Store Query hangs when > 1000000 rows returned

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2791]
When I query for 31d of Processor Tasks, the query is just hanging, stack trace attached.

Was previously working OK, current table size of processor_tasks is 1.5m rows.

Likely hitting row limit of `resultStoreConfig.valueQueueSize` but 
if it is, it isn't handling it very well.

[20220225ProcTask.txt](https://github.com/gchq/stroom/files/8140169/20220225ProcTask.txt)

**Comment by at055612** [comment]
Threads of note appear to be 
```
"Stroom P2 #7782" #84391 prio=2 os_prio=0 cpu=14568.02ms elapsed=6303.20s tid=0x00007efaec0077f0 nid=0xc7f1 waiting on condition  [0x00007f08139f7000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@15.0.2/Native Method)
	- parking to wait for  <0x000000040705fa88> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(java.base@15.0.2/LockSupport.java:341)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionNode.block(java.base@15.0.2/AbstractQueuedSynchronizer.java:505)
	at java.util.concurrent.ForkJoinPool.managedBlock(java.base@15.0.2/ForkJoinPool.java:3137)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@15.0.2/AbstractQueuedSynchronizer.java:1614)
	at java.util.concurrent.ArrayBlockingQueue.put(java.base@15.0.2/ArrayBlockingQueue.java:370)
	at stroom.util.concurrent.CompletableQueue.put(CompletableQueue.java:21)
	at stroom.query.common.v2.LmdbDataStore.doPut(LmdbDataStore.java:317)
	at stroom.query.common.v2.LmdbDataStore.put(LmdbDataStore.java:311)
	at stroom.query.common.v2.LmdbDataStore.add(LmdbDataStore.java:261)
```

and
```
"Stroom P2 #7920" #85335 prio=2 os_prio=0 cpu=36188.24ms elapsed=1815.87s tid=0x00007f084dc63c80 nid=0x10464 waiting on condition  [0x00007f086956c000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@15.0.2/Native Method)
	- parking to wait for  <0x0000000407060dc0> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.parkNanos(java.base@15.0.2/LockSupport.java:252)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@15.0.2/AbstractQueuedSynchronizer.java:1661)
	at java.util.concurrent.ArrayBlockingQueue.poll(java.base@15.0.2/ArrayBlockingQueue.java:435)
	at stroom.util.concurrent.CompletableQueue.poll(CompletableQueue.java:51)
	at stroom.query.common.v2.LmdbDataStore.lambda$transfer$8(LmdbDataStore.java:338)
	at stroom.query.common.v2.LmdbDataStore$$Lambda$1350/0x0000000801658ba0.run(Unknown Source)
	at stroom.util.logging.Metrics.measure(Metrics.java:38)
	at stroom.query.common.v2.LmdbDataStore.transfer(LmdbDataStore.java:326)
```

**Comment by stroomdev66** [comment]
Unable to reproduce
