### ISSUE TITLE
SQL exception on startup: `stroom.config_update_tracker`

### ISSUE THREAD

**Issue by p-kimberley** [gchq/stroom#2796]
Branch: `master`

On startup using an existing Stroom DB, the following error is thrown:

```
ERROR 2022-03-03T12:07:24.817Z main stroom.db.util.JooqUtil        SQL [select `config_update_tracker`.`update_time_ms` from `config_update_tracker` limit ?]; Table 'stroom.config_update_tracker' doesn't exist 
org.jooq.exception.DataAccessException: SQL [select `config_update_tracker`.`update_time_ms` from `config_update_tracker` limit ?]; Table 'stroom.config_update_tracker' doesn't exist
	at org.jooq_3.15.5.MYSQL.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2988)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:639)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:349)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:295)
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:316)
	at org.jooq.impl.SelectImpl.fetchLazyNonAutoClosing(SelectImpl.java:2866)
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:506)
	at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:434)
	at org.jooq.impl.ResultQueryTrait.fetchOptional(ResultQueryTrait.java:631)
	at stroom.config.global.impl.db.ConfigPropertyDaoImpl.lambda$getLatestConfigUpdateTimeMs$4(ConfigPropertyDaoImpl.java:111)
...
```

**Comment by at055612** [comment]
When it boots up does it say something like
```
Found required build version 'SNAPSHOT' in build_version table, no lock or DB migration required. 
```
in the logs?

Is this you running the HEAD of master in an IDE?

You can try shutting down, deleting the table `build_version`, then starting up again.

**Comment by at055612** [comment]
@p-kimberley provided the following during an upgrade of master to `7.1-beta.10` with master being about 2wks older than `7.1-beta.10`
```
********************************************************************************
Build version: 7.1-beta.10
Build date: 2022-03-18T18:21:05.428Z
********************************************************************************
INFO [2022-03-20T10:57:55.886Z] [main] stroom.db.util.DbUtil - Ensuring database connection to [jdbc:mysql://mysql-router.stroom-7.svc.cluster.local:6446/stroom?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8] with username [stroomuser] and driver class [com.mysql.cj.jdbc.Driver]
INFO [2022-03-20T10:57:56.200Z] [main] stroom.db.util.DbUtil - Successfully established connection to jdbc:mysql://mysql-router.stroom-7.svc.cluster.local:6446/stroom?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8 with username stroomuser
INFO [2022-03-20T10:57:56.589Z] [main] stroom.app.BootstrapUtil - Found old build version 'UNKNOWN_VERSION' in build_version table. Bootstrap lock and DB migration required.
INFO [2022-03-20T10:57:56.589Z] [main] stroom.app.BootstrapUtil - Waiting to acquire bootstrap lock on table: build_version, user: stroomuser, url: jdbc:mysql://mysql-router.stroom-7.svc.cluster.local:6446/stroom?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8
INFO [2022-03-20T10:57:56.592Z] [main] stroom.app.BootstrapUtil - Waited PT0.003026903S to acquire bootstrap lock
INFO [2022-03-20T10:57:56.594Z] [main] stroom.app.BootstrapUtil - Upgrading stroom from 'UNKNOWN_VERSION' to '7.1-beta.10' under lock
INFO [2022-03-20T10:57:56.594Z] [main] stroom.app.BootstrapUtil - Initialising database connections and configuration properties
INFO [2022-03-20T10:57:56.702Z] [main] stroom.db.util.DbUtil - Ensuring database connection hikari-stroom-legacy-db-migration to [jdbc:mysql://mysql-router.stroom-7.svc.cluster.local:6446/stroom?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8] with username [stroomuser] and driver class [com.mysql.cj.jdbc.Driver]
INFO [2022-03-20T10:57:56.724Z] [main] stroom.db.util.DbUtil - Successfully established connection to jdbc:mysql://mysql-router.stroom-7.svc.cluster.local:6446/stroom?serverTimezone=UTC&useUnicode=yes&characterEncoding=UTF-8 with username stroomuser
INFO [2022-03-20T10:57:56.779Z] [main] stroom.legacy.db.LegacyDbModule - Testing installed Stroom schema version
INFO [2022-03-20T10:57:56.805Z] [main] stroom.legacy.db.LegacyDbModule - This is an installation of v7.0 or greater. Legacy migrations won't be applied.
INFO [2022-03-20T10:57:56.808Z] [main] stroom.db.util.FlywayUtil -
-----------------------------------------------------------
Migrating database module: stroom-config
-----------------------------------------------------------
INFO [2022-03-20T10:57:56.817Z] [main] org.flywaydb.core.internal.license.VersionPrinter - Flyway Community Edition 7.5.3 by Redgate
INFO [2022-03-20T10:57:56.876Z] [main] org.flywaydb.core.internal.database.base.DatabaseType - Database: jdbc:mysql://mysql-router.stroom-7.svc.cluster.local:6446/stroom (MySQL 8.0)
INFO [2022-03-20T10:57:56.923Z] [main] stroom.db.util.FlywayUtil - No pending Flyway DB migration(s) for stroom-config in stroom/config/global/impl/db/migration
INFO [2022-03-20T10:57:56.926Z] [main] stroom.config.global.impl.ConfigMapper - Initialising application configuration
ERROR [2022-03-20T10:57:57.375Z] [main] stroom.db.util.JooqUtil - SQL [select `config_update_tracker`.`update_time_ms` from `config_update_tracker` limit ?]; Table 'stroom.config_update_tracker' doesn't exist
org.jooq.exception.DataAccessException: SQL [select `config_update_tracker`.`update_time_ms` from `config_update_tracker` limit ?]; Table 'stroom.config_update_tracker' doesn't exist
at org.jooq_3.16.4.MYSQL.debug(Unknown Source)
at org.jooq.impl.Tools.translate(Tools.java:3089)
at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:670)
at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:354)
at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:295)
at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:316)
at org.jooq.impl.SelectImpl.fetchLazyNonAutoClosing(SelectImpl.java:2867)
at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:506)
at org.jooq.impl.ResultQueryTrait.fetchOne(ResultQueryTrait.java:434)
at org.jooq.impl.ResultQueryTrait.fetchOptional(ResultQueryTrait.java:633)
at stroom.config.global.impl.db.ConfigPropertyDaoImpl.lambda$getLatestConfigUpdateTimeMs$4(ConfigPropertyDaoImpl.java:111)
at stroom.db.util.JooqUtil.contextResult(JooqUtil.java:138)
at stroom.config.global.impl.db.ConfigPropertyDaoImpl.getLatestConfigUpdateTimeMs(ConfigPropertyDaoImpl.java:107)
at stroom.config.global.impl.GlobalConfigBootstrapService.updateConfigFromDb(GlobalConfigBootstrapService.java:50)
at stroom.config.global.impl.GlobalConfigBootstrapService.<init>(GlobalConfigBootstrapService.java:38)
at stroom.config.global.impl.GlobalConfigBootstrapService$$FastClassByGuice$$13916062.GUICE$TRAMPOLINE(<generated>)
at stroom.config.global.impl.GlobalConfigBootstrapService$$FastClassByGuice$$13916062.apply(<generated>)
```
