### ISSUE TITLE
Exception thrown for Index shard.

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#2874]
[IndexShard.txt](https://github.com/gchq/stroom/files/8685921/IndexShard.txt)

**Comment by at055612** [comment]
admin```
this writer hit an unrecoverable error; cannot complete commit 
java.lang.IllegalStateException: this writer hit an unrecoverable error; cannot complete commit
	at org.apache.lucene.index.IndexWriter.finishCommit(IndexWriter.java:2985)
	at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:2970)
	at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:2930)
	at stroom.index.impl.IndexShardWriterImpl.flush(IndexShardWriterImpl.java:284)
	at stroom.index.impl.IndexShardWriterCacheImpl.lambda$flush$14(IndexShardWriterCacheImpl.java:396)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$2(TaskContextFactoryImpl.java:255)
	at stroom.util.logging.LocationAwareLambdaLogger.logDurationIfDebugEnabled(LocationAwareLambdaLogger.java:156)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$4(TaskContextFactoryImpl.java:255)
	at stroom.util.pipeline.scope.PipelineScopeRunnable.scopeResult(PipelineScopeRunnable.java:38)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$5(TaskContextFactoryImpl.java:252)
	at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:232)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$9(TaskContextFactoryImpl.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.io.IOException: null: NIOFSIndexInput(path=&#34;/stroom/volumes/xxxxxxx_index/index/3e72379d-403f-4757-88d5-bfae4d724b55/2022-05/451/_47.fdt&#34;)
	at org.apache.lucene.store.NIOFSDirectory$NIOFSIndexInput.readInternal(NIOFSDirectory.java:189)
	at org.apache.lucene.store.BufferedIndexInput.readBytes(BufferedIndexInput.java:160)
	at org.apache.lucene.store.BufferedIndexInput.readBytes(BufferedIndexInput.java:116)
	at org.apache.lucene.store.BufferedChecksumIndexInput.readBytes(BufferedChecksumIndexInput.java:49)
	at org.apache.lucene.store.DataInput.readBytes(DataInput.java:87)
	at org.apache.lucene.store.DataInput.skipBytes(DataInput.java:350)
	at org.apache.lucene.store.ChecksumIndexInput.seek(ChecksumIndexInput.java:52)
	at org.apache.lucene.codecs.CodecUtil.checksumEntireFile(CodecUtil.java:450)
	at org.apache.lucene.codecs.compressing.CompressingStoredFieldsReader.checkIntegrity(CompressingStoredFieldsReader.java:669)
	at org.apache.lucene.codecs.compressing.CompressingStoredFieldsWriter.merge(CompressingStoredFieldsWriter.java:534)
	at org.apache.lucene.index.SegmentMerger.mergeFields(SegmentMerger.java:177)
	at org.apache.lucene.index.SegmentMerger.merge(SegmentMerger.java:83)
	at org.apache.lucene.index.IndexWriter.mergeMiddle(IndexWriter.java:4075)
	at org.apache.lucene.index.IndexWriter.merge(IndexWriter.java:3655)
	at org.apache.lucene.index.ConcurrentMergeScheduler.doMerge(ConcurrentMergeScheduler.java:588)
	at org.apache.lucene.index.ConcurrentMergeScheduler$MergeThread.run(ConcurrentMergeScheduler.java:626)
Caused by: java.nio.channels.ClosedChannelException: null
	at java.base/sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:156)
	at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:790)
	at org.apache.lucene.store.NIOFSDirectory$NIOFSIndexInput.readInternal(NIOFSDirectory.java:179)
	... 15 common frames omitted
```
