### ISSUE TITLE
Addition of `FilteredHealthCheckServlet` has broken DropWizard commands

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#2881]
e.g. ResetPasswordCommand

```
1) [Guice/MissingConstructor]: No injectable constructor for type Environment.

class Environment does not have a @Inject annotated constructor or a no-arg constructor.

Requested by:
1  : Environment.class(Environment.java:62)
     at FilteredHealthCheckServlet.<init>(FilteredHealthCheckServlet.java:58)
      \_ for 1st parameter
     at AdminServletBinder.bind(AdminServletBinder.java:21)

```

**Comment by at055612** [comment]
Fixed in > beta.203
