### ISSUE TITLE
Search errors not being shown in the UI

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#2883]
Errors in search, such as having invalid terms are being caught by the error receiver (which you can see in debug) but are not making it up to the UI so the user has no idea why the search is not returning anything.

```
DEBUG 2022-05-20T08:59:09.227Z Search Index Shard #26 s.q.c.v.ErrorConsumerImpl      Expected a numeric value for field "EventId" but was given string "1*" 
stroom.search.impl.SearchException: Expected a numeric value for field "EventId" but was given string "1*"
	at stroom.search.impl.SearchExpressionQueryBuilder.getLong(SearchExpressionQueryBuilder.java:810)
	at stroom.search.impl.SearchExpressionQueryBuilder.getTermQuery(SearchExpressionQueryBuilder.java:450)
	at stroom.search.impl.SearchExpressionQueryBuilder.getQuery(SearchExpressionQueryBuilder.java:103)
	at stroom.search.impl.SearchExpressionQueryBuilder.getQuery(SearchExpressionQueryBuilder.java:111)
	at stroom.search.impl.SearchExpressionQueryBuilder.buildQuery(SearchExpressionQueryBuilder.java:94)
	at stroom.search.impl.shard.IndexShardSearchFactory$1.getQuery(IndexShardSearchFactory.java:192)
	at stroom.search.impl.shard.IndexShardSearchFactory$1.lambda$getQuery$0(IndexShardSearchFactory.java:177)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at stroom.search.impl.shard.IndexShardSearchFactory$1.getQuery(IndexShardSearchFactory.java:175)
	at stroom.search.impl.shard.IndexShardSearchTaskHandler.searchShard(IndexShardSearchTaskHandler.java:158)
	at stroom.search.impl.shard.IndexShardSearchTaskHandler.searchShard(IndexShardSearchTaskHandler.java:111)
	at stroom.search.impl.shard.IndexShardSearchFactory.lambda$search$2(IndexShardSearchFactory.java:128)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$createFromConsumer$0(TaskContextFactoryImpl.java:177)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$2(TaskContextFactoryImpl.java:255)
	at stroom.util.logging.LocationAwareLambdaLogger.logDurationIfDebugEnabled(LocationAwareLambdaLogger.java:156)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$4(TaskContextFactoryImpl.java:255)
	at stroom.util.pipeline.scope.PipelineScopeRunnable.scopeResult(PipelineScopeRunnable.java:38)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$5(TaskContextFactoryImpl.java:252)
	at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:232)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$9(TaskContextFactoryImpl.java:252)
	at stroom.search.impl.shard.IndexShardSearchFactory.lambda$search$3(IndexShardSearchFactory.java:147)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1800)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832
```

**Comment by at055612** [comment]
Fixed in >beta.204
