### ISSUE TITLE
Lock wait timeout deleting from STAT_VAL_SRC

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#2947]
```
executeUpdate() - DELETE FROM SQL_STAT_VAL_SRC WHERE PROCESSING = 1 AND TIME_MS &lt; 253370764800000 AND VAL_TP = 1 
com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:123)
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
    at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1092)
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1040)
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1347)
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1025)
    at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
    at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
    at stroom.statistics.impl.sql.ConnectionUtil.executeUpdate(ConnectionUtil.java:57)
    at stroom.statistics.impl.sql.SQLStatisticAggregationTransactionHelper.doAggregateSQL_Update(SQLStatisticAggregationTransactionHelper.java:214)
    at stroom.statistics.impl.sql.SQLStatisticAggregationTransactionHelper.aggregateConfigStage1(SQLStatisticAggregationTransactionHelper.java:393)
    at stroom.statistics.impl.sql.SQLStatisticAggregationManager.aggregate(SQLStatisticAggregationManager.java:93)
    at stroom.statistics.impl.sql.SQLStatisticAggregationManager.lambda$aggregate$0(SQLStatisticAggregationManager.java:65)
    at stroom.cluster.lock.impl.db.ClusterLockServiceImpl.tryLock(ClusterLockServiceImpl.java:97)
    at stroom.statistics.impl.sql.SQLStatisticAggregationManager.aggregate(SQLStatisticAggregationManager.java:62)
    at stroom.util.RunnableWrapper.run(RunnableWrapper.java:19)
    at stroom.job.impl.ScheduledJobFunction.run(ScheduledJobFunction.java:27)
    at stroom.job.impl.ScheduledTaskExecutor$JobNodeTrackedFunction.run(ScheduledTaskExecutor.java:270)
    at stroom.job.impl.ScheduledTaskExecutor.lambda$execute$2(ScheduledTaskExecutor.java:149)
    at stroom.task.impl.TaskContextFactoryImpl.lambda$createFromConsumer$0(TaskContextFactoryImpl.java:194)
    at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$2(TaskContextFactoryImpl.java:275)
    at stroom.util.logging.LocationAwareLambdaLogger.logDurationIfDebugEnabled(LocationAwareLambdaLogger.java:156)
    at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$4(TaskContextFactoryImpl.java:275)
    at stroom.util.pipeline.scope.PipelineScopeRunnable.scopeResult(PipelineScopeRunnable.java:38)
    at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$5(TaskContextFactoryImpl.java:272)
    at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$7(TaskContextFactoryImpl.java:286)
    at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:237)
    at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$11(TaskContextFactoryImpl.java:282)
    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
    at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by at055612** [comment]
This appears to be fixed by the improvements to stats
