### ISSUE TITLE
Error logged when source data not found during processing

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#2948]
```
Unable to find meta data for id=xxxxxx with valid status &#xA;stroom.data.store.api.DataException: Unable to find meta data for id=xxxxxxxx with valid status
    at stroom.data.store.impl.fs.FsStore.openSource(FsStore.java:176)
    at stroom.data.store.impl.fs.FsStore.openSource(FsStore.java:148)
    at stroom.processor.impl.DataProcessorTaskHandler.exec(DataProcessorTaskHandler.java:102)
    at stroom.processor.impl.DataProcessorTaskHandler.lambda$exec$0(DataProcessorTaskHandler.java:85)
    at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$2(TaskContextFactoryImpl.java:275)
    at stroom.util.logging.LocationAwareLambdaLogger.logDurationIfDebugEnabled(LocationAwareLambdaLogger.java:156)
    at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$4(TaskContextFactoryImpl.java:275)
    at stroom.util.pipeline.scope.PipelineScopeRunnable.scopeResult(PipelineScopeRunnable.java:38)
    at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$5(TaskContextFactoryImpl.java:272)
    at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$7(TaskContextFactoryImpl.java:286)
    at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:237)
    at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$11(TaskContextFactoryImpl.java:282)
    at stroom.processor.impl.DataProcessorTaskHandler.lambda$exec$1(DataProcessorTaskHandler.java:85)
    at stroom.security.impl.SecurityContextImpl.asProcessingUserResult(SecurityContextImpl.java:273)
    at stroom.processor.impl.DataProcessorTaskHandler.exec(DataProcessorTaskHandler.java:80)
    at stroom.processor.impl.DataProcessorTaskFactory.lambda$fetch$0(DataProcessorTaskFactory.java:83)
    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
    at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by stroomdev66** [comment]
In some ways this is linked to gh-2905 as it is related to failure handling when source data is deleted
