### ISSUE TITLE
Dashboard searches sometimes leave dead extraction tasks

### ISSUE THREAD

**Issue by p-kimberley** [gchq/stroom#2969]
Build: `master` branch

# Problem
Sometimes, after conducting an Elasticsearch search, a dead/terminated task appears and lingers indefinitely in the `Server Tasks` view (see screenshot).

This issue has arisen in the past 30 days or so, since the last build.

![image](https://user-images.githubusercontent.com/17559369/177735140-a87c891a-95db-4d4f-a0ce-23e9eb7b6a66.png)

**Comment by p-kimberley** [comment]
After further testing, this issue arises when the user stops a search before it completes.

**Comment by p-kimberley** [comment]
An extract from the Java stack trace highlighting the stuck/dead task:
```
bash-5.1$ jstack 9 | grep Stream
"Extraction - Stream Map Creator #1" #125 prio=5 os_prio=0 cpu=765.25ms elapsed=252.07s tid=0x00007f06a4717030 nid=0xba waiting on condition  [0x00007efa13597000]
        at stroom.search.extraction.ExtractionDecorator.lambda$mapStreams$6(ExtractionDecorator.java:182)
        at stroom.search.extraction.StreamEventMap.take(StreamEventMap.java:104)
        at stroom.search.extraction.StreamEventMap.take(StreamEventMap.java:104)
        at stroom.search.extraction.StreamEventMap.take(StreamEventMap.java:104)
        at stroom.search.extraction.StreamEventMap.take(StreamEventMap.java:104)
        at stroom.search.extraction.StreamEventMap.take(StreamEventMap.java:104)
"Extraction - Stream Map Creator #2" #152 prio=5 os_prio=0 cpu=796.80ms elapsed=237.99s tid=0x00007efa168e76a0 nid=0xe5 waiting on condition  [0x00007efa13d25000]
        at stroom.search.extraction.ExtractionDecorator.lambda$mapStreams$6(ExtractionDecorator.java:182)
        at stroom.search.extraction.StreamEventMap.take(StreamEventMap.java:104)
        at stroom.search.extraction.StreamEventMap.take(StreamEventMap.java:104)
        at stroom.search.extraction.StreamEventMap.take(StreamEventMap.java:104)
        at stroom.search.extraction.StreamEventMap.take(StreamEventMap.java:104)
        at stroom.search.extraction.StreamEventMap.take(StreamEventMap.java:104)
```

**Comment by p-kimberley** [comment]
It seems that the recent merges from the `7.0` branch have cause an issue with early search task termination.

That is, when starting a dashboard search and quickly stopping it (say, within 1-2 seconds), the search task does NOT terminate and instead runs in the background until the underlying query is fully exhausted. This has been observed to result in OOM due to the resources consumed by this process.

This doesn't appear to be isolated to Elastic searches either - Lucene searches exhibit the same behaviour. For reference, the following thread interrupt handler is not triggered under these conditions:

https://github.com/gchq/stroom/blob/9cb6d6c0e9c862fe2f5f8295075d87e9d63102fc/stroom-search/stroom-search-impl/src/main/java/stroom/search/impl/ClusterSearchTaskHandler.java#L134
