### ISSUE TITLE
NPE Whilst stepping in saxon TinyBuilder

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#312]
java.lang.NullPointerException at net.sf.saxon.tree.tiny.TinyBuilder(TinyBuilder.java:175)
at net.sf.saxon.event.ReceivingContentHandler.endDocument(ReceivingContentHandler.java:243)
at stroom.pipeline.server.filter.TinyTreeBufferFilter.endDocument(TinyTreeBufferFilter.java:120)
at stroom.pipeline.server.filter.AbstractXMLFilter.endDocument(AbstractXMLFilter.java:168)
at stroom.pipeline.server.filter.XSLTFilter.endDocument(XSLYFilter.java:372)
at stroom.pipeline.server.filter.TinyTreeBufferFilter.endDocument(TinyTreeBufferFilter.java:131)
at stroom.pipeline.server.filter.AbstractXMLFilter.endDocument(AbstractXMLFilter.java:168)
at stroom.pipeline.server.filter.SAXRecordDetector.endDocument(SAXRecordDetector.java:58)
at stroom.pipeline.server.filter.AbstractXMLFilter.endDocument(AbstractXMLFilter.java:168)
at stroom.pipeline.server.filter.TinyTreeBufferFilter.endDocument(TinyTreeBuffer.......

**Comment by stroomdev10** [comment]
turns out that this occurs when calling stroom:meta in a processed stream

**Comment by stroomdev66** [comment]
Related to gh-311.
