### ISSUE TITLE
5.1 Alpha 2 - error on startup / upgrade from 5.1 Alpha 1

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#331]
2017-06-27T06:58:12.747Z INFO  [Thread-3] spring.PersistenceConfiguration (PersistenceConfiguration.java:84) - Testing installed Stroom schema version
2017-06-27T06:58:13.500Z INFO  [Thread-3] spring.PersistenceConfiguration (PersistenceConfiguration.java:170) - Detected current Stroom version is v5.1.0
2017-06-27T06:58:14.266Z INFO  [Thread-3] spring.StatisticsConfiguration (StatisticsConfiguration.java:82) - Testing installed statistics schema version
2017-06-27T06:58:14.749Z INFO  [Thread-3] spring.StatisticsConfiguration (StatisticsConfiguration.java:117) - Detected current statistics version is v4.0.60
2017-06-27T06:58:18.667Z ERROR [Thread-3] servlet.FrameworkServlet (FrameworkServlet.java:502) - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in stroom.spring.PersistenceConfiguration: Invocation of init method failed; nested exception is org.hibernate.HibernateException: Missing column: DASH_ID in stroom.QUERY
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1054)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:829)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:668)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:682)
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:553)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:494)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at stroom.util.upgrade.UpgradeDispatcherServlet.doInit(UpgradeDispatcherServlet.java:40)
	at stroom.util.upgrade.UpgradeDispatcherSingleton$1.run(UpgradeDispatcherSingleton.java:125)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.hibernate.HibernateException: Missing column: DASH_ID in stroom.QUERY
	at org.hibernate.mapping.Table.validateColumns(Table.java:365)
	at org.hibernate.cfg.Configuration.validateSchema(Configuration.java:1338)
	at org.hibernate.tool.hbm2ddl.SchemaValidator.validate(SchemaValidator.java:175)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:525)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1859)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:852)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:845)
	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.withTccl(ClassLoaderServiceImpl.java:398)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:844)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:343)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:318)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
	... 19 more
2017-06-27T06:58:18.677Z ERROR [Thread-3] upgrade.UpgradeDispatcherSingleton$1 (UpgradeDispatcherSingleton.java:143) - init() - Error during upgrade
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in stroom.spring.PersistenceConfiguration: Invocation of init method failed; nested exception is org.hibernate.HibernateException: Missing column: DASH_ID in stroom.QUERY
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1054)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:829)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:668)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:682)
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:553)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:494)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at stroom.util.upgrade.UpgradeDispatcherServlet.doInit(UpgradeDispatcherServlet.java:40)
	at stroom.util.upgrade.UpgradeDispatcherSingleton$1.run(UpgradeDispatcherSingleton.java:125)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.hibernate.HibernateException: Missing column: DASH_ID in stroom.QUERY
	at org.hibernate.mapping.Table.validateColumns(Table.java:365)
	at org.hibernate.cfg.Configuration.validateSchema(Configuration.java:1338)
	at org.hibernate.tool.hbm2ddl.SchemaValidator.validate(SchemaValidator.java:175)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:525)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1859)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:852)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:845)
	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.withTccl(ClassLoaderServiceImpl.java:398)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:844)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:343)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:318)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
	... 19 more

**Comment by stroomdev10** [comment]
I just updated the docker image and ran it, no setup etc...

**Comment by stroomdev10** [comment]
Not an issue, need to start a new DB
