### ISSUE TITLE
NPE importing content

### ISSUE THREAD

**Issue by gcdev373** [gchq/stroom#3361]
Exported from 7.0 and imported into 7.2.

Many exceptions that look like this:
```
java.lang.NullPointerException: Cannot invoke "String.length()" because "s" is null
        at java.base/java.io.StringReader.<init>(StringReader.java:51)
        at stroom.docstore.impl.JsonSerialiser2.read(JsonSerialiser2.java:38)
        at stroom.docstore.impl.JsonSerialiser2.read(JsonSerialiser2.java:33)
        at stroom.pipeline.PipelineSerialiser.read(PipelineSerialiser.java:36)
        at stroom.pipeline.PipelineSerialiser.read(PipelineSerialiser.java:20)
        at stroom.docstore.impl.StoreImpl.checkForUpdatedFields(StoreImpl.java:475)
        at stroom.docstore.impl.StoreImpl.importDocument(StoreImpl.java:357)
        at stroom.pipeline.PipelineStoreImpl.importDocument(PipelineStoreImpl.java:215)
 ```      
 With various `XStoreImpls`, not only `PipleineStoreImpl`.

**Comment by stroomdev66** [comment]
Can't replicate
