### ISSUE TITLE
Timeouts waiting to get a http connection

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#3449]
This is following the change to use dropwizard configured jersey clients

```
ERROR  [2023-05-12T06:53:12.836Z] [Stroom P2 #1] stroom.processor.impl.DataProcessorTaskFactory -  javax.ws.rs.ProcessingException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
java.lang.RuntimeException: javax.ws.rs.ProcessingException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
        at stroom.node.api.NodeCallUtil.handleExceptionsOnNodeCall(NodeCallUtil.java:58)
        at stroom.node.impl.NodeServiceImpl.remoteRestResult(NodeServiceImpl.java:198)
        at stroom.node.api.NodeService.remoteRestResult(NodeService.java:69)
        at stroom.processor.impl.ProcessorTaskResourceImpl.assignTasks(ProcessorTaskResourceImpl.java:125)
        at stroom.processor.impl.DataProcessorTaskFactory.fetch(DataProcessorTaskFactory.java:74)
        at stroom.job.impl.DistributedTaskFetcher.doFetch(DistributedTaskFetcher.java:209)
        at stroom.job.impl.DistributedTaskFetcher.lambda$fetch$0(DistributedTaskFetcher.java:131)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$2(TaskContextFactoryImpl.java:272)
        at stroom.util.logging.LocationAwareLambdaLogger.logDurationIfDebugEnabled(LocationAwareLambdaLogger.java:149)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$4(TaskContextFactoryImpl.java:272)
        at stroom.util.pipeline.scope.PipelineScopeRunnable.scopeResult(PipelineScopeRunnable.java:38)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$5(TaskContextFactoryImpl.java:269)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$7(TaskContextFactoryImpl.java:283)
        at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:261)
        at jdk.internal.reflect.GeneratedMethodAccessor163.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
        at jdk.proxy2/jdk.proxy2.$Proxy109.asUserResult(Unknown Source)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$11(TaskContextFactoryImpl.java:279)
        at stroom.job.impl.DistributedTaskFetcher.lambda$fetch$1(DistributedTaskFetcher.java:136)
        at stroom.security.impl.SecurityContextImpl.asUser(SecurityContextImpl.java:279)
        at stroom.security.impl.SecurityContextImpl.asProcessingUser(SecurityContextImpl.java:300)
        at stroom.job.impl.DistributedTaskFetcher.fetch(DistributedTaskFetcher.java:124)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.ws.rs.ProcessingException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
        at io.dropwizard.client.DropwizardApacheConnector.apply(DropwizardApacheConnector.java:105)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:297)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:662)
        at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:697)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:691)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
        at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:691)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:661)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:439)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:345)
        at stroom.processor.impl.ProcessorTaskResourceImpl.lambda$assignTasks$2(ProcessorTaskResourceImpl.java:136)
        at stroom.node.impl.NodeServiceImpl.remoteRestResult(NodeServiceImpl.java:188)
        ... 25 common frames omitted



ERROR  [2023-05-12T06:52:33.723Z] [Stroom P2 #1285] stroom.cluster.lock.impl.db.ClusterLockHandler -  Error connecting to master node 'xxxxxxxxxxxxxxxxxxxx' - javax.ws.rs.ProcessingException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
java.lang.RuntimeException: javax.ws.rs.ProcessingException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
        at stroom.node.api.NodeCallUtil.handleExceptionsOnNodeCall(NodeCallUtil.java:58)
        at stroom.cluster.lock.impl.db.ClusterLockResourceImpl.executeRemotely(ClusterLockResourceImpl.java:98)
        at stroom.cluster.lock.impl.db.ClusterLockResourceImpl.tryLock(ClusterLockResourceImpl.java:60)
        at stroom.cluster.lock.impl.db.ClusterLockHandler.lambda$tryLock$0(ClusterLockHandler.java:50)
        at stroom.cluster.lock.impl.db.ClusterLockHandler.lambda$call$3(ClusterLockHandler.java:65)
        at stroom.security.impl.SecurityContextImpl.secureResult(SecurityContextImpl.java:473)
        at stroom.cluster.lock.impl.db.ClusterLockHandler.call(ClusterLockHandler.java:65)
        at stroom.cluster.lock.impl.db.ClusterLockHandler.tryLock(ClusterLockHandler.java:50)
        at stroom.cluster.lock.impl.db.ClusterLockServiceImpl.tryLock(ClusterLockServiceImpl.java:81)
        at stroom.processor.impl.ProcessorTaskCreatorImpl.exec(ProcessorTaskCreatorImpl.java:144)
        at stroom.util.RunnableWrapper.run(RunnableWrapper.java:19)
        at stroom.job.impl.ScheduledJobFunction.run(ScheduledJobFunction.java:27)
        at stroom.job.impl.ScheduledTaskExecutor$JobNodeTrackedFunction.run(ScheduledTaskExecutor.java:270)
        at stroom.job.impl.ScheduledTaskExecutor.lambda$execute$2(ScheduledTaskExecutor.java:149)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$createFromConsumer$0(TaskContextFactoryImpl.java:195)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$2(TaskContextFactoryImpl.java:272)
        at stroom.util.logging.LocationAwareLambdaLogger.logDurationIfDebugEnabled(LocationAwareLambdaLogger.java:149)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$4(TaskContextFactoryImpl.java:272)
        at stroom.util.pipeline.scope.PipelineScopeRunnable.scopeResult(PipelineScopeRunnable.java:38)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$5(TaskContextFactoryImpl.java:269)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$7(TaskContextFactoryImpl.java:283)
        at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:261)
        at jdk.internal.reflect.GeneratedMethodAccessor163.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
        at jdk.proxy2/jdk.proxy2.$Proxy109.asUserResult(Unknown Source)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$11(TaskContextFactoryImpl.java:279)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: javax.ws.rs.ProcessingException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
        at io.dropwizard.client.DropwizardApacheConnector.apply(DropwizardApacheConnector.java:105)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:297)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:662)
        at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:697)
        at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:691)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
        at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:691)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:661)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:439)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.put(JerseyInvocation.java:328)
        at stroom.cluster.lock.impl.db.ClusterLockResourceImpl.executeRemotely(ClusterLockResourceImpl.java:92)
        ... 30 common frames omitted
Caused by: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:316)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:282)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at io.dropwizard.client.DropwizardApacheConnector.apply(DropwizardApacheConnector.java:87)
        ... 43 common frames omitted
		INFO   [2023-05-12T06:52:33.723Z] [Stroom P2 #1285] stroom.cluster.lock.impl.db.ClusterLockServiceImpl -  Skipped process as did not get lock ProcessorTaskCreator in 30s
WARN   [2023-05-12T06:52:45.920Z] [Stroom P2 #1298] stroom.cluster.task.impl.ClusterTaskTerminatorImpl -  javax.ws.rs.ProcessingException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
WARN   [2023-05-12T06:52:45.921Z] [Stroom P2 #1287] stroom.cluster.task.impl.ClusterTaskTerminatorImpl -  javax.ws.rs.ProcessingException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
WARN   [2023-05-12T06:52:45.921Z] [Stroom P2 #1295] stroom.cluster.task.impl.ClusterTaskTerminatorImpl -  javax.ws.rs.ProcessingException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
WARN   [2023-05-12T06:52:45.922Z] [Stroom P2 #1272] stroom.cluster.task.impl.ClusterTaskTerminatorImpl -  javax.ws.rs.ProcessingException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
WARN   [2023-05-12T06:52:45.924Z] [Stroom P2 #1244] stroom.cluster.impl.ClusterNodeManagerImpl -  discover() - unable to contact xxxxxxx - javax.ws.rs.ProcessingException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
WARN   [2023-05-12T06:52:45.924Z] [Stroom P2 #1288] stroom.cluster.impl.ClusterNodeManagerImpl -  discover() - unable to contact xxxxxxx - javax.ws.rs.ProcessingException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
INFO   [2023-05-12T06:52:45.924Z] [Stroom P2 #1288] stroom.cluster.impl.ClusterNodeManagerImpl -  Master node has changed from xxxxxxxx to xxxxxxxxxxxxxxxxxxxxxxxxxx
WARN   [2023-05-12T06:52:46.723Z] [Stroom P2 #1271] stroom.cluster.task.impl.ClusterTaskTerminatorImpl -  javax.ws.rs.ProcessingException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
WARN   [2023-05-12T06:52:46.723Z] [Stroom P2 #1289] stroom.cluster.task.impl.ClusterTaskTerminatorImpl -  javax.ws.rs.ProcessingException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
WARN   [2023-05-12T06:52:46.723Z] [Stroom P2 #1282] stroom.cluster.task.impl.ClusterTaskTerminatorImpl -  javax.ws.rs.ProcessingException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
WARN   [2023-05-12T06:52:46.723Z] [Stroom P2 #1294] stroom.cluster.task.impl.ClusterTaskTerminatorImpl -  javax.ws.rs.ProcessingException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
```

**Comment by at055612** [comment]
PR is a speculative fix for this problem.  It is possible that we are seeing these timouts because `Response` objects are not always being closed and thus the connections are left open and until GC'd, which delays their return to the pool.
