### ISSUE TITLE
LMDB error in Analytics

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3473]
```
ERROR  [2023-05-19T12:54:51.117Z] [Stroom P2 #12] stroom.query.common.v2.LmdbDataStore -  Error putting queueItem (Unexpected collision)
java.lang.RuntimeException: Error putting queueItem (Unexpected collision)
        at stroom.query.common.v2.LmdbDataStore.lambda$insert$20(LmdbDataStore.java:560)
        at stroom.util.logging.Metrics.measure(Metrics.java:33)
        at stroom.query.common.v2.LmdbDataStore.insert(LmdbDataStore.java:478)
        at stroom.query.common.v2.LmdbDataStore.lambda$transfer$10(LmdbDataStore.java:367)
        at stroom.util.logging.Metrics.measure(Metrics.java:33)
        at stroom.query.common.v2.LmdbDataStore.transfer(LmdbDataStore.java:350)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Unexpected collision
        at stroom.query.common.v2.LmdbDataStore.lambda$insert$20(LmdbDataStore.java:547)
        ... 8 common frames omitted
```

**Comment by stroomdev66** [comment]
Added debug
