### ISSUE TITLE
Java Deadlock 7.0

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3504]
Node appeared stalled, ran Thread Print, dump says Deadlock.

[2023-06-07_Deadlock_7_0.txt](https://github.com/gchq/stroom/files/11676596/2023-06-07_Deadlock_7_0.txt)

**Comment by stroomdev66** [comment]
```
	at java.util.concurrent.locks.LockSupport.park(java.base@15.0.2/LockSupport.java:211)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@15.0.2/AbstractQueuedSynchronizer.java:714)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@15.0.2/AbstractQueuedSynchronizer.java:937)
	at java.util.concurrent.locks.ReentrantLock$Sync.lock(java.base@15.0.2/ReentrantLock.java:153)
	at java.util.concurrent.locks.ReentrantLock.lock(java.base@15.0.2/ReentrantLock.java:322)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.clear(BoundedLocalCache.java:1889)
	at com.github.benmanes.caffeine.cache.LocalManualCache.invalidateAll(LocalManualCache.java:150)
	at stroom.cache.impl.CacheUtil.clear(CacheUtil.java:37)
	at stroom.cache.impl.AbstractStroomCache.clear(AbstractStroomCache.java:274)
	at stroom.pipeline.cache.AbstractPoolCache.clear(AbstractPoolCache.java:176)
	at stroom.pipeline.cache.SchemaPoolImpl$$Lambda$1908/0x00000008018a6ac8.onClear(Unknown Source)
	at stroom.pipeline.xmlschema.XmlSchemaCache.clear(XmlSchemaCache.java:68)
	at stroom.pipeline.xmlschema.XmlSchemaCache.clearIfOld(XmlSchemaCache.java:148)
	at stroom.pipeline.xmlschema.XmlSchemaCache.getSchemaSet(XmlSchemaCache.java:135)
	at stroom.pipeline.filter.SchemaFilter.validateSchemaLocations(SchemaFilter.java:396)
	at stroom.pipeline.filter.SchemaFilter.storeSchemaLocations(SchemaFilter.java:387)
	at stroom.pipeline.filter.SchemaFilter.startElement(SchemaFilter.java:287)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at stroom.pipeline.xml.converter.ds3.DS3ParserFactory.configure(DS3ParserFactory.java:81)
	at stroom.pipeline.cache.DSChooser.configure(DSChooser.java:62)
	at stroom.pipeline.cache.ParserFactoryPoolImpl.createValue(ParserFactoryPoolImpl.java:84)
	at stroom.pipeline.cache.ParserFactoryPoolImpl.createValue(ParserFactoryPoolImpl.java:44)
	at stroom.pipeline.cache.AbstractDocPool.lambda$internalCreateValue$0(AbstractDocPool.java:71)
	at stroom.pipeline.cache.AbstractDocPool$$Lambda$1760/0x000000080172faa0.get(Unknown Source)
	at stroom.security.impl.SecurityContextImpl.asProcessingUserResult(SecurityContextImpl.java:273)
	at stroom.pipeline.cache.AbstractDocPool.internalCreateValue(AbstractDocPool.java:71)
	at stroom.pipeline.cache.AbstractDocPool.internalCreateValue(AbstractDocPool.java:35)
	at stroom.pipeline.cache.AbstractPoolCache.create(AbstractPoolCache.java:63)
	at stroom.pipeline.cache.AbstractPoolCache$$Lambda$1709/0x000000080170d208.apply(Unknown Source)
	at stroom.cache.impl.LoadingStroomCacheImpl$$Lambda$576/0x0000000801280b30.load(Unknown Source)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.lambda$newMappingFunction$3(LocalLoadingCache.java:197)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache$$Lambda$578/0x0000000801295a00.apply(Unknown Source)
	at com.github.benmanes.caffeine.cache.LocalCache.lambda$statsAware$2(LocalCache.java:162)
	at com.github.benmanes.caffeine.cache.LocalCache$$Lambda$981/0x00000008014c8490.apply(Unknown Source)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$13(BoundedLocalCache.java:2478)
	- locked <0x00000002150b86a0> (a com.github.benmanes.caffeine.cache.PSAMS)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$$Lambda$982/0x00000008014c8eb8.apply(Unknown Source)
	at java.util.concurrent.ConcurrentHashMap.compute(java.base@15.0.2/ConcurrentHashMap.java:1940)
	- locked <0x0000000215142068> (a java.util.concurrent.ConcurrentHashMap$Node)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2449)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2432)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:107)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:57)
	```

**Comment by stroomdev66** [comment]
Caused by
```
	at stroom.pipeline.xmlschema.XmlSchemaCache.clear(XmlSchemaCache.java:68)
	at stroom.pipeline.xmlschema.XmlSchemaCache.clearIfOld(XmlSchemaCache.java:148)
	at stroom.pipeline.xmlschema.XmlSchemaCache.getSchemaSet(XmlSchemaCache.java:135)
	```
	
happening  within create

**Comment by stroomdev66** [comment]
It seems that clear really ought to be called by an external job every 10 minutes and not during the create process. Also `clear` in `AbstractPoolCache` should probably clear the `keyMap` at the same time.
