### ISSUE TITLE
7.2 Error in pipeline after restart

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3592]
```
[PipelineStreamProcessor] FATAL: Unable to provision, see the following errors:  1) [Guice/ErrorInjectingConstructor]: RuntimeException: A cache called 'Reference Data - Meta ID to Ref Store Cache' already exists   at DelegatingRefDataOffHeapStore.<init>(DelegatingRefDataOffHeapStore.java:105)   at DelegatingRefDataOffHeapStore.class(DelegatingRefDataOffHeapStore.java:65)   at RefDataStoreFactory.<init>(RefDataStoreFactory.java:36)       \_ for 1st parameter   at RefDataStoreFactory.class(RefDataStoreFactory.java:31)   at ReferenceDataServiceImpl.<init>(ReferenceDataServiceImpl.java:146)       \_ for 1st parameter   while locating ReferenceDataServiceImpl   while locating Searchable annotated with @internal.Element(setName=,uniqueId=421, type=MULTIBINDER, keyType=)   at SearchableProviderImpl.<init>(SearchableProviderImpl.java:21)       \_ for 1st parameter   at SearchableProviderImpl.class(SearchableProviderImpl.java:21)   while locating SearchableProviderImpl   at SearchableSearchProvider.<init>(SearchableSearchProvider.java:72)       \_ for 6th parameter   while locating SearchableSearchProvider   while locating DataSourceProvider annotated with @internal.Element(setName=,uniqueId=595, type=MULTIBINDER, keyType=)   at DataSourceProviderRegistry.<init>(DataSourceProviderRegistry.java:25)       \_ for 1st parameter   at DataSourceProviderRegistry.class(DataSourceProviderRegistry.java:20)   at DataSourceResolver.<init>(DataSourceResolver.java:22)       \_ for 2nd parameter   at AnalyticRuleSearchRequestHelper.<init>(AnalyticRuleSearchRequestHelper.java:18)       \_ for 1st parameter   at AlertManagerImpl.<init>(AlertManagerImpl.java:99)       \_ for 14th parameter   at AlertManagerImpl.class(AlertManagerImpl.java:63)   while locating AlertManagerImpl   at IndexingFilter.<init>(IndexingFilter.java:114)       \_ for 6th parameter   while locating IndexingFilter   while locating factory.Element annotated with @internal.Element(setName=,uniqueId=169, type=MAPBINDER, keyType=PipelineElementModule$ElementType)  Learn more:   https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR  1 error  ====================== Full classname legend: ====================== AlertManagerImpl:                  "stroom.analytics.impl.AlertManagerImpl" AnalyticRuleSearchRequestHelper:   "stroom.analytics.impl.AnalyticRuleSearchRequestHelper" DataSourceProvider:                "stroom.datasource.api.v2.DataSourceProvider" DataSourceProviderRegistry:        "stroom.query.common.v2.DataSourceProviderRegistry" DataSourceResolver:                "stroom.query.language.DataSourceResolver" DelegatingRefDataOffHeapStore:     "stroom.pipeline.refdata.store.offheapstore.DelegatingRefDataOffHeapStore" IndexingFilter:                    "stroom.index.impl.IndexingFilter" PipelineElementModule$ElementType: "stroom.pipeline.factory.PipelineElementModule$ElementType" RefDataStoreFactory:               "stroom.pipeline.refdata.store.RefDataStoreFactory" ReferenceDataServiceImpl:          "stroom.pipeline.refdata.ReferenceDataServiceImpl" Searchable:                        "stroom.searchable.api.Searchable" SearchableProviderImpl:            "stroom.searchable.impl.SearchableProviderImpl" SearchableSearchProvider:          "stroom.searchable.impl.SearchableSearchProvider" factory.Element:                   "stroom.pipeline.factory.Element" internal.Element:                  "com.google.inject.internal.Element" ======================== End of classname legend: ======================== 
```

**Comment by at055612** [comment]
Now verifies the dirs exist and are writable first.

```
1) [Guice/ErrorInjectingConstructor]: RuntimeException: Error writing test file in directory /home/dev/.stroom/v7/node1a/reference_data for property 'stroom.pipeline.referenceData.lmdb.localDir': AccessDeniedException /home/dev/.stroom/v7/node1a/reference_data/12683108099919228321.tmp
  at DelegatingRefDataOffHeapStore.<init>(DelegatingRefDataOffHeapStore.java:109)
```

**Comment by at055612** [comment]
Fixed in >7.2-beta.41
