### ISSUE TITLE
Proxy failing to forward files larger than JVM heap size

### ISSUE THREAD

**Issue by p-kimberley** [gchq/stroom#3612]
When an individual file is received, whose size exceeds the JVM max heap size, stroom-proxy 7.2 throws the following error repeatedly.

The file is not forwarded to the destination and remains in the repo directory.

This is due to the default behaviour of the HTTP client, which is to buffer the entire stream contents in memory. Workaround is to set `ForwardHttpPostConfig.forwardChunkSize` to a non-null value.

Recommend setting the default value of `forwardChunkSize` to a sensible value (e.g. `1048576` - 1MiB) to avoid nasty surprises for unsuspecting users.

```
Exception in thread "AggregateForwarder - forwardNext 7" java.lang.OutOfMemoryError: Java heap space
2023-07-17T17:10:27.874681669+10:00 	at java.base/java.util.Arrays.copyOf(Arrays.java:3537)
2023-07-17T17:10:27.874710717+10:00 	at java.base/java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:100)
2023-07-17T17:10:27.874713763+10:00 	at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:130)
2023-07-17T17:10:27.874715757+10:00 	at java.base/sun.net.www.http.PosterOutputStream.write(PosterOutputStream.java:78)
2023-07-17T17:10:27.874717871+10:00 	at java.base/java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:252)
2023-07-17T17:10:27.874720115+10:00 	at java.base/java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:210)
2023-07-17T17:10:27.874722430+10:00 	at java.base/java.util.zip.ZipOutputStream.write(ZipOutputStream.java:338)
2023-07-17T17:10:27.874732470+10:00 	at stroom.util.io.StreamUtil.streamToStream(StreamUtil.java:265)
2023-07-17T17:10:27.874755295+10:00 	at stroom.proxy.app.forwarder.ForwardStreamHandler.addEntry(ForwardStreamHandler.java:127)
2023-07-17T17:10:27.874757680+10:00 	at stroom.proxy.repo.SenderImpl.sendEntry(SenderImpl.java:153)
	at stroom.proxy.repo.SenderImpl.sendDataToHandler(SenderImpl.java:130)
2023-07-17T17:10:27.874761367+10:00 	at stroom.proxy.repo.AggregateForwarder.lambda$forward$2(AggregateForwarder.java:203)
2023-07-17T17:10:27.874778040+10:00 	at stroom.proxy.repo.AggregateForwarder$$Lambda$913/0x00000008012d5e68.accept(Unknown Source)
2023-07-17T17:10:27.874790785+10:00 	at stroom.proxy.app.forwarder.ForwardHttpPostHandlers.handle(ForwardHttpPostHandlers.java:51)
	at stroom.proxy.repo.AggregateForwarder.forward(AggregateForwarder.java:202)
2023-07-17T17:10:27.874796146+10:00 	at stroom.proxy.app.ProxyLifecycle$$Lambda$546/0x0000000801142450.accept(Unknown Source)
2023-07-17T17:10:27.874798120+10:00 	at stroom.proxy.repo.BatchExecutor.process(BatchExecutor.java:79)
2023-07-17T17:10:27.874800174+10:00 	at stroom.proxy.repo.BatchExecutor$$Lambda$632/0x0000000801181ba0.run(Unknown Source)
2023-07-17T17:10:27.874802078+10:00 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
```

**Comment by at055612** [comment]
Fixed in > 7.2-beta.43
