### ISSUE TITLE
Processing ERRORs b.57

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3733]
I did delete what i thought was an old Stroom User account of mine :)

373 and 66 have similar accounts on the env, might be a oidc merge artefact, or something else

```
RROR  [2023-09-08T07:49:11.720Z] [Create Processor Tasks #1] stroom.processor.impl.ProcessorTaskCreatorImpl -  No user name found for filter uuid: xxxxxx, owner uuid: 7xxxxx
java.lang.RuntimeException: No user name found for filter uuid: xxxxx, owner uuid: xxxxxxxx
        at stroom.processor.impl.ProcessorTaskCreatorImpl.lambda$getFilterOwnerIdentity$8(ProcessorTaskCreatorImpl.java:258)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at stroom.processor.impl.ProcessorTaskCreatorImpl.getFilterOwnerIdentity(ProcessorTaskCreatorImpl.java:257)
        at stroom.processor.impl.ProcessorTaskCreatorImpl.lambda$createNewTasks$3(ProcessorTaskCreatorImpl.java:194)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by at055612** [comment]
We think this is down to the env in question having users that were created with an earlier version of the OIDC enabled stroom, such that they did not have a UUIDy IDP subject ID.  The failing filters were created by these early users, one of which has now been deleted.
