### ISSUE TITLE
Rule has no owner

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3753]
```
RROR  [2023-09-19T13:18:21.337Z] [Stroom P2 #219] stroom.analytics.impl.StreamingAnalyticExecutor -  Error executing rule: xxxxxxxx v7.2-beta.55 (xxxxxxxx)
stroom.util.shared.DocumentOwnerException: Document has no owners
        at stroom.security.impl.SecurityContextImpl.getDocumentOwnerUuid(SecurityContextImpl.java:268)
        at stroom.analytics.impl.StreamingAnalyticExecutor.processAll(StreamingAnalyticExecutor.java:165)
        at stroom.analytics.impl.StreamingAnalyticExecutor.lambda$processUntilAllComplete$4(StreamingAnalyticExecutor.java:150)
        at stroom.security.impl.SecurityContextImpl.asUser(SecurityContextImpl.java:303)
        at stroom.security.impl.SecurityContextImpl.asProcessingUser(SecurityContextImpl.java:324)
        at stroom.analytics.impl.StreamingAnalyticExecutor.processUntilAllComplete(StreamingAnalyticExecutor.java:146)
        at stroom.analytics.impl.StreamingAnalyticExecutor.exec(StreamingAnalyticExecutor.java:135)
        at stroom.util.RunnableWrapper.run(RunnableWrapper.java:19)
        at stroom.job.impl.ScheduledJobFunction.run(ScheduledJobFunction.java:27)
        at stroom.job.impl.ScheduledTaskExecutor$JobNodeTrackedFunction.run(ScheduledTaskExecutor.java:272)
        at stroom.job.impl.ScheduledTaskExecutor.lambda$execute$2(ScheduledTaskExecutor.java:151)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$createFromConsumer$0(TaskContextFactoryImpl.java:193)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$2(TaskContextFactoryImpl.java:266)
        at stroom.util.logging.LocationAwareLambdaLogger.logDurationIfDebugEnabled(LocationAwareLambdaLogger.java:149)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$4(TaskContextFactoryImpl.java:266)
        at stroom.util.pipeline.scope.PipelineScopeRunnable.scopeResult(PipelineScopeRunnable.java:38)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$5(TaskContextFactoryImpl.java:263)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$7(TaskContextFactoryImpl.java:277)
        at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:285)
        at jdk.internal.reflect.GeneratedMethodAccessor157.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
        at jdk.proxy2/jdk.proxy2.$Proxy116.asUserResult(Unknown Source)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$11(TaskContextFactoryImpl.java:273)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by at055612** [comment]
Fixed by https://github.com/gchq/stroom/commit/1b6cdde1cb52c20bd9ade15220d7c19961c2d8ef
