### ISSUE TITLE
Stroom API Search failing

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#3849]
`Expected a standard data value for field "EventTime" but was given string "day()-1d"`

Expression is `EventTime between  day()-1d and day()`

**Comment by stroomdev10** [comment]
```
DEBUG  [2023-10-18T11:59:47.036Z] [Search Index Shard #44] stroom.query.common.v2.DateExpressionParser -  Cannot invoke "stroom.expression.api.DateTimeSettings.getReferenceTime()" because "dateTimeSettings" is null
java.lang.NullPointerException: Cannot invoke "stroom.expression.api.DateTimeSettings.getReferenceTime()" because "dateTimeSettings" is null
        at stroom.query.common.v2.DateExpressionParser.parse(DateExpressionParser.java:110)
        at stroom.query.common.v2.DateExpressionParser.getMs(DateExpressionParser.java:81)
        at stroom.search.impl.SearchExpressionQueryBuilder.getDates(SearchExpressionQueryBuilder.java:814)
        at stroom.search.impl.SearchExpressionQueryBuilder.getTermQuery(SearchExpressionQueryBuilder.java:483)
        at stroom.search.impl.SearchExpressionQueryBuilder.getQuery(SearchExpressionQueryBuilder.java:106)
        at stroom.search.impl.SearchExpressionQueryBuilder.getQuery(SearchExpressionQueryBuilder.java:113)
        at stroom.search.impl.SearchExpressionQueryBuilder.buildQuery(SearchExpressionQueryBuilder.java:91)
        at stroom.search.impl.shard.IndexShardSearchFactory$1.getQuery(IndexShardSearchFactory.java:193)
        at stroom.search.impl.shard.IndexShardSearchFactory$1.lambda$getQuery$0(IndexShardSearchFactory.java:179)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
        at stroom.search.impl.shard.IndexShardSearchFactory$1.getQuery(IndexShardSearchFactory.java:177)
        at stroom.search.impl.shard.IndexShardSearchTaskHandler.searchShard(IndexShardSearchTaskHandler.java:164)
        at stroom.search.impl.shard.IndexShardSearchTaskHandler.searchShard(IndexShardSearchTaskHandler.java:117)
        at stroom.search.impl.shard.IndexShardSearchFactory.lambda$search$1(IndexShardSearchFactory.java:136)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$createFromConsumer$0(TaskContextFactoryImpl.java:180)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$2(TaskContextFactoryImpl.java:252)
        at stroom.util.logging.LocationAwareLambdaLogger.logDurationIfDebugEnabled(LocationAwareLambdaLogger.java:307)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$4(TaskContextFactoryImpl.java:252)
        at stroom.util.pipeline.scope.PipelineScopeRunnable.scopeResult(PipelineScopeRunnable.java:38)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$5(TaskContextFactoryImpl.java:249)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$6(TaskContextFactoryImpl.java:261)
        at stroom.security.impl.SecurityContextImpl.useAsReadResult(SecurityContextImpl.java:389)
        at jdk.internal.reflect.GeneratedMethodAccessor164.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
        at jdk.proxy2/jdk.proxy2.$Proxy117.useAsReadResult(Unknown Source)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$7(TaskContextFactoryImpl.java:261)
        at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:321)
        at jdk.internal.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
        at jdk.proxy2/jdk.proxy2.$Proxy117.asUserResult(Unknown Source)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$11(TaskContextFactoryImpl.java:259)
        at stroom.search.impl.shard.IndexShardSearchFactory.lambda$search$2(IndexShardSearchFactory.java:151)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

```
