### ISSUE TITLE
Empty analytic rules causing errors

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#4010]
I have a rule that has no query and is not enabled but stroom is trying to set up a search for it.

![image](https://github.com/gchq/stroom/assets/22818309/f06b6a4a-06c9-4a66-95ad-4aabc8f3592b)

```
ERROR 2024-01-16T14:44:42.071Z dw-96 - POST /api/result-store/v1/find/node3a s.a.i.AnalyticRuleSearchRequestHelper Error creating search request for analytic rule - dsdd (848e6849-ce00-4528-8142-79eeb12b170d) 
stroom.query.language.token.TokenException: Empty query
	at stroom.query.language.token.Tokeniser.<init>(Tokeniser.java:29)
	at stroom.query.language.token.Tokeniser.parse(Tokeniser.java:96)
	at stroom.query.language.SearchRequestFactory$Builder.create(SearchRequestFactory.java:132)
	at stroom.query.language.SearchRequestFactory.create(SearchRequestFactory.java:79)
	at stroom.analytics.impl.AnalyticRuleSearchRequestHelper.create(AnalyticRuleSearchRequestHelper.java:48)
	at stroom.analytics.impl.AnalyticDataStores.lambda$find$5(AnalyticDataStores.java:308)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at stroom.analytics.impl.AnalyticDataStores.find(AnalyticDataStores.java:306)
	at stroom.query.impl.ResultStoreService.lambda$find$1(ResultStoreService.java:61)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at stroom.query.impl.ResultStoreService.lambda$find$2(ResultStoreService.java:59)
	at stroom.node.impl.NodeServiceImpl.remoteRestResult(NodeServiceImpl.java:177)
	at stroom.node.api.NodeService.remoteRestResult(NodeService.java:69)
	at stroom.query.impl.ResultStoreService.find(ResultStoreService.java:50)
	at stroom.query.impl.ResultStoreResourceImpl.find(ResultStoreResourceImpl.java:34)
```

**Comment by at055612** [comment]
Fixed in >7.2.20
