### ISSUE TITLE
params in a stats dashboard cause an error

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#413]
INFO   [14:59:28.589] [dw-530 - POST /api/sqlstatistics/v2/search] s.s.s.sql.SQLStatisticEventStore -  Searching statistics s
ERROR  [14:59:28.591] [dw-530 - POST /api/sqlstatistics/v2/search] i.d.j.errors.LoggingExceptionMapper -  Error handling a re
java.lang.UnsupportedOperationException: null                                                                                
        at java.util.AbstractMap.put(AbstractMap.java:209)                                                                   
        at stroom.statistics.server.sql.search.StatisticsQueryServiceImpl.buildResponse(StatisticsQueryServiceImpl.java:145) 
        at stroom.statistics.server.sql.search.StatisticsQueryServiceImpl.search(StatisticsQueryServiceImpl.java:108)        
        at stroom.resources.query.v2.SqlStatisticsQueryResource.search(SqlStatisticsQueryResource.java:84)                   
        at sun.reflect.GeneratedMethodAccessor506.invoke(Unknown Source)                                                     
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                             
        at java.lang.reflect.Method.invoke(Method.java:498)                                                                  
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocatio
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDi
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodD
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaReso
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMetho
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)              
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)               
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)               
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)

**Comment by stroomdev10** [comment]
Confirmed not an issue anymore
