### ISSUE TITLE
LMDB errors 7.3

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#4133]
INFO   [2024-02-28T08:45:24.687Z] [Data Processor# #43] stroom.pipeline.refdata.store.offheapstore.DelegatingRefDataOffHeapStore -  No legacy reference data store found in /xxxx/xxxxxxx/stroom/reference_data. No migration required.
DEBUG  [2024-02-28T08:45:24.697Z] [Data Processor# #43] stroom.pipeline.errorhandler.ErrorReceiverProxy -  Unable to provision, see the following errors:

1) [Guice/ErrorInjectingConstructor]: NoClassDefFoundError: Could not initialize class Library
  at DelegatingRefDataOffHeapStore.<init>(DelegatingRefDataOffHeapStore.java:111)
  at DelegatingRefDataOffHeapStore.class(DelegatingRefDataOffHeapStore.java:69)
  at RefDataStoreFactory.<init>(RefDataStoreFactory.java:35)
      \_ for 1st parameter
  at RefDataStoreFactory.class(RefDataStoreFactory.java:30)
  at RefDataStoreHolder.<init>(RefDataStoreHolder.java:54)
      \_ for 1st parameter
  at RefDataStoreHolder.class(RefDataStoreHolder.java:42)
  at ReferenceData.<init>(ReferenceData.java:94)
      \_ for 7th parameter
  at Lookup.<init>(Lookup.java:48)
      \_ for 1st parameter
  while locating Lookup

Learn more:
  https://github.com/google/guice/wiki/ERROR_INJECTING_CONSTRUCTOR

1 error

======================
Full classname legend:
======================
DelegatingRefDataOffHeapStore: "stroom.pipeline.refdata.store.offheapstore.DelegatingRefDataOffHeapStore"
Library:                       "org.lmdbjava.Library"
Lookup:                        "stroom.pipeline.xsltfunctions.Lookup"
RefDataStoreFactory:           "stroom.pipeline.refdata.store.RefDataStoreFactory"
RefDataStoreHolder:            "stroom.pipeline.refdata.RefDataStoreHolder"
ReferenceData:                 "stroom.pipeline.refdata.ReferenceData"
========================
End of classname legend:
========================

**Comment by at055612** [comment]
This would seem to be an issue with running lmdb 0.8.3 on centos 7.  0.8.3 runs fine on other OSs, e.g. arch, alpine.
Rolling back to 0.8.2 fixes the problem on centos 7.

Have raised this issue (and PR) against lmdb to uplift its jnr-ffi lib
https://github.com/lmdbjava/lmdbjava/issues/234

**Comment by cdprete** [comment]
> This would seem to be an issue with running lmdb 0.8.3 on centos 7. 0.8.3 runs fine on other OSs, e.g. arch, alpine. Rolling back to 0.8.2 fixes the problem on centos 7.
> 
> Have raised this issue (and PR) against lmdb to uplift its jnr-ffi lib [lmdbjava/lmdbjava#234](https://github.com/lmdbjava/lmdbjava/issues/234)
> 
> We need to wait for that PR to be merged and the following issues to be fixed/released before we can uplift lmdb [lmdbjava/lmdbjava#230](https://github.com/lmdbjava/lmdbjava/issues/230) [lmdbjava/lmdbjava#228](https://github.com/lmdbjava/lmdbjava/issues/228)

I've open https://github.com/lmdbjava/lmdbjava/pull/237 to fix https://github.com/lmdbjava/lmdbjava/issues/228 and https://github.com/lmdbjava/lmdbjava/issues/230 🤞
