### ISSUE TITLE
SQL Deadlock 7.3

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#4195]
```Error updating fields for: DocRef{type='Index', uuid='xxxxxxx', name='xxxxxxx'} SQL [insert into `index_field` (`fk_index_field_source_id`, `type`, `name`, `analyzer`, `indexed`, `stored`, `term_positions`, `case_sensitive`) values (?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?) on duplicate key update `index_field`.`fk_index_field_source_id` = ?]; Deadlock found when trying to get lock; try restarting transaction 
org.jooq.exception.DataAccessException: SQL [insert into `index_field` (`fk_index_field_source_id`, `type`, `name`, `analyzer`, `indexed`, `stored`, `term_positions`, `case_sensitive`) values (?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?) on duplicate key update `index_field`.`fk_index_field_source_id` = ?]; Deadlock found when trying to get lock; try restarting transaction
	at org.jooq_3.18.7.MYSQL.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:3470)
	at org.jooq.impl.Tools.translate(Tools.java:3458)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:802)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:360)
	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
	at stroom.index.impl.db.IndexFieldDaoImpl.lambda$addFields$2(IndexFieldDaoImpl.java:106)
	at stroom.db.util.JooqUtil.context(JooqUtil.java:118)
	at stroom.index.impl.db.IndexFieldDaoImpl.addFields(IndexFieldDaoImpl.java:84)
	at stroom.index.impl.IndexFieldServiceImpl.addFields(IndexFieldServiceImpl.java:47)
	at stroom.index.impl.DynamicIndexingFilter.flushFields(DynamicIndexingFilter.java:156)
	at stroom.index.impl.DynamicIndexingFilter.endProcessing(DynamicIndexingFilter.java:149)
	at stroom.pipeline.filter.XMLFilterFork.endProcessing(XMLFilterFork.java:89)
	at stroom.pipeline.filter.AbstractXMLFilter.endProcessing(AbstractXMLFilter.java:52)
	at stroom.pipeline.filter.AbstractXMLFilter.endProcessing(AbstractXMLFilter.java:52)
	at stroom.pipeline.filter.XsltFilter.endProcessing(XsltFilter.java:232)
	at stroom.pipeline.filter.AbstractXMLFilter.endProcessing(AbstractXMLFilter.java:52)
	at stroom.pipeline.filter.AbstractXMLFilter.endProcessing(AbstractXMLFilter.java:52)
	at stroom.pipeline.filter.SplitFilter.endProcessing(SplitFilter.java:146)
	at stroom.pipeline.filter.AbstractXMLFilter.endProcessing(AbstractXMLFilter.java:52)
	at stroom.pipeline.parser.AbstractParser.endProcessing(AbstractParser.java:136)
	at stroom.pipeline.reader.AbstractIOElement.endProcessing(AbstractIOElement.java:195)
	at stroom.pipeline.factory.PipelineImpl.internalEndProcessing(PipelineImpl.java:75)
	at stroom.pipeline.factory.PipelineImpl.endProcessing(PipelineImpl.java:55)
	at stroom.core.dataprocess.AbstractProcessorTaskExecutor.processNestedStreams(AbstractProcessorTaskExecutor.java:487)
	at stroom.core.dataprocess.AbstractProcessorTaskExecutor.process(AbstractProcessorTaskExecutor.java:339)
	at stroom.core.dataprocess.AbstractProcessorTaskExecutor.exec(AbstractProcessorTaskExecutor.java:238)
	at stroom.processor.impl.DataProcessorTaskHandler.exec(DataProcessorTaskHandler.java:164)
	at stroom.processor.impl.DataProcessorTaskHandler.lambda$exec$0(DataProcessorTaskHandler.java:92)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$2(TaskContextFactoryImpl.java:253)
	at stroom.util.logging.LocationAwareLambdaLogger.logDurationIfDebugEnabled(LocationAwareLambdaLogger.java:307)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$4(TaskContextFactoryImpl.java:253)
	at stroom.util.pipeline.scope.PipelineScopeRunnable.scopeResult(PipelineScopeRunnable.java:39)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$5(TaskContextFactoryImpl.java:250)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$6(TaskContextFactoryImpl.java:262)
	at stroom.security.impl.SecurityContextImpl.useAsReadResult(SecurityContextImpl.java:390)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
	at jdk.proxy2/jdk.proxy2.$Proxy120.useAsReadResult(Unknown Source)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$7(TaskContextFactoryImpl.java:262)
	at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:322)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
	at jdk.proxy2/jdk.proxy2.$Proxy120.asUserResult(Unknown Source)
	at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$11(TaskContextFactoryImpl.java:260)
	at stroom.processor.impl.DataProcessorTaskHandler.lambda$exec$1(DataProcessorTaskHandler.java:92)
	at stroom.security.impl.SecurityContextImpl.useAsReadResult(SecurityContextImpl.java:390)
	at stroom.processor.impl.DataProcessorTaskHandler.lambda$exec$2(DataProcessorTaskHandler.java:87)
	at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:322)
	at stroom.processor.impl.DataProcessorTaskHandler.exec(DataProcessorTaskHandler.java:87)
	at stroom.processor.impl.DataProcessorTaskFactory$RunnableFactoryImpl.lambda$create$0(DataProcessorTaskFactory.java:166)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:124)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:445)
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:1024)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:346)
	... 52 common frames omitted```

```
------------------------
LATEST DETECTED DEADLOCK
------------------------
2024-04-09 13:30:42 139696266131200
*** (1) TRANSACTION:
TRANSACTION 2720357778, ACTIVE 0 sec inserting
mysql tables in use 1, locked 1
LOCK WAIT 7 lock struct(s), heap size 1128, 5 row lock(s)
MySQL thread id 27355, OS thread handle 139696497997568, query id 479742158 host IP ref_aceuser update
insert into `index_field` (`fk_index_field_source_id`, `type`, `name`, `analyzer`, `indexed`, `stored`, `term_positions`, `case_sensitive`) values (5, 0, 'EventId', 'Keyword', 1, 1, 0, 0), (5, 7, 'FIELD1', 'Alpha numeric', 1, 0, 0, 0), (5, 7, 'FIELD1', 'Alpha numeric', 1, 0, 0, 0), (5, 7, 'FIELD1', 'Alpha numeric',
 1, 0, 0, 0), (5, 7, 'FIELD1', 'Alpha numeric', 1, 0, 0, 0), (5, 7, 'FIELD1', 'Alpha numeric', 1, 0, 0, 0), (5, 0, 'StreamId', 'Keyword', 1, 1, 0, 0), (5, 7, 'FIELD2', 'Alpha numeric', 1, 0, 0, 0), (5, 6, 'Time', 'Keyword', 1, 0, 0, 0), (5, 7, 'FIELD3', 'Alpha numeric', 1, 0, 0, 0), (5, 7, 'FIELD4', 'K
eyword', 1, 0, 0, 0), (5, 7, 'FIELD5', 'Alpha numeric', 1, 0, 0, 0), (5, 7, 'FIELD6', 'Alpha numeric', 1, 0, 0, 0) on duplicate key update `index_field`.`fk_index_field_source_id` = 5

*** (1) HOLDS THE LOCK(S):
RECORD LOCKS space id 86052 page no 4 n bits 240 index PRIMARY of table `ace`.`index_field` trx id 2720357778 lock_mode X
Record lock, heap no 1 PHYSICAL RECORD: n_fields 1; compact format; info bits 0
 0: len 8; hex 73757072656d756d; asc supremum;;


*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 86052 page no 4 n bits 240 index PRIMARY of table `ace`.`index_field` trx id 2720357778 lock_mode X insert intention waiting
Record lock, heap no 1 PHYSICAL RECORD: n_fields 1; compact format; info bits 0
 0: len 8; hex 73757072656d756d; asc supremum;;


*** (2) TRANSACTION:
TRANSACTION 2720357777, ACTIVE 0 sec inserting
mysql tables in use 1, locked 1
LOCK WAIT 8 lock struct(s), heap size 1128, 7 row lock(s)
MySQL thread id 27320, OS thread handle 139675585947392, query id 479742157 host ip ref_aceuser update
insert into `index_field` (`fk_index_field_source_id`, `type`, `name`, `analyzer`, `indexed`, `stored`, `term_positions`, `case_sensitive`) values (5, 7, 'FIELD1', 'Alpha numeric', 1, 0, 0, 0), (5, 7, 'FIELD1', 'Alpha numeric', 1, 0, 0, 0), (5, 0, 'EventId', 'Keyword', 1, 1, 0, 0), (5, 7, 'FIELD1', 'Alpha numeric
', 1, 0, 0, 0), (5, 0, 'StreamId', 'Keyword', 1, 1, 0, 0), (5, 7, 'FIELD1', 'Alpha numeric', 1, 0, 0, 0), (5, 6, 'Time', 'Keyword', 1, 0, 0, 0), (5, 7, 'FIELD', 'Alpha numeric', 1, 0, 0, 0), (5, 7, 'FIELD', 'Keyword', 1, 0, 0, 0), (5, 7, 'FIELD1', 'Alpha numeric', 1, 0, 0, 0) on duplicate key update
`index_field`.`fk_index_field_source_id` = 5

*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 86052 page no 4 n bits 240 index PRIMARY of table `ace`.`index_field` trx id 2720357777 lock_mode X
Record lock, heap no 1 PHYSICAL RECORD: n_fields 1; compact format; info bits 0
 0: len 8; hex 73757072656d756d; asc supremum;;


*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 86052 page no 4 n bits 240 index PRIMARY of table `ace`.`index_field` trx id 2720357777 lock_mode X insert intention waiting
Record lock, heap no 1 PHYSICAL RECORD: n_fields 1; compact format; info bits 0
 0: len 8; hex 73757072656d756d; asc supremum;;

*** WE ROLL BACK TRANSACTION (1)

```

**Comment by at055612** [comment]
Fixed in >7.3-beta.14
