### ISSUE TITLE
v7.3 Shard Error on close

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#4213]
```
ERROR  [2024-04-13T04:29:46.823Z] [Index Shard Writer Cache #12986] stroom.index.lucene980.Lucene980IndexShardWriter -  /xxxxxxx/xxxxx/index/xxxxxxxx/2024-04/32103/segments_y
java.nio.file.NoSuchFileException: /xxxxxx/xxxxxx/index/xxxxxxxx/2024-04/32103/segments_y
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:291)
        at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:104)
        at java.base/java.nio.file.Files.delete(Files.java:1152)
        at org.apache.lucene980.store.FSDirectory.privateDeleteFile(FSDirectory.java:346)
        at org.apache.lucene980.store.FSDirectory.deleteFile(FSDirectory.java:311)
        at org.apache.lucene980.store.LockValidatingDirectoryWrapper.deleteFile(LockValidatingDirectoryWrapper.java:37)
        at org.apache.lucene980.util.FileDeleter.delete(FileDeleter.java:234)
        at org.apache.lucene980.util.FileDeleter.delete(FileDeleter.java:218)
        at org.apache.lucene980.util.FileDeleter.deleteFilesIfNoRef(FileDeleter.java:190)
        at org.apache.lucene980.index.IndexFileDeleter.refresh(IndexFileDeleter.java:496)
        at org.apache.lucene980.index.IndexWriter.rollbackInternalNoCommit(IndexWriter.java:2520)
        at org.apache.lucene980.index.IndexWriter.rollbackInternal(IndexWriter.java:2449)
        at org.apache.lucene980.index.IndexWriter.shutdown(IndexWriter.java:1334)
        at org.apache.lucene980.index.IndexWriter.close(IndexWriter.java:1362)
        at stroom.index.lucene980.Lucene980IndexShardWriter.close(Lucene980IndexShardWriter.java:364)
        at stroom.index.impl.IndexShardWriterCacheImpl.lambda$close$17(IndexShardWriterCacheImpl.java:378)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$2(TaskContextFactoryImpl.java:253)
        at stroom.util.logging.LocationAwareLambdaLogger.logDurationIfDebugEnabled(LocationAwareLambdaLogger.java:307)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$4(TaskContextFactoryImpl.java:253)
        at stroom.util.pipeline.scope.PipelineScopeRunnable.scopeResult(PipelineScopeRunnable.java:39)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$5(TaskContextFactoryImpl.java:250)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$6(TaskContextFactoryImpl.java:262)
        at stroom.security.impl.SecurityContextImpl.useAsReadResult(SecurityContextImpl.java:390)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
        at jdk.proxy2/jdk.proxy2.$Proxy120.useAsReadResult(Unknown Source)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$7(TaskContextFactoryImpl.java:262)
        at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:322)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
        at jdk.proxy2/jdk.proxy2.$Proxy120.asUserResult(Unknown Source)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$11(TaskContextFactoryImpl.java:260)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)

```

**Comment by stroomdev66** [comment]
Closing for now
