### ISSUE TITLE
Exception when using --createUser in the manageUsers CLI command

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#4299]
```
Caused by: java.util.NoSuchElementException: null
        at java.base/java.util.List.getFirst(List.java:825)
        at stroom.security.impl.db.UserDaoImpl.getBySubjectId(UserDaoImpl.java:170)
        at stroom.security.impl.UserServiceImpl.getUserBySubjectId(UserServiceImpl.java:96)
        at stroom.app.commands.ManageUsersCommand.createUser(ManageUsersCommand.java:222)
        ... 22 common frames omitted
```

**Comment by at055612** [comment]
Fixed in >7.4-beta.15
