### ISSUE TITLE
Optimistic lock exception on 1st attempt at data upload

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#432]
Got the following error in master-20171004-DAILY when attempting to upload a data zip into a feed.  Worked fine on second attempt.

```
stroom             | ERROR  [15:03:15.343] [dw-85 - POST /dispatch.rpc - UploadDataAction - StreamUploadTask] s.s.s.u.StreamUploadTaskHandler -  importData() - aborting import  
stroom             | javax.persistence.OptimisticLockException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [stroom.node.shared.VolumeState#1]
stroom             |    at org.hibernate.jpa.spi.AbstractEntityManagerImpl.wrapStaleStateException(AbstractEntityManagerImpl.java:1785)
stroom             |    at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1705)
stroom             |    at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1677)
stroom             |    at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1683)
stroom             |    at org.hibernate.jpa.spi.AbstractEntityManagerImpl.flush(AbstractEntityManagerImpl.java:1338)
stroom             |    at sun.reflect.GeneratedMethodAccessor119.invoke(Unknown Source)
stroom             |    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
stroom             |    at java.lang.reflect.Method.invoke(Method.java:498)
stroom             |    at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:298)
stroom             |    at com.sun.proxy.$Proxy154.flush(Unknown Source)
stroom             |    at stroom.entity.server.util.StroomEntityManagerImpl.internalSaveEntity(StroomEntityManagerImpl.java:140)

stroom             | Caused by: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [stroom.node.shared.VolumeState#1]
stroom             |    at org.hibernate.persister.entity.AbstractEntityPersister.check(AbstractEntityPersister.java:2541)
stroom             |    at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3285)
stroom             |    at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:3183)
stroom             |    at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3525)
stroom             |    at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:159)
stroom             |    at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:465)
stroom             |    at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:351)
stroom             |    at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:350)
stroom             |    at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56)
stroom             |    at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1222)
stroom             |    at org.hibernate.jpa.spi.AbstractEntityManagerImpl.flush(AbstractEntityManagerImpl.java:1335)
stroom             |    ... 174 common frames omitted
```

**Comment by at055612** [comment]
Repeated this process in a fresh container and it didn't happen.  Import worked 1st time.
