### ISSUE TITLE
HTTPAppender with useCompression=true

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#4331]
Changed my httpAppender to `useCompression=true` , I started to see lots of the following ERROR

```
DEBUG  [2024-06-24T10:37:25.773Z] [Data Processor# #131577] stroom.pipeline.writer.HTTPAppender -  Added 'Feed: SOME-EVENTS-V1' to {Feed=SOME-EVENTS-V1, GUID=xxxx-xxxxxx-xxxxx-xxxxx}
INFO   [2024-06-24T10:37:25.785Z] [Data Processor# #131577] stroom.pipeline.writer.HTTPAppender -  createOutputStream() - https://server/stroom/datafeed Sending request {Feed=SOME-EVENTS-V1, GUID=xxxx-xxxxxx-xxxxx-xxxxx}
INFO   [2024-06-24T10:37:25.785Z] [Data Processor# #131577] stroom.pipeline.writer.HTTPAppender -  Configuring SSLSocketFactory for destination https://server/stroom/datafeed
INFO   [2024-06-24T10:37:25.786Z] [Data Processor# #131577] stroom.util.cert.SSLUtil -  Loading keystore /data-dir/config/certs/identity.jks of type JKS
INFO   [2024-06-24T10:37:25.786Z] [Data Processor# #131577] stroom.util.cert.SSLUtil -  Loading truststore /dir/stroom/certs/KEYSTORE.jks of type JKS
INFO   [2024-06-24T10:37:25.787Z] [Data Processor# #131577] stroom.util.cert.SSLUtil -  Creating ssl socket factory
ERROR  [2024-06-24T10:37:25.823Z] [Data Processor# #131577] stroom.pipeline.writer.HTTPAppender -  ERROR LOGGING MESSAGE - Already connected
java.lang.IllegalStateException: Already connected
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getRequestProperties(HttpURLConnection.java:3417)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getRequestProperties(HttpsURLConnectionImpl.java:327)
        at stroom.pipeline.writer.HTTPAppender.lambda$logConnectionToDebug$5(HTTPAppender.java:197)
        at stroom.util.logging.LocationAwareLambdaLogger.log(LocationAwareLambdaLogger.java:417)
        at stroom.util.logging.LocationAwareLambdaLogger.debug(LocationAwareLambdaLogger.java:40)
        at stroom.util.logging.LocationAwareLambdaLogger.debug(LocationAwareLambdaLogger.java:34)
        at stroom.pipeline.writer.HTTPAppender.logConnectionToDebug(HTTPAppender.java:190)
        at stroom.pipeline.writer.HTTPAppender.createOutput(HTTPAppender.java:167)
        at stroom.pipeline.writer.AbstractAppender.getOutputStream(AbstractAppender.java:102)
        at stroom.pipeline.writer.AbstractWriter.borrowDestinations(AbstractWriter.java:119)
        at stroom.pipeline.writer.XMLWriter.endElement(XMLWriter.java:443)
        at stroom.pipeline.filter.XMLFilterFork.endElement(XMLFilterFork.java:527)
        at stroom.pipeline.filter.AbstractXMLFilter.endElement(AbstractXMLFilter.java:326)
        at stroom.pipeline.filter.RecordCountFilter.endElement(RecordCountFilter.java:192)
        at net.sf.saxon.event.ContentHandlerProxy.endElement(ContentHandlerProxy.java:412)
        at net.sf.saxon.event.ProxyReceiver.endElement(ProxyReceiver.java:185)
        at net.sf.saxon.event.SequenceNormalizer.endElement(SequenceNormalizer.java:230)
        at net.sf.saxon.event.NamespaceReducer.endElement(NamespaceReducer.java:235)
        at net.sf.saxon.event.ComplexContentOutputter.endElement(ComplexContentOutputter.java:559)
        at net.sf.saxon.tree.tiny.TinyElementImpl.copy(TinyElementImpl.java:504)
        at net.sf.saxon.expr.instruct.CopyOf.copyOneNode(CopyOf.java:614)
        at net.sf.saxon.expr.instruct.CopyOf.lambda$processLeavingTail$1(CopyOf.java:544)
        at net.sf.saxon.om.SequenceIterator.forEachOrFail(SequenceIterator.java:128)
        at net.sf.saxon.expr.instruct.CopyOf.processLeavingTail(CopyOf.java:542)
        at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:352)
        at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:533)
        at net.sf.saxon.expr.instruct.ApplyTemplates$ApplyTemplatesPackage.processLeavingTail(ApplyTemplates.java:557)
        at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:451)
        at net.sf.saxon.expr.instruct.ApplyTemplates.apply(ApplyTemplates.java:300)
        at net.sf.saxon.expr.instruct.ApplyTemplates.process(ApplyTemplates.java:251)
        at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:353)
        at net.sf.saxon.expr.instruct.Copy.processLeavingTail(Copy.java:431)
        at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:352)
        at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:533)
        at net.sf.saxon.trans.rules.TextOnlyCopyRuleSet.process(TextOnlyCopyRuleSet.java:71)
        at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:495)
        at net.sf.saxon.trans.XsltController.applyTemplates(XsltController.java:746)
        at net.sf.saxon.s9api.AbstractXsltTransformer.applyTemplatesToSource(AbstractXsltTransformer.java:347)
        at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:349)
        at net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:71)
        at net.sf.saxon.jaxp.TransformerHandlerImpl.endDocument(TransformerHandlerImpl.java:173)
        at stroom.pipeline.filter.XsltFilter.endDocument(XsltFilter.java:305)
        at net.sf.saxon.event.ContentHandlerProxy.close(ContentHandlerProxy.java:295)
        at net.sf.saxon.event.ProxyReceiver.close(ProxyReceiver.java:102)
        at net.sf.saxon.event.SequenceNormalizer.close(SequenceNormalizer.java:248)
        at net.sf.saxon.event.ProxyReceiver.close(ProxyReceiver.java:102)
        at net.sf.saxon.event.ComplexContentOutputter.close(ComplexContentOutputter.java:621)
        at net.sf.saxon.trans.XsltController.applyTemplates(XsltController.java:753)
        at net.sf.saxon.s9api.AbstractXsltTransformer.applyTemplatesToSource(AbstractXsltTransformer.java:347)
        at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:349)
        at net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:71)
        at net.sf.saxon.jaxp.TransformerHandlerImpl.endDocument(TransformerHandlerImpl.java:173)
        at stroom.pipeline.filter.XsltFilter.endDocument(XsltFilter.java:305)
        at stroom.pipeline.filter.AbstractXMLFilter.endDocument(AbstractXMLFilter.java:158)
        at stroom.pipeline.filter.AbstractXMLFilter.endDocument(AbstractXMLFilter.java:158)
        at stroom.pipeline.filter.SplitFilter.endElement(SplitFilter.java:356)
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
        at org.apache.xerces.impl.XML11NSDocumentScannerImpl.scanEndElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at stroom.pipeline.parser.AbstractParser.parse(AbstractParser.java:185)
        at stroom.pipeline.parser.AbstractParser.lambda$createProcessors$0(AbstractParser.java:86)
        at stroom.pipeline.factory.PipelineImpl.process(PipelineImpl.java:129)
        at stroom.core.dataprocess.AbstractProcessorTaskExecutor.processNestedStreams(AbstractProcessorTaskExecutor.java:459)
        at stroom.core.dataprocess.AbstractProcessorTaskExecutor.process(AbstractProcessorTaskExecutor.java:340)
        at stroom.core.dataprocess.AbstractProcessorTaskExecutor.exec(AbstractProcessorTaskExecutor.java:239)
        at stroom.processor.impl.DataProcessorTaskHandler.exec(DataProcessorTaskHandler.java:164)
        at stroom.processor.impl.DataProcessorTaskHandler.lambda$exec$0(DataProcessorTaskHandler.java:92)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$2(TaskContextFactoryImpl.java:253)
        at stroom.util.logging.LocationAwareLambdaLogger.logDurationIfDebugEnabled(LocationAwareLambdaLogger.java:307)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$4(TaskContextFactoryImpl.java:253)
        at stroom.util.pipeline.scope.PipelineScopeRunnable.scopeResult(PipelineScopeRunnable.java:39)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$5(TaskContextFactoryImpl.java:250)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$6(TaskContextFactoryImpl.java:262)
        at stroom.security.impl.SecurityContextImpl.useAsReadResult(SecurityContextImpl.java:406)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
        at jdk.proxy2/jdk.proxy2.$Proxy122.useAsReadResult(Unknown Source)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$7(TaskContextFactoryImpl.java:262)
        at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:338)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
        at jdk.proxy2/jdk.proxy2.$Proxy122.asUserResult(Unknown Source)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$11(TaskContextFactoryImpl.java:260)
        at stroom.processor.impl.DataProcessorTaskHandler.lambda$exec$1(DataProcessorTaskHandler.java:92)
        at stroom.security.impl.SecurityContextImpl.useAsReadResult(SecurityContextImpl.java:406)
        at stroom.processor.impl.DataProcessorTaskHandler.lambda$exec$2(DataProcessorTaskHandler.java:87)
        at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:338)
        at stroom.processor.impl.DataProcessorTaskHandler.exec(DataProcessorTaskHandler.java:87)
        at stroom.processor.impl.DataProcessorTaskFactory$RunnableFactoryImpl.lambda$create$0(DataProcessorTaskFactory.java:166)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
		
		DEBUG  [2024-06-24T10:37:25.826Z] [Data Processor# #131577] stroom.pipeline.writer.HTTPAppender -  Cannot write output after reading input.
java.net.ProtocolException: Cannot write output after reading input.
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1442)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1417)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:219)
        at stroom.pipeline.writer.HTTPAppender.createOutput(HTTPAppender.java:171)
        at stroom.pipeline.writer.AbstractAppender.getOutputStream(AbstractAppender.java:102)
        at stroom.pipeline.writer.AbstractWriter.borrowDestinations(AbstractWriter.java:119)
        at stroom.pipeline.writer.XMLWriter.endElement(XMLWriter.java:443)
        at stroom.pipeline.filter.XMLFilterFork.endElement(XMLFilterFork.java:527)
        at stroom.pipeline.filter.AbstractXMLFilter.endElement(AbstractXMLFilter.java:326)
        at stroom.pipeline.filter.RecordCountFilter.endElement(RecordCountFilter.java:192)
        at net.sf.saxon.event.ContentHandlerProxy.endElement(ContentHandlerProxy.java:412)
        at net.sf.saxon.event.ProxyReceiver.endElement(ProxyReceiver.java:185)
        at net.sf.saxon.event.SequenceNormalizer.endElement(SequenceNormalizer.java:230)
        at net.sf.saxon.event.NamespaceReducer.endElement(NamespaceReducer.java:235)
        at net.sf.saxon.event.ComplexContentOutputter.endElement(ComplexContentOutputter.java:559)
        at net.sf.saxon.tree.tiny.TinyElementImpl.copy(TinyElementImpl.java:504)
        at net.sf.saxon.expr.instruct.CopyOf.copyOneNode(CopyOf.java:614)
        at net.sf.saxon.expr.instruct.CopyOf.lambda$processLeavingTail$1(CopyOf.java:544)
        at net.sf.saxon.om.SequenceIterator.forEachOrFail(SequenceIterator.java:128)
        at net.sf.saxon.expr.instruct.CopyOf.processLeavingTail(CopyOf.java:542)
        at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:352)
        at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:533)
        at net.sf.saxon.expr.instruct.ApplyTemplates$ApplyTemplatesPackage.processLeavingTail(ApplyTemplates.java:557)
        at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:451)
        at net.sf.saxon.expr.instruct.ApplyTemplates.apply(ApplyTemplates.java:300)
        at net.sf.saxon.expr.instruct.ApplyTemplates.process(ApplyTemplates.java:251)
        at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:353)
        at net.sf.saxon.expr.instruct.Copy.processLeavingTail(Copy.java:431)
        at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:352)
        at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:533)
        at net.sf.saxon.trans.rules.TextOnlyCopyRuleSet.process(TextOnlyCopyRuleSet.java:71)
        at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:495)
        at net.sf.saxon.trans.XsltController.applyTemplates(XsltController.java:746)
        at net.sf.saxon.s9api.AbstractXsltTransformer.applyTemplatesToSource(AbstractXsltTransformer.java:347)
        at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:349)
        at net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:71)
        at net.sf.saxon.jaxp.TransformerHandlerImpl.endDocument(TransformerHandlerImpl.java:173)
        at stroom.pipeline.filter.XsltFilter.endDocument(XsltFilter.java:305)
        at net.sf.saxon.event.ContentHandlerProxy.close(ContentHandlerProxy.java:295)
        at net.sf.saxon.event.ProxyReceiver.close(ProxyReceiver.java:102)
        at net.sf.saxon.event.SequenceNormalizer.close(SequenceNormalizer.java:248)
        at net.sf.saxon.event.ProxyReceiver.close(ProxyReceiver.java:102)
        at net.sf.saxon.event.ComplexContentOutputter.close(ComplexContentOutputter.java:621)
        at net.sf.saxon.trans.XsltController.applyTemplates(XsltController.java:753)
        at net.sf.saxon.s9api.AbstractXsltTransformer.applyTemplatesToSource(AbstractXsltTransformer.java:347)
        at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:349)
        at net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:71)
        at net.sf.saxon.jaxp.TransformerHandlerImpl.endDocument(TransformerHandlerImpl.java:173)
        at stroom.pipeline.filter.XsltFilter.endDocument(XsltFilter.java:305)
        at stroom.pipeline.filter.AbstractXMLFilter.endDocument(AbstractXMLFilter.java:158)
        at stroom.pipeline.filter.AbstractXMLFilter.endDocument(AbstractXMLFilter.java:158)
        at stroom.pipeline.filter.SplitFilter.endElement(SplitFilter.java:356)
        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)
        at org.apache.xerces.impl.XML11NSDocumentScannerImpl.scanEndElement(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
        at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
        at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
        at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at stroom.pipeline.parser.AbstractParser.parse(AbstractParser.java:185)
        at stroom.pipeline.parser.AbstractParser.lambda$createProcessors$0(AbstractParser.java:86)
        at stroom.pipeline.factory.PipelineImpl.process(PipelineImpl.java:129)
        at stroom.core.dataprocess.AbstractProcessorTaskExecutor.processNestedStreams(AbstractProcessorTaskExecutor.java:459)
        at stroom.core.dataprocess.AbstractProcessorTaskExecutor.process(AbstractProcessorTaskExecutor.java:340)
        at stroom.core.dataprocess.AbstractProcessorTaskExecutor.exec(AbstractProcessorTaskExecutor.java:239)
        at stroom.processor.impl.DataProcessorTaskHandler.exec(DataProcessorTaskHandler.java:164)
        at stroom.processor.impl.DataProcessorTaskHandler.lambda$exec$0(DataProcessorTaskHandler.java:92)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$2(TaskContextFactoryImpl.java:253)
        at stroom.util.logging.LocationAwareLambdaLogger.logDurationIfDebugEnabled(LocationAwareLambdaLogger.java:307)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$4(TaskContextFactoryImpl.java:253)
        at stroom.util.pipeline.scope.PipelineScopeRunnable.scopeResult(PipelineScopeRunnable.java:39)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$5(TaskContextFactoryImpl.java:250)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$6(TaskContextFactoryImpl.java:262)
        at stroom.security.impl.SecurityContextImpl.useAsReadResult(SecurityContextImpl.java:406)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
        at jdk.proxy2/jdk.proxy2.$Proxy122.useAsReadResult(Unknown Source)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$7(TaskContextFactoryImpl.java:262)
        at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:338)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
        at jdk.proxy2/jdk.proxy2.$Proxy122.asUserResult(Unknown Source)
        at stroom.task.impl.TaskContextFactoryImpl.lambda$wrap$11(TaskContextFactoryImpl.java:260)
        at stroom.processor.impl.DataProcessorTaskHandler.lambda$exec$1(DataProcessorTaskHandler.java:92)
        at stroom.security.impl.SecurityContextImpl.useAsReadResult(SecurityContextImpl.java:406)
        at stroom.processor.impl.DataProcessorTaskHandler.lambda$exec$2(DataProcessorTaskHandler.java:87)
        at stroom.security.impl.SecurityContextImpl.asUserResult(SecurityContextImpl.java:338)
        at stroom.processor.impl.DataProcessorTaskHandler.exec(DataProcessorTaskHandler.java:87)
        at stroom.processor.impl.DataProcessorTaskFactory$RunnableFactoryImpl.lambda$create$0(DataProcessorTaskFactory.java:166)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
DEBUG  [2024-06-24T10:37:25.863Z] [Data Processor# #131577] stroom.pipeline.writer.HTTPAppender -  closeConnection() - header fields {null=[HTTP/1.1 200 OK], Transfer-Encoding=[chunked], Server=[nginx/1.20.1], Connection=[keep-alive], Date=[Mon, 24 Jun 2024 10:37:25 GMT]}



```

**Comment by at055612** [comment]
Fixed in > 7.4.4
