### ISSUE TITLE
Stroom proxy 7.0.33+ unable to deal with data larger than 4 GiB

### ISSUE THREAD

**Issue by stroomdev66** [gchq/stroom#4437]

**Comment by stroomdev66** [comment]
[error (1).log](https://github.com/user-attachments/files/16906140/error.1.log)

**Comment by stroomdev66** [comment]
`18:07:10.971
[1;31mERROR [0;39m [2024-09-05T08:07:10.971Z] [[32mdw-28167 - POST /stroom/noauth/datafeed[0;39m] [36mstroom.proxy.app.handler.ProxyRequestHandler[0;39m -  This archive contains unclosed entries. 
18:07:10.971
java.io.IOException: This archive contains unclosed entries.
18:07:10.971
	at org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.finish(ZipArchiveOutputStream.java:1019)
18:07:10.971
	at org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.close(ZipArchiveOutputStream.java:633)
18:07:10.971
	at stroom.data.zip.StroomZipOutputStreamImpl.closeDelete(StroomZipOutputStreamImpl.java:166)
18:07:10.972
	at stroom.proxy.repo.StroomZipRepository$2.closeDelete(StroomZipRepository.java:388)
18:07:10.972
	at stroom.proxy.repo.ProxyRepositoryStreamHandler.handleError(ProxyRepositoryStreamHandler.java:75)
18:07:10.972
	at stroom.proxy.app.handler.ProxyRequestHandler.stream(ProxyRequestHandler.java:142)
18:07:10.972
	at stroom.proxy.app.handler.ProxyRequestHandler.handle(ProxyRequestHandler.java:69)
18:07:10.972
	at stroom.receive.common.ReceiveDataServlet.handleRequest(ReceiveDataServlet.java:97)
18:07:10.972
	at stroom.receive.common.ReceiveDataServlet.doPost(ReceiveDataServlet.java:71)
18:07:10.972
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
18:07:10.972
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
18:07:10.972
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
18:07:10.972
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
18:07:10.972
	at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
18:07:10.972
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
18:07:10.972
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
18:07:10.972
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:45)
18:07:10.972
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39)
18:07:10.972
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
18:07:10.972
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
18:07:10.972
	at stroom.proxy.app.servlet.ProxySecurityFilter.filter(ProxySecurityFilter.java:146)
18:07:10.972
	at stroom.proxy.app.servlet.ProxySecurityFilter.doFilter(ProxySecurityFilter.java:105)
18:07:10.972
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
18:07:10.972
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
18:07:10.972
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:319)
18:07:10.972
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:273)
18:07:10.972
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
18:07:10.972
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
18:07:10.972
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
18:07:10.972
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
18:07:10.972
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
18:07:10.972
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
18:07:10.972
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
18:07:10.972
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
18:07:10.972
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
18:07:10.972
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
18:07:10.972
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
18:07:10.972
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
18:07:10.972
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
18:07:10.972
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
18:07:10.972
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:313)
18:07:10.972
	at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
18:07:10.972
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:716)
18:07:10.972
	at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:67)
18:07:10.972
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
18:07:10.972
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179)
18:07:10.972
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
18:07:10.972
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
18:07:10.972
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
18:07:10.972
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
18:07:10.972
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
18:07:10.972
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
18:07:10.972
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
18:07:10.972
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
18:07:10.972
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:540)
18:07:10.972
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:395)
18:07:10.972
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:161)
18:07:10.972
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
18:07:10.972
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
18:07:10.972
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
18:07:10.972
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
18:07:10.972
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
18:07:10.972
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
18:07:10.972
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)
18:07:10.972
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
18:07:10.972
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
18:07:10.972
	at java.base/java.lang.Thread.run(Thread.java:832)`
