### ISSUE TITLE
Analytic Rule perm issue when Executing

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#4617]
```
Error executing rule: ABCRule (123456) 
stroom.util.shared.PermissionException: You are not authorised to read AnalyticRule 'ABCRule' {123456}
&#x9;at stroom.docstore.impl.StoreImpl.read(StoreImpl.java:571)
&#x9;at stroom.docstore.impl.StoreImpl.read(StoreImpl.java:561)
&#x9;at stroom.docstore.impl.StoreImpl.readDocument(StoreImpl.java:292)
&#x9;at stroom.docstore.impl.StoreImpl.readDocument(StoreImpl.java:67)
&#x9;at stroom.analytics.rule.impl.AnalyticRuleStoreImpl.readDocument(AnalyticRuleStoreImpl.java:248)
&#x9;at stroom.analytics.rule.impl.AnalyticRuleStoreImpl.readDocument(AnalyticRuleStoreImpl.java:53)
&#x9;at stroom.analytics.impl.ScheduledQueryAnalyticExecutor.executeIfScheduled(ScheduledQueryAnalyticExecutor.java:256)
&#x9;at stroom.analytics.impl.ScheduledQueryAnalyticExecutor.lambda$execAnalyticAsUser$8(ScheduledQueryAnalyticExecutor.java:230)
&#x9;at stroom.security.impl.SecurityContextImpl.useAsRead(SecurityContextImpl.java:423)
&#x9;at stroom.analytics.impl.ScheduledQueryAnalyticExecutor.lambda$execAnalyticAsUser$9(ScheduledQueryAnalyticExecutor.java:227)
&#x9;at stroom.security.impl.SecurityContextImpl.asUser(SecurityContextImpl.java:355)
&#x9;at stroom.analytics.impl.ScheduledQueryAnalyticExecutor.lambda$execAnalyticAsUser$11(ScheduledQueryAnalyticExecutor.java:227)
&#x9;at stroom.util.concurrent.WorkQueue.lambda$new$0(WorkQueue.java:26)
&#x9;at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
&#x9;at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
&#x9;at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
&#x9;at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by at055612** [comment]
PR is only debug logging
