### ISSUE TITLE
New Index is generating corrupt shards

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#508]
Created a new index, some shards have been marked as corrupt almost immediately.

**Comment by stroomdev10** [comment]
2017-12-04T14:18:40.101Z ERROR [Stream Processor# #31437 - StreamProcessorTask] server.IndexShardWriterCacheImpl (IndexShardWriterCacheImpl.java:211) - Setting index shard status to corrupt because (stroom.index.server.IndexException: Unable to create directories for new index in ""/rootDirectory/IndexDirectory/nodeName/index/131/2017-11/49797")
stroom.index.server.IndexException: Unable to create directories for new index in "/rootDirectory/IndexDirectory/nodeName/index/131/2017-11/49797"
        at stroom.index.server.IndexShardWriterImpl.<init>(IndexShardWriterImpl.java:141)
        at stroom.index.server.IndexShardWriterCacheImpl.openWriter(IndexShardWriterCacheImpl.java:196)
        at stroom.index.server.IndexShardWriterCacheImpl.openExistingShard(IndexShardWriterCacheImpl.java:161)
        at stroom.index.server.IndexShardWriterCacheImpl.lambda$getWriterByShardKey$0(IndexShardWriterCacheImpl.java:130)
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
        at stroom.index.server.IndexShardWriterCacheImpl.getWriterByShardKey(IndexShardWriterCacheImpl.java:121)
        at stroom.index.server.IndexerImpl.addDocument(IndexerImpl.java:56)
        at stroom.index.server.IndexingFilter.processDocument(IndexingFilter.java:200)
        at stroom.index.server.IndexingFilter.endElement(IndexingFilter.java:179)
        at net.sf.saxon.event.ContentHandlerProxy.endElement(ContentHandlerProxy.java:402)
        at net.sf.saxon.event.NamespaceReducer.endElement(NamespaceReducer.java:231)
        at net.sf.saxon.event.ComplexContentOutputter.endElement(ComplexContentOutputter.java:560)
        at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:367)
        at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:311)
        at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:353)
        at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:456)
        at net.sf.saxon.expr.instruct.ApplyTemplates.apply(ApplyTemplates.java:298)
        at net.sf.saxon.expr.instruct.ApplyTemplates.processLeavingTail(ApplyTemplates.java:255)
        at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:653)
        at net.sf.saxon.expr.instruct.Instruction.process(Instruction.java:149)
        at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:364)
        at net.sf.saxon.expr.instruct.ElementCreator.processLeavingTail(ElementCreator.java:311)
        at net.sf.saxon.expr.instruct.TemplateRule.applyLeavingTail(TemplateRule.java:353)
        at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:456)
        at net.sf.saxon.trans.TextOnlyCopyRuleSet.process(TextOnlyCopyRuleSet.java:65)
        at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:433)
        at net.sf.saxon.Controller.transformDocument(Controller.java:2321)
        at net.sf.saxon.Controller.transform(Controller.java:1892)
        at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:579)
        at net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:185)
        at net.sf.saxon.jaxp.TransformerHandlerImpl.endDocument(TransformerHandlerImpl.java:172)
        at stroom.pipeline.server.filter.XSLTFilter.endDocument(XSLTFilter.java:353)
        at stroom.pipeline.server.filter.AbstractXMLFilter.endDocument(AbstractXMLFilter.java:168)
        at stroom.pipeline.server.filter.AbstractXMLFilter.endDocument(AbstractXMLFilter.java:168)
        at stroom.pipeline.server.filter.SplitFilter.endElement(SplitFilter.java:320)
        at stroom.pipeline.server.filter.AbstractXMLFilter.endElement(AbstractXMLFilter.java:353)
        at stroom.pipeline.server.filter.RecordCountFilter.endElement(RecordCountFilter.java:204)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
        at com.sun.org.apache.xerces.internal.impl.XML11NSDocumentScannerImpl.scanEndElement(XML11NSDocumentScannerImpl.java:779)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
        at com.sun.org.apache.xerces.internal.impl.XML11NSDocumentScannerImpl.next(XML11NSDocumentScannerImpl.java:822)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
        at stroom.pipeline.server.parser.AbstractParser.parse(AbstractParser.java:179)
        at stroom.pipeline.server.parser.AbstractParser.lambda$createProcessors$0(AbstractParser.java:80)
        at stroom.pipeline.server.factory.PipelineImpl.process(PipelineImpl.java:128)
        at stroom.pipeline.server.task.PipelineStreamProcessor.processNestedStreams(PipelineStreamProcessor.java:432)
        at stroom.pipeline.server.task.PipelineStreamProcessor.process(PipelineStreamProcessor.java:227)
        at stroom.pipeline.server.task.PipelineStreamProcessor.exec(PipelineStreamProcessor.java:165)
        at stroom.streamtask.server.StreamProcessorTaskHandler.exec(StreamProcessorTaskHandler.java:133)
        at stroom.streamtask.server.StreamProcessorTaskHandler.exec(StreamProcessorTaskHandler.java:45)
        at stroom.task.server.AbstractTaskHandler.exec(AbstractTaskHandler.java:30)
        at sun.reflect.GeneratedMethodAccessor228.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
        at stroom.security.server.UserSecurityMethodInterceptor.secureMethod(UserSecurityMethodInterceptor.java:94)
        at sun.reflect.GeneratedMethodAccessor113.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
        at com.sun.proxy.$Proxy143.exec(Unknown Source)
        at stroom.task.server.TaskManagerImpl.doExec(TaskManagerImpl.java:415)
        at stroom.task.server.TaskManagerImpl.access$400(TaskManagerImpl.java:67)
        at stroom.task.server.TaskManagerImpl$1.exec(TaskManagerImpl.java:321)
        at stroom.util.task.TaskScopeRunnable.run(TaskScopeRunnable.java:32)
        at stroom.task.server.TaskManagerImpl$2.exec(TaskManagerImpl.java:359)
        at stroom.util.thread.ThreadScopeRunnable.run(ThreadScopeRunnable.java:25)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
