### ISSUE TITLE
stroom:format-date() function throws an java exception on an invalid date

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#511]
Previous versions simply returned an empty string.

This is causing errors during translation and stepping

**Comment by stroomdev10** [comment]
Still in 5.1 beta 2

**Comment by stroomdev66** [comment]
java.lang.NullPointerException at net.sf.saxon.tree.tiny.TinyBuilder.endDocument(TinyBuilder.java:175) 
at net.sf.saxon.event.ReceivingContentHandler.endDocument(ReceivingContentHandler.java:243) 
at stroom.pipeline.server.filter.TinyTreeBufferFilter.endDocument(TinyTreeBufferFilter.java:120) 
at stroom.pipeline.server.filter.AbstractXMLFilter.endDocument(AbstractXMLFilter.java:168) 
at stroom.pipeline.server.filter.XSLTFilter.endDocument(XSLTFilter.java:371) 
at stroom.pipeline.server.filter.AbstractXMLFilter.endDocument(AbstractXMLFilter.java:168) 
at stroom.pipeline.server.filter.TinyTreeBufferFilter.endDocument(TinyTreeBufferFilter.java:131) 
at stroom.pipeline.server.filter.AbstractXMLFilter.endDocument(AbstractXMLFilter.java:168) 
at stroom.pipeline.server.filter.SAXRecordDetector.endDocument(SAXRecordDetector.java:58) 
at stroom.pipeline.server.filter.AbstractXMLFilter.endDocument(AbstractXMLFilter.java:168) 
at stroom.pipeline.server.filter.TinyTreeBufferFilter.endDocument(TinyTreeBuffer...
