### ISSUE TITLE
Proxy Aggregation is broken in 5.1-beta.2

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#524]
2017-12-13T10:40:08.001Z ERROR [Stroom P2 #8 - LifecycleTask] server.ProxyAggregationExecutor (ProxyAggregationExecutor.java:158) - Error waiting for 15 proxy aggregation jobs to complete
java.lang.RuntimeException: Error waiting for 15 proxy aggregation jobs to complete
        at stroom.proxy.repo.StroomZipRepositoryProcessor.process(StroomZipRepositoryProcessor.java:167)
        at stroom.streamtask.server.ProxyAggregationExecutor.aggregate(ProxyAggregationExecutor.java:153)
        at stroom.streamtask.server.ProxyAggregationExecutor.aggregate(ProxyAggregationExecutor.java:107)
        at stroom.streamtask.server.ProxyAggregationExecutor.exec(ProxyAggregationExecutor.java:103)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at stroom.util.spring.StroomBeanStore.invoke(StroomBeanStore.java:151)
        at stroom.util.spring.StroomBeanMethodExecutable.exec(StroomBeanMethodExecutable.java:58)
        at stroom.jobsystem.server.ScheduledTaskExecutorImpl$JobNodeTrackedExecutable.exec(ScheduledTaskExecutorImpl.java:63)
        at stroom.lifecycle.LifecycleTaskHandler.exec(LifecycleTaskHandler.java:37)
        at stroom.lifecycle.LifecycleTaskHandler.exec(LifecycleTaskHandler.java:27)
        at stroom.task.server.AbstractTaskHandler.exec(AbstractTaskHandler.java:30)
        at sun.reflect.GeneratedMethodAccessor146.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
        at stroom.security.server.UserSecurityMethodInterceptor.secureMethod(UserSecurityMethodInterceptor.java:94)
        at sun.reflect.GeneratedMethodAccessor113.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
        at com.sun.proxy.$Proxy132.exec(Unknown Source)
        at stroom.task.server.TaskManagerImpl.doExec(TaskManagerImpl.java:414)
        at stroom.task.server.TaskManagerImpl.access$500(TaskManagerImpl.java:67)
        at stroom.task.server.TaskManagerImpl$1.exec(TaskManagerImpl.java:322)
        at stroom.util.task.TaskScopeRunnable.run(TaskScopeRunnable.java:32)
        at stroom.task.server.TaskManagerImpl$2.exec(TaskManagerImpl.java:359)
        at stroom.util.thread.ThreadScopeRunnable.run(ThreadScopeRunnable.java:25)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: stroom.util.shared.Monitor.setName(Ljava/lang/String;)V
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
        at stroom.proxy.repo.StroomZipRepositoryProcessor.process(StroomZipRepositoryProcessor.java:162)
        ... 41 more
Caused by: java.lang.NoSuchMethodError: stroom.util.shared.Monitor.setName(Ljava/lang/String;)V
        at stroom.task.server.CurrentTaskState.setName(CurrentTaskState.java:68)
        at stroom.task.server.TaskContextImpl.setName(TaskContextImpl.java:25)
        at stroom.proxy.repo.StroomZipRepositoryProcessor.lambda$createProcessFeedFilesTask$6(StroomZipRepositoryProcessor.java:187)
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
        at stroom.task.server.GenericServerTaskHandler.exec(GenericServerTaskHandler.java:23)
        at stroom.task.server.GenericServerTaskHandler.exec(GenericServerTaskHandler.java:10)
        ... 29 more

**Comment by at055612** [comment]
The issue appears to be that stroom 5.1beta.2 depends on stroom-proxy:stroom-proxy-repo v5.1-beta.8.  Both have the class stroom.util.shared.Monitor.

The version of Monitor in stroom has get/setName but the one in stroom-proxy-repo does not.  Its at the mercy of the class loader as to which version get loaded.

**Comment by at055612** [comment]
We could 
* move the classes in -proxy that are common with stroom into a sub package of stroom.proxy to avoid the conflict
* move them into a new module and exclude that dependency when stroom pulls in -proxy-repo
* bring the common classes in stroom-proxy into line with stroom, but this is just another accident waiting to happen.
