### ISSUE TITLE
Adding a SQL Statistic Data Source via Import requires the user to clear the DataSource caches before it is available for query.

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom#539]
Directly after adding a SQL Stats Datasource via import, a user can access the Datasource via the UI, but querying for results in a transient error triangle that reports "No DataSource Found"

Clearing the SQL DataSource caches removes this message.

**Comment by at055612** [comment]
Opened stroom
created dashboard with the CPU stat
made sure i could query it
exported CPU stat config
deleted CPU stat config
restarted stroom
imported CPU stat config
opened dashboard and hit run - it returned data

I haven't managed to re-create this issue

**Comment by stroomdev10** [comment]
Open Stroom
Create Dash that queries a stat
export stat from above
clear both stats caches
open dash, check that stat isn't queryable, close dash
import stat
open dash, query stat
get error

I got stroom.statistics.server.common.StatisticEventStoreFactoryImpl$DoNothingStatisticEventStore cannot be cast to stroom.statistics.server.common.AbstractStatistics

**Comment by at055612** [comment]
Did as above but with deleting the stat after clearing the caches.  Still queries it ok.  Do you have a stack or at least a line for the exception?

**Comment by stroomdev10** [comment]
2018-01-08T14:36:37.770Z ERROR [Stroom P2 #10] server.TaskManagerImpl$1 (TaskManagerImpl.java:335) - stroom.statistics.server.common.StatisticEventStoreFactoryImpl$DoNothingStatisticEventStore cannot be cast to stroom.statistics.server.common.AbstractStatistics (StatStoreSearchTask)
java.lang.RuntimeException: stroom.statistics.server.common.StatisticEventStoreFactoryImpl$DoNothingStatisticEventStore cannot be cast to stroom.statistics.server.common.AbstractStatistics
	at stroom.statistics.server.common.search.StatStoreSearchResultCollector$1.onFailure(StatStoreSearchResultCollector.java:66)
	at stroom.task.server.AbstractTaskHandler.exec(AbstractTaskHandler.java:42)
	at sun.reflect.GeneratedMethodAccessor142.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at stroom.security.server.UserSecurityMethodInterceptor.secureMethod(UserSecurityMethodInterceptor.java:94)
	at sun.reflect.GeneratedMethodAccessor111.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:621)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:610)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:68)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
	at com.sun.proxy.$Proxy133.exec(Unknown Source)
	at stroom.task.server.TaskManagerImpl.doExec(TaskManagerImpl.java:414)
	at stroom.task.server.TaskManagerImpl.access$500(TaskManagerImpl.java:67)
	at stroom.task.server.TaskManagerImpl$1.exec(TaskManagerImpl.java:322)
	at stroom.util.task.TaskScopeRunnable.run(TaskScopeRunnable.java:32)
	at stroom.task.server.TaskManagerImpl$2.exec(TaskManagerImpl.java:359)
	at stroom.util.thread.ThreadScopeRunnable.run(ThreadScopeRunnable.java:25)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: stroom.statistics.server.common.StatisticEventStoreFactoryImpl$DoNothingStatisticEventStore cannot be cast to stroom.statistics.server.common.AbstractStatistics
	at stroom.statistics.server.common.search.StatStoreSearchTaskHandler.exec(StatStoreSearchTaskHandler.java:83)
	at stroom.statistics.server.common.search.StatStoreSearchTaskHandler.exec(StatStoreSearchTaskHandler.java:54)
	at stroom.task.server.AbstractTaskHandler.exec(AbstractTaskHandler.java:30)
	... 28 more

**Comment by at055612** [comment]
Managed to recreate `Could not retrieve a datasource entity from the database type=StatisticStore, uuid=af08c4a7-ee7c-44e4-8f5e-e9c6be280434, name=CPU` but could not recreate the class cast exception, though I suspect they are both symptoms of the same issue, ie. we are holding stale data in the stat datasource cache. Have changed it to invalidate cache entries when an entity is created and have added additional error handling for the CCE.
