### ISSUE TITLE
InteruptedException during sql stats queries

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#703]
Probably due to use of window() in StatStoreSearchTaskHandler, which is run in another thread.

**Comment by at055612** [comment]
```

2018-03-26T07:33:31.766Z ERROR [RxComputationThreadPool-1] query.TablePayloadHandler (TablePayloadHandler.java:193) - null - java.lang.InterruptedException
java.lang.InterruptedException
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireInterruptibly(AbstractQueuedSynchronizer.java:1220)
        at java.util.concurrent.locks.ReentrantLock.lockInterruptibly(ReentrantLock.java:335)
        at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:339)
        at stroom.query.TablePayloadHandler.addQueue(TablePayloadHandler.java:191)
        at stroom.query.SearchResultHandler.handle(SearchResultHandler.java:59)
        at stroom.statistics.server.common.search.StatStoreSearchResultCollector.handle(StatStoreSearchResultCollector.java:86)
        at stroom.statistics.server.common.search.StatStoreSearchTaskHandler.processPayloads(StatStoreSearchTaskHandler.java:191)
        at stroom.statistics.server.common.search.StatStoreSearchTaskHandler.lambda$null$5(StatStoreSearchTaskHandler.java:147)
        at io.reactivex.internal.subscribers.LambdaSubscriber.onComplete(LambdaSubscriber.java:94)
        at io.reactivex.processors.UnicastProcessor.checkTerminated(UnicastProcessor.java:322)
        at io.reactivex.processors.UnicastProcessor.drainRegular(UnicastProcessor.java:205)
        at io.reactivex.processors.UnicastProcessor.drain(UnicastProcessor.java:289)
        at io.reactivex.processors.UnicastProcessor.onComplete(UnicastProcessor.java:379)
        at io.reactivex.internal.operators.flowable.FlowableWindowTimed$WindowExactUnboundedSubscriber.drainLoop(FlowableWindowTimed.java:229)
        at io.reactivex.internal.operators.flowable.FlowableWindowTimed$WindowExactUnboundedSubscriber.run(FlowableWindowTimed.java:200)
        at io.reactivex.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:39)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by at055612** [comment]
The TablePayloadHandler is catching the InteruptedException (possibly from rxjava stopping the window thread), logging it and doing nothing more.  It doesn't need to log the stack as this is not unexpected behaviour.  It also needs to reset the interrupt flag.
