### ISSUE TITLE
'Only administrators can create root level entries' when querying on dashboard

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#751]
If I run a dash query in UI as a new user I get
```
ERROR  [09:01:32.679] [dw-360 - POST /stroom/dispatch.rpc - SearchBusPollAction] s.d.s.SearchBusPollActionHandler -  2dcdb36 
stroom.entity.shared.PermissionException: Only administrators can create root level entries
    at stroom.entity.server.DocumentEntityServiceImpl.checkCreatePermission(DocumentEntityServiceImpl.java:614)
    at stroom.entity.server.DocumentEntityServiceImpl.create(DocumentEntityServiceImpl.java:112)
    at stroom.entity.server.DocumentEntityServiceImpl.create(DocumentEntityServiceImpl.java:104)
    at stroom.dashboard.server.QueryServiceImpl.create(QueryServiceImpl.java:71)
```
User has 'Data - View' and 'Data - View with pipeline' and Use+Read on the dash.

Seen in `6.0` branch commit 2dcdb36 (.alpha.21)

**Comment by at055612** [comment]
Fixed in >6.0.alpha.21
