### ISSUE TITLE
Tools -> Dependencies shows and error

### ISSUE THREAD

**Issue by jc064522** [gchq/stroom#888]
Error dialog is: 'Invalid HTTP status returned from delete: 502'

**Comment by stroomdev66** [comment]
The error that was causing the screen to fail was in `ExternalDocumentEntityServiceImpl` and was related to not being able to authenticate to external document services successfully. This error has now been trapped and logged although it means that external documents will not always be listed in the dependencies screen. Since external documents are set to be re-integrated in version 7 I think logging this error is sufficient for now as at least the screen now works.

**Comment by stroomdev66** [comment]
This is the underlying exception
```
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:871)
	at stroom.query.audit.security.ServiceUser.<init>(ServiceUser.java:27)
	at stroom.query.audit.security.ServiceUser$Builder.build(ServiceUser.java:52)
	at stroom.externaldoc.server.ExternalDocumentEntityServiceImpl.serviceUser(ExternalDocumentEntityServiceImpl.java:76)
	at stroom.externaldoc.server.ExternalDocumentEntityServiceImpl.listDocuments(ExternalDocumentEntityServiceImpl.java:225)
	at stroom.externaldoc.server.ExternalDocumentEntityServiceImpl.getDependencies(ExternalDocumentEntityServiceImpl.java:248)
	at stroom.importexport.server.DependencyServiceImpl.lambda$getDependencies$0(DependencyServiceImpl.java:32)
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
	at stroom.importexport.server.DependencyServiceImpl.getDependencies(DependencyServiceImpl.java:31)
	at stroom.importexport.server.FetchDependenciesHandler.exec(FetchDependenciesHandler.java:41)
	at stroom.importexport.server.FetchDependenciesHandler.exec(FetchDependenciesHandler.java:29)
```
