### ISSUE TITLE
Failed to get lock as no writeable volumes

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#907]
Seeing this in a local version of the stack that has log shipping set up.  I suspect that the logs are being received by the datafeed servlet before the two default volumes have been auto-created.  It would be nice not to have stacks showing up for what is normal running, but not sure how best we could solve it.

```
WARN   [2018-10-31T13:21:03.278Z] [dw-40 - POST /stroom/datafeed] s.v.s.VolumeServiceImpl -  getVolumeSet - Failed to obtain 1 volumes as required on node Node (id=1, version=0, name=node1a, name=node1a, clusterCallUrl=null, priority=1) (set=[]) 
WARN   [2018-10-31T13:21:03.278Z] [dw-40 - POST /stroom/datafeed] s.s.s.f.FileSystemStreamStoreImpl -  Failed to get lock on Stream (id=-1, version=-1, type=11, feed=7) 
stroom.streamstore.server.StreamException: Failed to get lock as no writeable volumes
        at stroom.streamstore.server.fs.FileSystemStreamStoreImpl.obtainLockForUpdate(FileSystemStreamStoreImpl.java:408)
        at stroom.streamstore.server.fs.FileSystemStreamStoreImpl.openStreamTarget(FileSystemStreamStoreImpl.java:489)
        at stroom.streamstore.server.fs.FileSystemStreamStoreImpl.openStreamTarget(FileSystemStreamStoreImpl.java:474)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy195.openStreamTarget(Unknown Source)
        at stroom.streamtask.server.StreamTargetStroomStreamHandler.getCurrentNestedStreamTarget(StreamTargetStroomStreamHandler.java:292)
        at stroom.streamtask.server.StreamTargetStroomStreamHandler.handleEntryStart(StreamTargetStroomStreamHandler.java:175)
        at stroom.proxy.repo.StroomStreamProcessor.handleEntryStart(StroomStreamProcessor.java:370)
        at stroom.proxy.repo.StroomStreamProcessor.process(StroomStreamProcessor.java:161)
        at stroom.datafeed.server.DataFeedRequestHandler.handle(DataFeedRequestHandler.java:124)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
        at stroom.security.server.UserSecurityMethodInterceptor.secureMethod(UserSecurityMethodInterceptor.java:91)
        at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy232.handle(Unknown Source)
        at stroom.datafeed.server.DataFeedServlet.handleRequest(DataFeedServlet.java:84)
        at stroom.datafeed.server.DataFeedServlet.doPost(DataFeedServlet.java:58)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
```

**Comment by stroomdev66** [comment]
Fixed in v6.0-beta.12
