### ISSUE TITLE
Duplicate entry 'proxy-\x00' for key 'NAME'

### ISSUE THREAD

**Issue by at055612** [gchq/stroom#908]
Seeing this on a version of the stack that has stroom-proxy.  I suspect it is due to proxy hitting the content sync api and stroom is trying to auto create a user record, but failing for some reason.
```
WARN   [2018-10-31T13:21:00.384Z] [dw-38] o.h.e.j.s.SqlExceptionHelper -  SQL Error: 1062, SQLState: 23000                                                                                                                                                            [652/4200]
ERROR  [2018-10-31T13:21:00.384Z] [dw-38] o.h.e.j.s.SqlExceptionHelper -  Duplicate entry 'proxy-\x00' for key 'NAME' 
DEBUG  [2018-10-31T13:21:00.386Z] [dw-38] o.h.e.j.s.SqlExceptionHelper -  SQL Warning 
java.sql.SQLWarning: Duplicate entry 'proxy-\x00' for key 'NAME'
        at com.mysql.jdbc.SQLError.convertShowWarningsToSQLWarnings(SQLError.java:723)
        at com.mysql.jdbc.SQLError.convertShowWarningsToSQLWarnings(SQLError.java:656)
        at com.mysql.jdbc.StatementImpl.getWarnings(StatementImpl.java:2145)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.getWarnings(NewProxyPreparedStatement.java:1806)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.handleAndClearWarnings(SqlExceptionHelper.java:320)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logAndClearWarnings(SqlExceptionHelper.java:273)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.close(JdbcCoordinatorImpl.java:529)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.release(JdbcCoordinatorImpl.java:421)
        at org.hibernate.id.insert.AbstractReturningDelegate.releaseStatement(AbstractReturningDelegate.java:82)
        at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:61)
        at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3032)
        at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3558)
        at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:98)
        at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:492)
        at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:197)
        at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:181)
        at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:216)
        at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:324)
        at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:288)
        at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:194)
        at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:125)
        at org.hibernate.jpa.event.internal.core.JpaPersistEventListener.saveWithGeneratedId(JpaPersistEventListener.java:84)
        at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:206)
        at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:149)
        at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:75)
        at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:811)
        at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:784)
        at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:789)
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:1181)
        at sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:298)
        at com.sun.proxy.$Proxy131.persist(Unknown Source)
        at stroom.entity.server.util.StroomEntityManagerImpl.internalSaveEntity(StroomEntityManagerImpl.java:146)
        at stroom.entity.server.util.StroomEntityManagerImpl.saveEntity(StroomEntityManagerImpl.java:108)
        at sun.reflect.GeneratedMethodAccessor100.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:282)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy132.saveEntity(Unknown Source)
        at stroom.entity.server.EntityServiceHelper.save(EntityServiceHelper.java:165)
        at stroom.security.server.UserServiceImpl.save(UserServiceImpl.java:298)
        at stroom.security.server.UserServiceImpl.createUser(UserServiceImpl.java:232)
```

**Comment by stroomdev66** [comment]
Stroom now auto creates internal `User` entities whenever it receives an externally authenticated request. If more than one request is being made simultaneously then it is likely that Stroom is trying to create the same internal `User` entity more than once. We either need to check that the entity exists and then create one if it doesn't within the same transaction, or handle the error and reload the user that was created by whichever process managed to create it.

**Comment by stroomdev66** [comment]
This is expected behaviour and the error just needs suppressing in the logs with:
`org.hibernate.engine.jdbc.spi.SqlExceptionHelper: "OFF"`

**Comment by at055612** [comment]
Seen this again with SQLExceptionHelper logging set to OFF.  Looks like we are not handling the exception and it is bubbling all the way up to the top.
```

WARN   [2018-11-16T11:53:02.388Z] [dw-29] org.eclipse.jetty.server.HttpChannel -  /api/dictionary/v1/list                                                                                                                                                                       
javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement                                                                                                                                                      
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1763)                                                                                                                                                                         
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1677)                                                                                                                                                                         
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1683)         
        at stroom.security.server.AuthenticationServiceImpl.getUserRef(AuthenticationServiceImpl.java:72)     
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement                                                                                                                                                                                    
        at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:72)                                                                                                                                                                  
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)                                                                                                                                                        
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)                                                                                                                                                                                
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)                                                                                                                                                                                
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:211)                                                                                                                                                                   
        at org.hibernate.id.IdentityGenerator$GetGeneratedKeysDelegate.executeAndExtract(IdentityGenerator.java:96)                                                                                                                                                             
        at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:58)                                                                                                                                                                  
        at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3032)                                                                                                                                                                    
        at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3558)                                                                                                                                                                     
        at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:98)                                                                                                                                                                 
        at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:492)                                                                                                                                                                                                   
        at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:197)                                                                                                                                                                             
        at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:181)                                                                                                                                                                                           
        at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:216)                                                                                                                                                                                                 
        at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:324)                                                                                                                                                           
        at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:288)                                                                                                                                                    
        at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:194)                                                                                                                                                              
        at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:125)                                                                                                                                                       
        at org.hibernate.jpa.event.internal.core.JpaPersistEventListener.saveWithGeneratedId(JpaPersistEventListener.java:84)                                                                                                                                                   
        at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:206)                                                                                                                                                     
        at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:149)                                                                                                                                                             
        at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:75)                                                                                                                                                              
        at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:811)                                                                                                                                                                                                 
        at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:784)                                                                                                                                                                                                     
        at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:789)                                                                                                                                                                                                     
        at org.hibernate.jpa.spi.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:1181)                                                                                                                                                                        
        ... 108 common frames omitted                                                                                                                                                                                                                                           
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'proxy-\x00' for key 'NAME'                                                                                                                                              
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)                                                                                                                                                                                                
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)                                                                                                                                                                         
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)                                                                                                                                                                 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)                                                                                                                                                                                                      
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)                                                                                                                                                                                                                 
        at com.mysql.jdbc.Util.getInstance(Util.java:408)                                                                                                                                                                                                                       
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935)                                                                                                                                                                                                        
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)                                                                                                                                                                                                           
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)                                                                                                                                                                                                           
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)                                                                                                                                                                                                                
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)                                                                                                                                                                                                             
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)                                                                                                                                                                                                     
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)                                                                                                                                                                                       
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)                                                                                                                                                                                  
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)                                                                                                                                                                                  
        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5098)                                                                                                                                                                                     
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)                                                                                                                                                                                          
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:384)                                                                                                                                                                 
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)                                                                                                                                                                   
        ... 129 common frames omitted     
```
